In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
sales_df = pd.read_csv("C:/Users/shubh/Desktop/AI_Sales_Intelligence/data/raw/sales.csv")
sales_df.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Region_ID,Channel,Quantity,Unit_Price,Discount_Percent,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status
0,ORD000001,2025-02-09,CUST01598,PROD0124,R019,Online,5,10142.95,0.36,50532.18,34410.75,16121.43,Credit Card,Completed
1,ORD000002,2026-01-19,CUST05309,PROD0147,R003,Store,2,5213.69,13.33,9037.41,6554.02,2483.39,UPI,Cancelled
2,ORD000003,2024-05-18,CUST03374,PROD0162,R015,Online,1,14802.17,3.85,14232.29,8727.21,5505.08,UPI,Completed
3,ORD000004,2024-06-13,CUST05538,PROD0045,R006,Online,1,2884.24,11.30,2558.32,1843.05,715.27,Debit Card,Completed
4,ORD000005,2026-03-04,CUST03609,PROD0049,R021,Store,1,1295.82,13.79,1117.13,1040.43,76.70,Credit Card,Completed

In [4]:
# check dataset structure 
print("Dataset Shape:", sales_df.shape)

print("\nColumn Names:")
print(sales_df.columns.tolist())

print("\nData Types:")
print(sales_df.dtypes)

Dataset Shape: (75000, 14)

Column Names:
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Region_ID', 'Channel', 'Quantity', 'Unit_Price', 'Discount_Percent', 'Sales_Amount', 'Cost_Amount', 'Profit', 'Payment_Method', 'Order_Status']

Data Types:
Order_ID             object
Order_Date           object
Customer_ID          object
Product_ID           object
Region_ID            object
Channel              object
Quantity              int64
Unit_Price          float64
Discount_Percent    float64
Sales_Amount        float64
Cost_Amount         float64
Profit              float64
Payment_Method       object
Order_Status         object
dtype: object

In [5]:

#  DATA QUALITY PROFILING

# 1. Dataset overview
print(f"Rows       : {sales_df.shape[0]:,}")
print(f"Columns    : {sales_df.shape[1]}")
print(f"Memory     : {sales_df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")


# 2. Column information
sales_df.info()


# 3. Missing values
missing_report = pd.DataFrame({
    "Missing_Count": sales_df.isnull().sum(),
    "Missing_Percentage": (
        sales_df.isnull().sum() / len(sales_df) * 100
    ).round(2)
})

missing_report = missing_report.sort_values(
    "Missing_Count",
    ascending=False
)

display(missing_report)


# 4. Duplicate records
duplicate_count = sales_df.duplicated().sum()

print(f"Duplicate rows: {duplicate_count:,}")
print(
    f"Duplicate percentage: "
    f"{duplicate_count / len(sales_df) * 100:.2f}%"
)


# 5. Unique values
unique_report = pd.DataFrame({
    "Column": sales_df.columns,
    "Unique_Count": [
        sales_df[col].nunique(dropna=False)
        for col in sales_df.columns
    ]
})

display(unique_report)


# 6. Numerical summary
display(sales_df.describe().T)


# 7. Categorical summary
categorical_columns = sales_df.select_dtypes(
    include="object"
).columns

for col in categorical_columns:
    print(f"\n--- {col} ---")
    display(
        sales_df[col]
        .value_counts(dropna=False)
        .head(15)
    )


# 8. Date range
sales_df["Order_Date"] = pd.to_datetime(
    sales_df["Order_Date"],
    errors="coerce"
)

print("Minimum Order Date:", sales_df["Order_Date"].min())
print("Maximum Order Date:", sales_df["Order_Date"].max())
print("Invalid Order Dates:", sales_df["Order_Date"].isna().sum())


# 9. Business-rule checks
print(
    "Zero Quantity:",
    (sales_df["Quantity"] == 0).sum()
)

print(
    "Negative Quantity:",
    (sales_df["Quantity"] < 0).sum()
)

print(
    "Negative Sales:",
    (sales_df["Sales_Amount"] < 0).sum()
)

print(
    "Negative Cost:",
    (sales_df["Cost_Amount"] < 0).sum()
)

print(
    "Discount > 100%:",
    (sales_df["Discount_Percent"] > 100).sum()
)

print(
    "Discount < 0%:",
    (sales_df["Discount_Percent"] < 0).sum()
)


# 10. Duplicate Order IDs
duplicate_order_ids = sales_df["Order_ID"].duplicated().sum()

print(
    f"Duplicate Order_ID values: "
    f"{duplicate_order_ids:,}"
)

print(
    f"Unique Order_IDs: "
    f"{sales_df['Order_ID'].nunique():,}"
)

Rows       : 75,000
Columns    : 14
Memory     : 35.96 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75000 entries, 0 to 74999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          75000 non-null  object
 1   Order_Date        75000 non-null  object
 2   Customer_ID       75000 non-null  object
 3   Product_ID        75000 non-null  object
 4   Region_ID         75000 non-null  object
 5   Channel           75000 non-null  object
 6   Quantity          75000 non-null  int64
 7   Unit_Price        75000 non-null  float64
 8   Discount_Percent  74650 non-null  float64
 9   Sales_Amount      75000 non-null  float64
 10  Cost_Amount       75000 non-null  float64
 11  Profit            75000 non-null  float64
 12  Payment_Method    75000 non-null  object
 13  Order_Status      75000 non-null  object
dtypes: float64(5), int64(1), object(8)
memory usage: 8.0+ MB

                  Missing_Count  Missing_Percentage
Discount_Percent            350                0.47
Order_ID                      0                0.00
Customer_ID                   0                0.00
Product_ID                    0                0.00
Region_ID                     0                0.00
Order_Date                    0                0.00
Channel                       0                0.00
Quantity                      0                0.00
Unit_Price                    0                0.00
Sales_Amount                  0                0.00
Cost_Amount                   0                0.00
Profit                        0                0.00
Payment_Method                0                0.00
Order_Status                  0                0.00

Duplicate rows: 0
Duplicate percentage: 0.00%

              Column  Unique_Count
0           Order_ID         75000
1         Order_Date           912
2        Customer_ID          6000
3         Product_ID           180
4          Region_ID            25
5            Channel             4
6           Quantity             7
7         Unit_Price           180
8   Discount_Percent          2673
9       Sales_Amount         68600
10       Cost_Amount          1080
11            Profit         66533
12    Payment_Method             6
13      Order_Status             3

,count,mean,std,min,25%,50%,75%,max
Quantity,75000.0,2.362360,1.473451,0.00,1.0000,2.000,3.00,6.00
Unit_Price,75000.0,8449.788939,5147.121457,255.39,4193.3400,7447.920,12486.26,19962.64
Discount_Percent,74650.0,9.165822,5.648066,0.00,4.9600,8.980,13.03,34.32
Sales_Amount,75000.0,18172.459140,17340.100797,186.43,6060.3275,12515.185,24698.50,119775.84
Cost_Amount,75000.0,13720.644249,12910.967154,164.69,4730.0200,9521.150,18768.78,71837.04
Profit,75000.0,4451.814891,5219.846230,-3522.66,1091.6925,2699.365,5722.69,48766.50

--- Order_ID ---

Order_ID
ORD000001    1
ORD000002    1
ORD000003    1
ORD000004    1
ORD000005    1
ORD000006    1
ORD000007    1
ORD000008    1
ORD000009    1
ORD000010    1
ORD000011    1
ORD000012    1
ORD000013    1
ORD000014    1
ORD000015    1
Name: count, dtype: int64

--- Order_Date ---

Order_Date
2024-01-30    112
2024-11-10    110
2025-12-25    107
2026-01-31    106
2024-10-15    105
2024-06-22    104
2026-01-11    104
2024-08-12    104
2024-07-17    103
2024-04-22    102
2026-04-27    102
2025-12-10    101
2024-08-23    101
2026-02-05    101
2026-01-24    101
Name: count, dtype: int64

--- Customer_ID ---

Customer_ID
CUST04483    27
CUST02381    26
CUST02369    26
CUST02987    25
CUST01933    25
CUST05073    24
CUST05152    24
CUST00689    24
CUST01273    24
CUST04105    23
CUST04736    23
CUST02106    23
CUST03518    23
CUST02217    23
CUST04942    23
Name: count, dtype: int64

--- Product_ID ---

Product_ID
PROD0102    475
PROD0178    467
PROD0019    464
PROD0156    462
PROD0038    459
PROD0150    458
PROD0122    457
PROD0173    455
PROD0068    451
PROD0112    450
PROD0002    450
PROD0016    448
PROD0066    447
PROD0092    447
PROD0162    445
Name: count, dtype: int64

--- Region_ID ---

Region_ID
R010    3428
R016    3357
R012    3181
R013    3152
R001    3126
R018    3109
R007    3096
R025    3083
R019    3069
R023    3067
R009    3060
R017    3029
R005    3021
R003    2942
R024    2933
Name: count, dtype: int64

--- Channel ---

Channel
Online         41241
Store          18626
Marketplace    15013
online           120
Name: count, dtype: int64

--- Payment_Method ---

Payment_Method
UPI            28254
Credit Card    16537
Net Banking    11933
Debit Card     10667
Cash            7429
UPI              180
Name: count, dtype: int64

--- Order_Status ---

Order_Status
Completed    66669
Cancelled     4478
Pending       3853
Name: count, dtype: int64

Minimum Order Date: 2024-01-01 00:00:00
Maximum Order Date: 2026-06-30 00:00:00
Invalid Order Dates: 0
Zero Quantity: 80
Negative Quantity: 0
Negative Sales: 0
Negative Cost: 0
Discount > 100%: 0
Discount < 0%: 0
Duplicate Order_ID values: 0
Unique Order_IDs: 75,000

In [6]:
# DETAILED DATA QUALITY INVESTIGATION

print("\n1. DUPLICATE ROWS")
print("Duplicate complete rows:", sales_df.duplicated().sum())

print("\n2. DUPLICATE ORDER IDs")
duplicate_orders = sales_df[
    sales_df["Order_ID"].duplicated(keep=False)
].sort_values("Order_ID")

print("Rows belonging to duplicate Order_IDs:",
      len(duplicate_orders))

display(duplicate_orders.head(20))


print("\n3. QUANTITY VALIDATION")
quantity_issues = sales_df[
    sales_df["Quantity"] <= 0
]

print("Quantity <= 0:", len(quantity_issues))

display(
    quantity_issues[
        ["Order_ID", "Quantity", "Sales_Amount", "Profit"]
    ].head(20)
)


print("\n4. DISCOUNT VALIDATION")

print("Missing discount:",
      sales_df["Discount_Percent"].isna().sum())

print("Discount < 0:",
      (sales_df["Discount_Percent"] < 0).sum())

print("Discount > 100:",
      (sales_df["Discount_Percent"] > 100).sum())


print("\n5. SALES / COST / PROFIT VALIDATION")

print("Negative Sales:",
      (sales_df["Sales_Amount"] < 0).sum())

print("Negative Cost:",
      (sales_df["Cost_Amount"] < 0).sum())

print("Negative Profit:",
      (sales_df["Profit"] < 0).sum())

print("Zero Sales:",
      (sales_df["Sales_Amount"] == 0).sum())


print("\n6. CHANNEL STANDARDIZATION CHECK")

print(
    sales_df["Channel"]
    .value_counts(dropna=False)
)


print("\n7. PAYMENT METHOD STANDARDIZATION CHECK")
print(
    sales_df["Payment_Method"]
    .value_counts(dropna=False)
)


print("\n8. ORDER STATUS CHECK")
print(
    sales_df["Order_Status"]
    .value_counts(dropna=False)
)


print("\n9. DATE VALIDATION")

date_check = pd.to_datetime(
    sales_df["Order_Date"],
    errors="coerce"
)

print("Invalid dates:", date_check.isna().sum())
print("Minimum date:", date_check.min())
print("Maximum date:", date_check.max())


print("\n10. PROFIT CALCULATION VALIDATION")

calculated_profit = (
    sales_df["Sales_Amount"] -
    sales_df["Cost_Amount"]
)

profit_difference = (
    sales_df["Profit"] - calculated_profit
)

print(
    "Rows where Profit calculation differs:",
    (abs(profit_difference) > 0.01).sum()
)

print(
    "Maximum difference:",
    abs(profit_difference).max()
)

1. DUPLICATE ROWS
Duplicate complete rows: 0

2. DUPLICATE ORDER IDs
Rows belonging to duplicate Order_IDs: 0

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Product_ID, Region_ID, Channel, Quantity, Unit_Price, Discount_Percent, Sales_Amount, Cost_Amount, Profit, Payment_Method, Order_Status]
Index: []

3. QUANTITY VALIDATION
Quantity <= 0: 80

        Order_ID  Quantity  Sales_Amount   Profit
1021   ORD001022         0      24799.36  4757.26
1329   ORD001330         0       4135.80  1329.98
3874   ORD003875         0      27701.83  9974.91
4006   ORD004007         0       3857.51   978.15
5899   ORD005900         0       6342.84   696.69
6349   ORD006350         0       7607.36  2065.30
8596   ORD008597         0      34427.38  7704.58
9316   ORD009317         0       5273.43  1375.07
12087  ORD012088         0       5857.75   655.60
12610  ORD012611         0      22614.38  6229.33
15162  ORD015163         0        709.47   215.40
15973  ORD015974         0       7166.90   284.72
18949  ORD018950         0       5309.50  1430.33
19553  ORD019554         0      16924.75  5158.14
20352  ORD020353         0      25996.62  4837.48
21205  ORD021206         0       5688.00    83.72
22932  ORD022933         0      16616.35  3218.71
24156  ORD024157         0      20746.65  4521.42
24540  ORD024541         0       7269.08   588.38
24676  ORD024677         0       6405.63   860.96

4. DISCOUNT VALIDATION
Missing discount: 350
Discount < 0: 0
Discount > 100: 0

5. SALES / COST / PROFIT VALIDATION
Negative Sales: 0
Negative Cost: 0
Negative Profit: 907
Zero Sales: 0

6. CHANNEL STANDARDIZATION CHECK
Channel
Online         41241
Store          18626
Marketplace    15013
online           120
Name: count, dtype: int64

7. PAYMENT METHOD STANDARDIZATION CHECK
Payment_Method
UPI            28254
Credit Card    16537
Net Banking    11933
Debit Card     10667
Cash            7429
UPI              180
Name: count, dtype: int64

8. ORDER STATUS CHECK
Order_Status
Completed    66669
Cancelled     4478
Pending       3853
Name: count, dtype: int64

9. DATE VALIDATION
Invalid dates: 0
Minimum date: 2024-01-01 00:00:00
Maximum date: 2026-06-30 00:00:00

10. PROFIT CALCULATION VALIDATION
Rows where Profit calculation differs: 0
Maximum difference: 1.4551915228366852e-11

In [7]:
# INVESTIGATION: MISSING DISCOUNTS

missing_discount = sales_df[
    sales_df["Discount_Percent"].isna()
].copy()

print("MISSING DISCOUNT INVESTIGATION")
print(f"Records with missing discount: {len(missing_discount)}")


# 1. Basic statistics
print("NUMERICAL SUMMARY")

display(
    missing_discount[
        [
            "Quantity",
            "Unit_Price",
            "Sales_Amount",
            "Cost_Amount",
            "Profit"
        ]
    ].describe()
)


# 2. Check whether Sales_Amount equals Quantity × Unit_Price
missing_discount["Expected_Sales_No_Discount"] = (
    missing_discount["Quantity"] *
    missing_discount["Unit_Price"]
)

missing_discount["Sales_Difference"] = (
    missing_discount["Expected_Sales_No_Discount"]
    - missing_discount["Sales_Amount"]
)


print("DISCOUNT INFERENCE CHECK")
print(
    "Records where sales match full price:",
    (
        abs(missing_discount["Sales_Difference"]) < 0.01
    ).sum()
)

print(
    "Records where sales differ from full price:",
    (
        abs(missing_discount["Sales_Difference"]) >= 0.01
    ).sum()
)


# 3. Show examples
print("SAMPLE MISSING-DISCOUNT RECORDS")

display(
    missing_discount[
        [
            "Order_ID",
            "Quantity",
            "Unit_Price",
            "Sales_Amount",
            "Expected_Sales_No_Discount",
            "Sales_Difference",
            "Profit"
        ]
    ].head(20)
)


# 4. Estimate implied discount
missing_discount["Implied_Discount_Percent"] = (
    1 -
    missing_discount["Sales_Amount"] /
    missing_discount["Expected_Sales_No_Discount"]
) * 100

print("IMPLIED DISCOUNT")

display(
    missing_discount[
        "Implied_Discount_Percent"
    ].describe()
)

MISSING DISCOUNT INVESTIGATION
Records with missing discount: 350
NUMERICAL SUMMARY

         Quantity    Unit_Price  Sales_Amount   Cost_Amount        Profit
count  350.000000    350.000000    350.000000    350.000000    350.000000
mean     2.397143   8710.766371  17827.427343  13631.931657   4195.495686
std      1.500522   5070.765960  15140.432468  11630.668121   4428.761478
min      0.000000    255.390000    205.130000    164.690000   -985.040000
25%      1.000000   4622.910000   7150.232500   5478.490000   1298.097500
50%      2.000000   8066.730000  12955.590000   9707.230000   2715.625000
75%      3.000000  12629.577500  26032.522500  19654.732500   5368.372500
max      6.000000  19962.640000  73797.890000  60608.700000  26458.330000

DISCOUNT INFERENCE CHECK
Records where sales match full price: 19
Records where sales differ from full price: 331
SAMPLE MISSING-DISCOUNT RECORDS

,Order_ID,Quantity,Unit_Price,Sales_Amount,Expected_Sales_No_Discount,Sales_Difference,Profit
186,ORD000187,1,5204.80,4795.18,5204.80,409.62,1595.13
234,ORD000235,2,5547.10,10222.20,11094.20,872.00,2337.14
978,ORD000979,6,12170.89,69381.38,73025.34,3643.96,18221.36
1435,ORD001436,3,12001.30,33822.06,36003.90,2181.84,9240.21
1468,ORD001469,4,1029.53,4086.00,4118.12,32.12,1173.76
1490,ORD001491,3,15732.26,44737.83,47196.78,2458.95,12925.38
1611,ORD001612,1,13725.41,11433.27,13725.41,2292.14,1692.06
1698,ORD001699,3,3396.38,9306.76,10189.14,882.38,3112.27
1772,ORD001773,5,11488.02,49180.21,57440.10,8259.89,3698.81
2551,ORD002552,3,7568.74,20617.25,22706.22,2088.97,4527.02
2775,ORD002776,4,6354.88,24105.33,25419.52,1314.19,8588.65
2956,ORD002957,2,15469.47,28454.54,30938.94,2484.40,10515.42
2961,ORD002962,3,1301.37,3746.77,3904.11,157.34,702.43
2975,ORD002976,6,5285.30,29415.87,31711.80,2295.93,9744.63
3175,ORD003176,4,11737.65,38837.54,46950.60,8113.06,4051.26
3213,ORD003214,6,5573.33,28952.33,33439.98,4487.65,7678.31
3317,ORD003318,1,15765.29,13105.69,15765.29,2659.60,2513.01
3698,ORD003699,2,7461.76,14016.17,14923.52,907.35,4806.79
5855,ORD005856,6,717.80,3846.40,4306.80,460.40,526.06
6027,ORD006028,2,16109.18,30375.47,32218.36,1842.89,8207.15

IMPLIED DISCOUNT

c:\Users\shubh\AppData\Local\Programs\Python\Python314\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

count    350.000000
mean           -inf
std             NaN
min            -inf
25%        4.777862
50%        8.325024
75%       12.230027
max       25.680003
Name: Implied_Discount_Percent, dtype: float64

In [8]:
# MISSING DISCOUNT - FINAL INVESTIGATION

missing_discount = sales_df[
    sales_df["Discount_Percent"].isna()
].copy()

# Calculate gross sales
missing_discount["Gross_Sales"] = (
    missing_discount["Quantity"] *
    missing_discount["Unit_Price"]
)

# Identify zero-quantity records
zero_quantity_missing_discount = missing_discount[
    missing_discount["Quantity"] == 0
]

print("ZERO-QUANTITY RECORDS AMONG MISSING DISCOUNTS")
print(
    "Zero-quantity records:",
    len(zero_quantity_missing_discount)
)


# Remove zero-quantity records for discount inference
valid_discount_records = missing_discount[
    missing_discount["Gross_Sales"] > 0
].copy()

# Calculate implied discount
valid_discount_records["Implied_Discount_Percent"] = (
    (
        valid_discount_records["Gross_Sales"]
        - valid_discount_records["Sales_Amount"]
    )
    / valid_discount_records["Gross_Sales"]
) * 100

valid_discount_records["Implied_Discount_Percent"] = (
    valid_discount_records["Implied_Discount_Percent"]
    .round(2)
)


print("IMPLIED DISCOUNT SUMMARY")
display(
    valid_discount_records[
        "Implied_Discount_Percent"
    ].describe()
)


# Categorize records
no_discount = valid_discount_records[
    valid_discount_records["Implied_Discount_Percent"].abs() < 0.01
]

discount_applied = valid_discount_records[
    valid_discount_records["Implied_Discount_Percent"] > 0.01
]


print("DISCOUNT CLASSIFICATION")
print("No discount / approximately 0%:",
      len(no_discount))

print("Discount appears to be applied:",
      len(discount_applied))

print("Zero quantity:",
      len(zero_quantity_missing_discount))


# Show implied discounts
print("\n" + "=" * 60)
print("SAMPLE IMPLIED DISCOUNTS")
display(
    valid_discount_records[
        [
            "Order_ID",
            "Quantity",
            "Unit_Price",
            "Gross_Sales",
            "Sales_Amount",
            "Implied_Discount_Percent"
        ]
    ].head(20)
)


# Check whether implied discounts fall within sensible range
print("IMPLIED DISCOUNT VALIDATION")
print(
    "Implied discount < 0%:",
    (
        valid_discount_records[
            "Implied_Discount_Percent"
        ] < 0
    ).sum()
)

print(
    "Implied discount > 100%:",
    (
        valid_discount_records[
            "Implied_Discount_Percent"
        ] > 100
    ).sum()
)

ZERO-QUANTITY RECORDS AMONG MISSING DISCOUNTS
Zero-quantity records: 1
IMPLIED DISCOUNT SUMMARY

count    349.000000
mean       8.755301
std        5.468005
min        0.000000
25%        4.800000
50%        8.380000
75%       12.230000
max       25.680000
Name: Implied_Discount_Percent, dtype: float64

DISCOUNT CLASSIFICATION
No discount / approximately 0%: 19
Discount appears to be applied: 330
Zero quantity: 1

============================================================
SAMPLE IMPLIED DISCOUNTS

,Order_ID,Quantity,Unit_Price,Gross_Sales,Sales_Amount,Implied_Discount_Percent
186,ORD000187,1,5204.80,5204.80,4795.18,7.87
234,ORD000235,2,5547.10,11094.20,10222.20,7.86
978,ORD000979,6,12170.89,73025.34,69381.38,4.99
1435,ORD001436,3,12001.30,36003.90,33822.06,6.06
1468,ORD001469,4,1029.53,4118.12,4086.00,0.78
1490,ORD001491,3,15732.26,47196.78,44737.83,5.21
1611,ORD001612,1,13725.41,13725.41,11433.27,16.70
1698,ORD001699,3,3396.38,10189.14,9306.76,8.66
1772,ORD001773,5,11488.02,57440.10,49180.21,14.38
2551,ORD002552,3,7568.74,22706.22,20617.25,9.20
2775,ORD002776,4,6354.88,25419.52,24105.33,5.17
2956,ORD002957,2,15469.47,30938.94,28454.54,8.03
2961,ORD002962,3,1301.37,3904.11,3746.77,4.03
2975,ORD002976,6,5285.30,31711.80,29415.87,7.24
3175,ORD003176,4,11737.65,46950.60,38837.54,17.28
3213,ORD003214,6,5573.33,33439.98,28952.33,13.42
3317,ORD003318,1,15765.29,15765.29,13105.69,16.87
3698,ORD003699,2,7461.76,14923.52,14016.17,6.08
5855,ORD005856,6,717.80,4306.80,3846.40,10.69
6027,ORD006028,2,16109.18,32218.36,30375.47,5.72

IMPLIED DISCOUNT VALIDATION
Implied discount < 0%: 0
Implied discount > 100%: 0

## Data Cleaning Decisions

### 1. Order_Date
- Convert from object to datetime.
- Invalid dates will be identified and handled.
- Current validation shows 0 invalid dates.

### 2. Missing Discount_Percent
- 19 records have implied discount ≈ 0%.
- 330 records have an identifiable implied discount.
- 1 record has Quantity = 0 and cannot be reliably inferred.
- For valid transactions, calculate:
  
  Implied Discount % =
  ((Quantity × Unit Price) - Sales Amount)
  / (Quantity × Unit Price) × 100

### 3. Channel
- Standardize inconsistent values such as `online` → `Online`.

### 4. Payment_Method
- Remove leading/trailing whitespace.
- Standardize values such as `UPI ` → `UPI`.

### 5. Quantity
- Quantity = 0 is considered an invalid transaction record.
- We will investigate before deciding whether to remove it.

### 6. Negative Profit
- Keep negative-profit transactions.
- Negative profit can represent legitimate loss-making sales.
- These records will be analyzed as a business insight.

### 7. Profit
- Profit calculation has been validated.
- No correction required because:
  
  Profit = Sales Amount - Cost Amount

### 8. Duplicate Records
- Complete duplicate rows and duplicate Order_IDs will be investigated.
- No records will be removed without evidence.

### 9. Order Status
- Completed, Cancelled and Pending transactions will be retained initially.
- Their treatment will depend on the analytical metric being calculated.

In [9]:
# FINAL INVESTIGATION BEFORE CLEANING

# 1. Complete duplicate rows
duplicate_rows = sales_df[
    sales_df.duplicated(keep=False)
].sort_values("Order_ID")


print("COMPLETE DUPLICATE ROWS")
print("Duplicate rows:", sales_df.duplicated().sum())

if len(duplicate_rows) > 0:
    display(duplicate_rows.head(20))


# 2. Duplicate Order IDs
duplicate_order_ids = sales_df[
    sales_df["Order_ID"].duplicated(keep=False)
].sort_values("Order_ID")

print("DUPLICATE ORDER IDs")
print(
    "Rows with duplicated Order_ID:",
    len(duplicate_order_ids)
)

if len(duplicate_order_ids) > 0:
    display(duplicate_order_ids.head(20))


# 3. Zero / negative quantities
quantity_issues = sales_df[
    sales_df["Quantity"] <= 0
].copy()

print("INVALID QUANTITY RECORDS")
print("Quantity <= 0:", len(quantity_issues))

if len(quantity_issues) > 0:
    display(
        quantity_issues[
            [
                "Order_ID",
                "Order_Date",
                "Customer_ID",
                "Product_ID",
                "Quantity",
                "Sales_Amount",
                "Cost_Amount",
                "Profit",
                "Order_Status"
            ]
        ]
    )


# 4. Check zero quantity against sales/profit
print("ZERO QUANTITY BUSINESS VALIDATION")
zero_quantity = sales_df[
    sales_df["Quantity"] == 0
]

print("Zero quantity:", len(zero_quantity))
print(
    "Zero quantity with non-zero sales:",
    (zero_quantity["Sales_Amount"] != 0).sum()
)
print(
    "Zero quantity with non-zero cost:",
    (zero_quantity["Cost_Amount"] != 0).sum()
)
print(
    "Zero quantity with non-zero profit:",
    (zero_quantity["Profit"] != 0).sum()
)


# 5. Negative profit investigation
negative_profit = sales_df[
    sales_df["Profit"] < 0
].copy()

print("NEGATIVE PROFIT INVESTIGATION")
print("Negative-profit records:", len(negative_profit))

display(
    negative_profit[
        [
            "Order_ID",
            "Quantity",
            "Unit_Price",
            "Discount_Percent",
            "Sales_Amount",
            "Cost_Amount",
            "Profit",
            "Channel",
            "Order_Status"
        ]
    ].head(20)
)

COMPLETE DUPLICATE ROWS
Duplicate rows: 0
DUPLICATE ORDER IDs
Rows with duplicated Order_ID: 0
INVALID QUANTITY RECORDS
Quantity <= 0: 80

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Sales_Amount,Cost_Amount,Profit,Order_Status
1021,ORD001022,2025-05-06,CUST01440,PROD0033,0,24799.36,20042.10,4757.26,Completed
1329,ORD001330,2024-02-14,CUST00336,PROD0137,0,4135.80,2805.82,1329.98,Completed
3874,ORD003875,2024-05-22,CUST05773,PROD0040,0,27701.83,17726.92,9974.91,Completed
4006,ORD004007,2025-10-07,CUST05056,PROD0111,0,3857.51,2879.36,978.15,Completed
5899,ORD005900,2025-01-16,CUST05100,PROD0174,0,6342.84,5646.15,696.69,Completed
...,...,...,...,...,...,...,...,...,...
72393,ORD072394,2025-09-17,CUST04234,PROD0041,0,7150.99,5152.16,1998.83,Completed
72495,ORD072496,2025-04-04,CUST05481,PROD0120,0,17921.06,12997.41,4923.65,Completed
72767,ORD072768,2024-09-14,CUST05166,PROD0120,0,17993.53,12997.41,4996.12,Completed
73915,ORD073916,2024-06-04,CUST04278,PROD0058,0,2444.41,1818.81,625.60,Completed
74503,ORD074504,2025-08-22,CUST02210,PROD0033,0,16300.10,13361.40,2938.70,Completed

ZERO QUANTITY BUSINESS VALIDATION
Zero quantity: 80
Zero quantity with non-zero sales: 80
Zero quantity with non-zero cost: 80
Zero quantity with non-zero profit: 80
NEGATIVE PROFIT INVESTIGATION
Negative-profit records: 907

,Order_ID,Quantity,Unit_Price,Discount_Percent,Sales_Amount,Cost_Amount,Profit,Channel,Order_Status
17,ORD000018,6,2745.78,22.55,12759.64,13281.66,-522.02,Online,Completed
24,ORD000025,2,8761.87,20.54,13924.36,14265.32,-340.96,Online,Completed
40,ORD000041,4,7244.80,25.34,21635.87,22617.84,-981.97,Online,Completed
59,ORD000060,1,5395.83,23.87,4107.85,4511.00,-403.15,Online,Completed
93,ORD000094,2,14323.08,24.90,21513.27,21975.60,-462.33,Online,Completed
389,ORD000390,5,5395.83,16.84,22435.86,22555.00,-119.14,Online,Completed
423,ORD000424,3,7374.91,18.65,17998.47,18109.59,-111.12,Online,Completed
565,ORD000566,1,12486.26,21.12,9849.16,10343.69,-494.53,Online,Completed
732,ORD000733,3,14057.37,20.76,33417.18,34323.42,-906.24,Marketplace,Completed
758,ORD000759,1,891.52,16.76,742.10,753.72,-11.62,Online,Completed
1093,ORD001094,2,5926.22,18.82,9621.81,9890.92,-269.11,Marketplace,Completed
1097,ORD001098,2,12486.26,18.39,20380.07,20687.38,-307.31,Online,Completed
1109,ORD001110,2,4032.23,18.81,6547.54,6612.70,-65.16,Store,Completed
1321,ORD001322,1,12200.98,19.17,9862.05,10101.45,-239.40,Store,Completed
1373,ORD001374,2,4032.23,20.31,6426.57,6612.70,-186.13,Online,Completed
1500,ORD001501,6,14425.18,21.78,67700.25,69605.82,-1905.57,Online,Completed
1512,ORD001513,4,4366.12,24.77,13138.53,13615.60,-477.07,Online,Completed
1568,ORD001569,1,10298.65,22.42,7989.69,8216.21,-226.52,Store,Completed
1616,ORD001617,3,891.52,17.42,2208.65,2261.16,-52.51,Online,Completed
1667,ORD001668,2,14323.08,23.91,21796.86,21975.60,-178.74,Marketplace,Completed

In [10]:
# FACT SALES - DATA CLEANING PIPELINE

# Create a copy so the raw dataset remains untouched
sales_clean = sales_df.copy()

print("STARTING DATA CLEANING")

print(f"Original rows: {len(sales_clean):,}")


# ------------------------------------------------------------
# 1. Convert Order_Date to datetime
# ------------------------------------------------------------

sales_clean["Order_Date"] = pd.to_datetime(
    sales_clean["Order_Date"],
    errors="coerce"
)

print("\n1. Order_Date converted to datetime")


# ------------------------------------------------------------
# 2. Standardize text columns
# ------------------------------------------------------------

sales_clean["Channel"] = (
    sales_clean["Channel"]
    .astype("string")
    .str.strip()
    .str.title()
)

sales_clean["Payment_Method"] = (
    sales_clean["Payment_Method"]
    .astype("string")
    .str.strip()
)

print("2. Text fields standardized")


# ------------------------------------------------------------
# 3. Remove invalid quantity records
# ------------------------------------------------------------

invalid_quantity_mask = sales_clean["Quantity"] <= 0

invalid_quantity_count = invalid_quantity_mask.sum()

sales_clean = sales_clean[
    ~invalid_quantity_mask
].copy()

print(
    f"3. Removed invalid quantity records: "
    f"{invalid_quantity_count}"
)


# ------------------------------------------------------------
# 4. Reconstruct missing discounts
# ------------------------------------------------------------

missing_discount_mask = (
    sales_clean["Discount_Percent"].isna()
)

gross_sales = (
    sales_clean["Quantity"] *
    sales_clean["Unit_Price"]
)

# Calculate implied discount only where gross sales > 0
implied_discount = (
    (
        gross_sales -
        sales_clean["Sales_Amount"]
    )
    / gross_sales
) * 100

# Fill missing discounts using the transaction-level calculation
sales_clean.loc[
    missing_discount_mask,
    "Discount_Percent"
] = implied_discount[missing_discount_mask]

# Round discount
sales_clean["Discount_Percent"] = (
    sales_clean["Discount_Percent"]
    .round(2)
)

print(
    "4. Missing discounts reconstructed"
)


# ------------------------------------------------------------
# 5. Validate discount values
# ------------------------------------------------------------

invalid_discount = (
    (sales_clean["Discount_Percent"] < 0) |
    (sales_clean["Discount_Percent"] > 100)
)

print(
    "5. Invalid discount values after cleaning:",
    invalid_discount.sum()
)


# ------------------------------------------------------------
# 6. Validate profit calculation
# ------------------------------------------------------------

calculated_profit = (
    sales_clean["Sales_Amount"] -
    sales_clean["Cost_Amount"]
)

profit_difference = (
    sales_clean["Profit"] -
    calculated_profit
)

profit_errors = (
    abs(profit_difference) > 0.01
)

print(
    "6. Profit calculation errors:",
    profit_errors.sum()
)


# ------------------------------------------------------------
# 7. Save cleaned dataset
# ------------------------------------------------------------

output_path = (
    "C:/Users/shubh/Desktop/AI_Sales_Intelligence/data/cleaned/sales_clean.csv"
)

sales_clean.to_csv(
    output_path,
    index=False
)

print("\n" + "=" * 60)
print("CLEANING COMPLETE")
print("=" * 60)

print(f"Original rows : {len(sales_df):,}")
print(f"Cleaned rows  : {len(sales_clean):,}")
print(
    f"Rows removed  : "
    f"{len(sales_df) - len(sales_clean):,}"
)

print(f"\nSaved to: {output_path}")

STARTING DATA CLEANING
Original rows: 75,000

1. Order_Date converted to datetime
2. Text fields standardized
3. Removed invalid quantity records: 80
4. Missing discounts reconstructed
5. Invalid discount values after cleaning: 0
6. Profit calculation errors: 0

============================================================
CLEANING COMPLETE
============================================================
Original rows : 75,000
Cleaned rows  : 74,920
Rows removed  : 80

Saved to: C:/Users/shubh/Desktop/AI_Sales_Intelligence/data/cleaned/sales_clean.csv

In [11]:
# ============================================================
# CLEANED DATASET VALIDATION
# ============================================================

print("CLEANED DATASET VALIDATION")


# 1. Shape
print("\n1. DATASET SIZE")
print(f"Rows    : {len(sales_clean):,}")
print(f"Columns : {len(sales_clean.columns)}")


# 2. Missing values
print("\n2. MISSING VALUES")

remaining_missing = sales_clean.isnull().sum()
remaining_missing = remaining_missing[
    remaining_missing > 0
]

if len(remaining_missing) == 0:
    print("No missing values found.")
else:
    print(remaining_missing)


# 3. Duplicates
print("\n3. DUPLICATES")

print(
    "Duplicate rows:",
    sales_clean.duplicated().sum()
)

print(
    "Duplicate Order_ID:",
    sales_clean["Order_ID"].duplicated().sum()
)


# 4. Data types
print("\n4. DATA TYPES")

print(
    sales_clean.dtypes
)


# 5. Quantity validation
print("\n5. QUANTITY VALIDATION")

print(
    "Quantity <= 0:",
    (sales_clean["Quantity"] <= 0).sum()
)


# 6. Discount validation
print("\n6. DISCOUNT VALIDATION")

print(
    "Discount < 0:",
    (sales_clean["Discount_Percent"] < 0).sum()
)

print(
    "Discount > 100:",
    (sales_clean["Discount_Percent"] > 100).sum()
)


# 7. Financial validation
print("\n7. FINANCIAL VALIDATION")

print(
    "Negative Sales:",
    (sales_clean["Sales_Amount"] < 0).sum()
)

print(
    "Negative Cost:",
    (sales_clean["Cost_Amount"] < 0).sum()
)

print(
    "Negative Profit:",
    (sales_clean["Profit"] < 0).sum()
)


# 8. Text consistency
print("\n8. CHANNEL VALUES")

print(
    sales_clean["Channel"].value_counts()
)

print("\nPAYMENT METHODS")

print(
    sales_clean["Payment_Method"].value_counts()
)


# 9. Date validation
print("\n9. DATE VALIDATION")

print(
    "Invalid dates:",
    sales_clean["Order_Date"].isna().sum()
)

print(
    "Min date:",
    sales_clean["Order_Date"].min()
)

print(
    "Max date:",
    sales_clean["Order_Date"].max()
)


# 10. Profit reconciliation
print("\n10. PROFIT RECONCILIATION")

calculated_profit = (
    sales_clean["Sales_Amount"] -
    sales_clean["Cost_Amount"]
)

difference = (
    sales_clean["Profit"] -
    calculated_profit
)

print(
    "Profit mismatches:",
    (abs(difference) > 0.01).sum()
)

CLEANED DATASET VALIDATION

1. DATASET SIZE
Rows    : 74,920
Columns : 14

2. MISSING VALUES
No missing values found.

3. DUPLICATES
Duplicate rows: 0
Duplicate Order_ID: 0

4. DATA TYPES
Order_ID                    object
Order_Date          datetime64[ns]
Customer_ID                 object
Product_ID                  object
Region_ID                   object
Channel             string[python]
Quantity                     int64
Unit_Price                 float64
Discount_Percent           float64
Sales_Amount               float64
Cost_Amount                float64
Profit                     float64
Payment_Method      string[python]
Order_Status                object
dtype: object

5. QUANTITY VALIDATION
Quantity <= 0: 0

6. DISCOUNT VALIDATION
Discount < 0: 0
Discount > 100: 0

7. FINANCIAL VALIDATION
Negative Sales: 0
Negative Cost: 0
Negative Profit: 906

8. CHANNEL VALUES
Channel
Online         41322
Store          18604
Marketplace    14994
Name: count, dtype: Int64

PAYMENT METHODS
Payment_Method
UPI            28397
Credit Card    16525
Net Banking    11921
Debit Card     10656
Cash            7421
Name: count, dtype: Int64

9. DATE VALIDATION
Invalid dates: 0
Min date: 2024-01-01 00:00:00
Max date: 2026-06-30 00:00:00

10. PROFIT RECONCILIATION
Profit mismatches: 0

In [12]:

# MULTI-TABLE DATA VALIDATION

print("LOADING ALL PROJECT TABLES")

# Load dimension tables
customers_df = pd.read_csv("C:/Users/shubh/Desktop/AI_Sales_Intelligence/data/raw/customer.csv")
products_df = pd.read_csv("C:/Users/shubh/Desktop/AI_Sales_Intelligence/data/raw/product.csv")
date_df = pd.read_csv("C:/Users/shubh/Desktop/AI_Sales_Intelligence/data/raw/date.csv")
regions_df = pd.read_csv("C:/Users/shubh/Desktop/AI_Sales_Intelligence/data/raw/region.csv")

# Load supporting fact tables
returns_df = pd.read_csv("C:/Users/shubh/Desktop/AI_Sales_Intelligence/data/raw/returns.csv")
targets_df = pd.read_csv("C:/Users/shubh/Desktop/AI_Sales_Intelligence/data/raw/targets.csv")

tables = {
    "Sales": sales_clean,
    "Customer": customers_df,
    "Product": products_df,
    "Date": date_df,
    "Region": regions_df,
    "Returns": returns_df,
    "Targets": targets_df
}


# 1. TABLE SIZES

print("TABLE SIZES")

table_summary = pd.DataFrame({
    "Table": tables.keys(),
    "Rows": [df.shape[0] for df in tables.values()],
    "Columns": [df.shape[1] for df in tables.values()]
})

display(table_summary)


# 2. MISSING VALUES

print("MISSING VALUES BY TABLE")

for table_name, df in tables.items():

    missing = df.isnull().sum()
    missing = missing[missing > 0]

    print(f"\n--- {table_name} ---")

    if len(missing) == 0:
        print("No missing values.")
    else:
        display(missing)


# 3. DUPLICATE RECORDS

print("DUPLICATE RECORDS")

for table_name, df in tables.items():

    print(
        f"{table_name}: "
        f"{df.duplicated().sum():,} duplicate rows"
    )


# 4. PRIMARY KEY UNIQUENESS

print("PRIMARY KEY VALIDATION")

primary_keys = {
    "Customer": ("Customer_ID", customers_df),
    "Product": ("Product_ID", products_df),
    "Date": ("Date", date_df),
    "Region": ("Region_ID", regions_df),
    "Sales": ("Order_ID", sales_clean),
    "Returns": ("Return_ID", returns_df),
    "Targets": ("Target_ID", targets_df)
}

for table_name, (key, df) in primary_keys.items():

    duplicate_keys = df[key].duplicated().sum()

    print(
        f"{table_name:20} | "
        f"{key:15} | "
        f"Duplicates: {duplicate_keys:,}"
    )


# 5. FACT SALES → CUSTOMER

print("FACT SALES → CUSTOMER VALIDATION")

missing_customers = ~sales_clean["Customer_ID"].isin(
    customers_df["Customer_ID"]
)

print(
    "Sales records with missing customer:",
    missing_customers.sum()
)


# 6. FACT SALES → PRODUCT

print("FACT SALES → PRODUCT VALIDATION")

missing_products = ~sales_clean["Product_ID"].isin(
    products_df["Product_ID"]
)

print(
    "Sales records with missing product:",
    missing_products.sum()
)


# 7. FACT SALES → REGION

print("FACT SALES → REGION VALIDATION")

missing_regions = ~sales_clean["Region_ID"].isin(
    regions_df["Region_ID"]
)

print(
    "Sales records with missing region:",
    missing_regions.sum()
)


# 8. RETURNS → SALES

print("RETURNS → SALES VALIDATION")

missing_return_orders = ~returns_df["Order_ID"].isin(
    sales_clean["Order_ID"]
)

print(
    "Returns without matching sales order:",
    missing_return_orders.sum()
)


# 9. RETURNS → CUSTOMER

missing_return_customers = ~returns_df["Customer_ID"].isin(
    customers_df["Customer_ID"]
)

print(
    "Returns with missing customer:",
    missing_return_customers.sum()
)


# 10. RETURNS → PRODUCT

missing_return_products = ~returns_df["Product_ID"].isin(
    products_df["Product_ID"]
)

print(
    "Returns with missing product:",
    missing_return_products.sum()
)


# 11. TARGETS → REGION

missing_target_regions = ~targets_df["Region_ID"].isin(
    regions_df["Region_ID"]
)

print("TARGETS → REGION VALIDATION")

print(
    "Targets with missing region:",
    missing_target_regions.sum()
)


# 12. DATE COVERAGE

print("DATE COVERAGE")

sales_dates = pd.to_datetime(sales_clean["Order_Date"])
date_dimension = pd.to_datetime(date_df["Date"])

print(
    "Sales min date:",
    sales_dates.min()
)

print(
    "Sales max date:",
    sales_dates.max()
)

print(
    "Date dimension min:",
    date_dimension.min()
)

print(
    "Date dimension max:",
    date_dimension.max()
)


# 13. REGION DISTRIBUTION

print("REGION DISTRIBUTION")

region_distribution = (
    sales_clean["Region_ID"]
    .value_counts()
    .reset_index()
)

region_distribution.columns = [
    "Region_ID",
    "Sales_Record_Count"
]

display(region_distribution.head(10))

LOADING ALL PROJECT TABLES

TABLE SIZES

      Table   Rows  Columns
0     Sales  74920       14
1  Customer   6000       10
2   Product    180        8
3      Date    912        9
4    Region     25        5
5   Returns   4500        9
6   Targets   1500        6

MISSING VALUES BY TABLE

--- Sales ---
No missing values.

--- Customer ---
No missing values.

--- Product ---
No missing values.

--- Date ---
No missing values.

--- Region ---
No missing values.

--- Returns ---
No missing values.

--- Targets ---
No missing values.
DUPLICATE RECORDS
Sales: 0 duplicate rows
Customer: 0 duplicate rows
Product: 0 duplicate rows
Date: 0 duplicate rows
Region: 0 duplicate rows
Returns: 0 duplicate rows
Targets: 0 duplicate rows
PRIMARY KEY VALIDATION
Customer             | Customer_ID     | Duplicates: 0
Product              | Product_ID      | Duplicates: 0
Date                 | Date            | Duplicates: 0
Region               | Region_ID       | Duplicates: 0
Sales                | Order_ID        | Duplicates: 0
Returns              | Return_ID       | Duplicates: 0
Targets              | Target_ID       | Duplicates: 0
FACT SALES → CUSTOMER VALIDATION
Sales records with missing customer: 0
FACT SALES → PRODUCT VALIDATION
Sales records with missing product: 0
FACT SALES → REGION VALIDATION
Sales records with missing region: 0
RETURNS → SALES VALIDATION
Returns without matching sales order: 3
Returns with missing customer: 0
Returns with missing product: 0
TARGETS → REGION VALIDATION
Targets with missing region: 0
DATE COVERAGE
Sales min date: 2024-01-01 00:00:00
Sales max date: 2026-06-30 00:00:00
Date dimension min: 2024-01-01 00:00:00
Date dimension max: 2026-06-30 00:00:00
REGION DISTRIBUTION

  Region_ID  Sales_Record_Count
0      R010                3423
1      R016                3351
2      R012                3176
3      R013                3149
4      R001                3120
5      R018                3106
6      R007                3092
7      R025                3076
8      R019                3065
9      R023                3061

In [13]:
# ORPHAN RETURN INVESTIGATION

print("ORPHAN RETURN INVESTIGATION")

# Identify returns whose Order_ID does not exist in sales
orphan_returns = returns_df[
    ~returns_df["Order_ID"].isin(
        sales_clean["Order_ID"]
    )
].copy()

print(f"\nOrphan returns: {len(orphan_returns)}")

display(orphan_returns)


# Check whether their customers exist

print("CUSTOMER VALIDATION")

orphan_customer_check = orphan_returns[
    [
        "Return_ID",
        "Order_ID",
        "Customer_ID",
        "Product_ID"
    ]
].copy()

orphan_customer_check["Customer_Exists"] = (
    orphan_customer_check["Customer_ID"].isin(
        customers_df["Customer_ID"]
    )
)

display(orphan_customer_check)


# Check whether their products exist

print("PRODUCT VALIDATION")

orphan_product_check = orphan_returns[
    [
        "Return_ID",
        "Order_ID",
        "Customer_ID",
        "Product_ID"
    ]
].copy()

orphan_product_check["Product_Exists"] = (
    orphan_product_check["Product_ID"].isin(
        products_df["Product_ID"]
    )
)

display(orphan_product_check)


# Check return dates

print("RETURN DATE VALIDATION")

orphan_returns["Return_Date"] = pd.to_datetime(
    orphan_returns["Return_Date"],
    errors="coerce"
)

print(
    "Invalid return dates:",
    orphan_returns["Return_Date"].isna().sum()
)

print(
    "Minimum return date:",
    orphan_returns["Return_Date"].min()
)

print(
    "Maximum return date:",
    orphan_returns["Return_Date"].max()
)


# Check whether Order_ID pattern is valid

print("ORDER ID FORMAT")

print(
    orphan_returns["Order_ID"].tolist()
)


# Check whether these orders might exist
# under a different status / condition

print("\n" + "=" * 70)
print("ORPHAN RETURN DETAILS")
print("=" * 70)

display(
    orphan_returns[
        [
            "Return_ID",
            "Order_ID",
            "Customer_ID",
            "Product_ID",
            "Return_Date"
        ]
    ]
)

ORPHAN RETURN INVESTIGATION

Orphan returns: 3

,Return_ID,Order_ID,Return_Date,Customer_ID,Product_ID,Return_Quantity,Return_Reason,Refund_Amount,Return_Status
1525,RET01526,ORD043819,2024-02-13,CUST01904,PROD0028,1,Quality Issue,19962.64,Approved
2988,RET02989,ORD012088,2025-06-06,CUST02470,PROD0049,1,Quality Issue,1295.82,Pending
3581,RET03582,ORD072496,2025-04-15,CUST05481,PROD0120,2,Damaged,13057.24,Approved

CUSTOMER VALIDATION

     Return_ID   Order_ID Customer_ID Product_ID  Customer_Exists
1525  RET01526  ORD043819   CUST01904   PROD0028             True
2988  RET02989  ORD012088   CUST02470   PROD0049             True
3581  RET03582  ORD072496   CUST05481   PROD0120             True

PRODUCT VALIDATION

     Return_ID   Order_ID Customer_ID Product_ID  Product_Exists
1525  RET01526  ORD043819   CUST01904   PROD0028            True
2988  RET02989  ORD012088   CUST02470   PROD0049            True
3581  RET03582  ORD072496   CUST05481   PROD0120            True

RETURN DATE VALIDATION
Invalid return dates: 0
Minimum return date: 2024-02-13 00:00:00
Maximum return date: 2025-06-06 00:00:00
ORDER ID FORMAT
['ORD043819', 'ORD012088', 'ORD072496']

======================================================================
ORPHAN RETURN DETAILS
======================================================================

     Return_ID   Order_ID Customer_ID Product_ID Return_Date
1525  RET01526  ORD043819   CUST01904   PROD0028  2024-02-13
2988  RET02989  ORD012088   CUST02470   PROD0049  2025-06-06
3581  RET03582  ORD072496   CUST05481   PROD0120  2025-04-15

In [14]:
# ============================================================
# TRACE ORPHAN RETURNS BACK TO ORIGINAL SALES DATA
# ============================================================

print("=" * 70)
print("TRACE ORPHAN RETURNS TO ORIGINAL SALES DATA")
print("=" * 70)

# The 3 orphan Order_IDs
orphan_order_ids = orphan_returns["Order_ID"].tolist()

# ------------------------------------------------------------
# 1. Check whether these orders existed in the ORIGINAL sales
# ------------------------------------------------------------

original_order_matches = sales_df[
    sales_df["Order_ID"].isin(orphan_order_ids)
].copy()

print("\nOriginal sales records found:")
print(len(original_order_matches))

display(
    original_order_matches[
        [
            "Order_ID",
            "Order_Date",
            "Customer_ID",
            "Product_ID",
            "Quantity",
            "Unit_Price",
            "Discount_Percent",
            "Sales_Amount",
            "Cost_Amount",
            "Profit",
            "Order_Status"
        ]
    ]
)

# ------------------------------------------------------------
# 2. Compare return information with original sales
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("RETURN ↔ ORIGINAL SALES COMPARISON")
print("=" * 70)

return_sales_comparison = orphan_returns[
    [
        "Return_ID",
        "Order_ID",
        "Return_Date",
        "Customer_ID",
        "Product_ID",
        "Return_Quantity",
        "Refund_Amount",
        "Return_Status"
    ]
].merge(
    original_order_matches[
        [
            "Order_ID",
            "Order_Date",
            "Customer_ID",
            "Product_ID",
            "Quantity",
            "Sales_Amount",
            "Cost_Amount",
            "Profit",
            "Order_Status"
        ]
    ],
    on="Order_ID",
    how="left",
    suffixes=("_Return", "_Sales")
)

display(return_sales_comparison)

# ------------------------------------------------------------
# 3. Check whether customer IDs match
# ------------------------------------------------------------

return_sales_comparison["Customer_Match"] = (
    return_sales_comparison["Customer_ID_Return"]
    ==
    return_sales_comparison["Customer_ID_Sales"]
)

# ------------------------------------------------------------
# 4. Check whether product IDs match
# ------------------------------------------------------------

return_sales_comparison["Product_Match"] = (
    return_sales_comparison["Product_ID_Return"]
    ==
    return_sales_comparison["Product_ID_Sales"]
)

# ------------------------------------------------------------
# 5. Check whether return quantity is valid
# ------------------------------------------------------------

return_sales_comparison["Return_Quantity_Valid"] = (
    return_sales_comparison["Return_Quantity"]
    <=
    return_sales_comparison["Quantity"]
)

# ------------------------------------------------------------
# 6. Show validation results
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("VALIDATION RESULTS")
print("=" * 70)

display(
    return_sales_comparison[
        [
            "Return_ID",
            "Order_ID",
            "Customer_Match",
            "Product_Match",
            "Return_Quantity",
            "Quantity",
            "Return_Quantity_Valid",
            "Order_Status"
        ]
    ]
)

# ------------------------------------------------------------
# 7. Determine whether orders were removed during cleaning
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CLEANING IMPACT CHECK")
print("=" * 70)

for order_id in orphan_order_ids:

    original = sales_df[
        sales_df["Order_ID"] == order_id
    ]

    cleaned = sales_clean[
        sales_clean["Order_ID"] == order_id
    ]

    print(f"\nOrder: {order_id}")
    print(f"Original records: {len(original)}")
    print(f"Cleaned records: {len(cleaned)}")

    if len(original) > 0:
        print(
            "Original Quantity:",
            original["Quantity"].iloc[0]
        )

        print(
            "Original Order Status:",
            original["Order_Status"].iloc[0]
        )

    if len(cleaned) == 0:
        print("STATUS: Order was removed during cleaning.")
    else:
        print("STATUS: Order exists in cleaned sales.")

# ------------------------------------------------------------
# 8. Final classification
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL CLASSIFICATION")
print("=" * 70)

for _, row in return_sales_comparison.iterrows():

    if pd.isna(row["Quantity"]):
        classification = "No original sales record found"

    elif (
        row["Customer_Match"]
        and row["Product_Match"]
        and row["Return_Quantity_Valid"]
    ):
        classification = (
            "Likely valid return; "
            "sales record exists in original data "
            "but was removed during cleaning"
        )

    else:
        classification = (
            "Requires further investigation"
        )

    print(
        f"{row['Return_ID']} | "
        f"{row['Order_ID']} | "
        f"{classification}"
    )

======================================================================
TRACE ORPHAN RETURNS TO ORIGINAL SALES DATA
======================================================================

Original sales records found:
3

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Unit_Price,Discount_Percent,Sales_Amount,Cost_Amount,Profit,Order_Status
12087,ORD012088,2025-05-24,CUST02470,PROD0049,0,1295.82,9.59,5857.75,5202.15,655.60,Completed
43818,ORD043819,2024-02-01,CUST01904,PROD0028,0,19962.64,2.84,38791.40,23669.78,15121.62,Completed
72495,ORD072496,2025-04-04,CUST05481,PROD0120,0,6528.62,8.50,17921.06,12997.41,4923.65,Completed

======================================================================
RETURN ↔ ORIGINAL SALES COMPARISON
======================================================================

,Return_ID,Order_ID,Return_Date,Customer_ID_Return,Product_ID_Return,Return_Quantity,Refund_Amount,Return_Status,Order_Date,Customer_ID_Sales,Product_ID_Sales,Quantity,Sales_Amount,Cost_Amount,Profit,Order_Status
0,RET01526,ORD043819,2024-02-13,CUST01904,PROD0028,1,19962.64,Approved,2024-02-01,CUST01904,PROD0028,0,38791.40,23669.78,15121.62,Completed
1,RET02989,ORD012088,2025-06-06,CUST02470,PROD0049,1,1295.82,Pending,2025-05-24,CUST02470,PROD0049,0,5857.75,5202.15,655.60,Completed
2,RET03582,ORD072496,2025-04-15,CUST05481,PROD0120,2,13057.24,Approved,2025-04-04,CUST05481,PROD0120,0,17921.06,12997.41,4923.65,Completed

======================================================================
VALIDATION RESULTS
======================================================================

,Return_ID,Order_ID,Customer_Match,Product_Match,Return_Quantity,Quantity,Return_Quantity_Valid,Order_Status
0,RET01526,ORD043819,True,True,1,0,False,Completed
1,RET02989,ORD012088,True,True,1,0,False,Completed
2,RET03582,ORD072496,True,True,2,0,False,Completed

======================================================================
CLEANING IMPACT CHECK
======================================================================

Order: ORD043819
Original records: 1
Cleaned records: 0
Original Quantity: 0
Original Order Status: Completed
STATUS: Order was removed during cleaning.

Order: ORD012088
Original records: 1
Cleaned records: 0
Original Quantity: 0
Original Order Status: Completed
STATUS: Order was removed during cleaning.

Order: ORD072496
Original records: 1
Cleaned records: 0
Original Quantity: 0
Original Order Status: Completed
STATUS: Order was removed during cleaning.

======================================================================
FINAL CLASSIFICATION
======================================================================
RET01526 | ORD043819 | Requires further investigation
RET02989 | ORD012088 | Requires further investigation
RET03582 | ORD072496 | Requires further investigation

In [15]:
# ============================================================
# CLEAN AND VALIDATE RETURNS DATA
# ============================================================

returns_clean = returns_df.copy()

# ------------------------------------------------------------
# 1. Standardize data types
# ------------------------------------------------------------

returns_clean["Return_Date"] = pd.to_datetime(
    returns_clean["Return_Date"],
    errors="coerce"
)

returns_clean["Return_Quantity"] = pd.to_numeric(
    returns_clean["Return_Quantity"],
    errors="coerce"
)

returns_clean["Refund_Amount"] = pd.to_numeric(
    returns_clean["Refund_Amount"],
    errors="coerce"
)

# ------------------------------------------------------------
# 2. Identify whether return Order_ID exists in cleaned sales
# ------------------------------------------------------------

returns_clean["Sales_Record_Exists"] = (
    returns_clean["Order_ID"].isin(
        sales_clean["Order_ID"]
    )
)

# ------------------------------------------------------------
# 3. Identify whether return Order_ID existed in original sales
# ------------------------------------------------------------

returns_clean["Original_Sales_Record_Exists"] = (
    returns_clean["Order_ID"].isin(
        sales_df["Order_ID"]
    )
)

# ------------------------------------------------------------
# 4. Bring original sales quantity where available
# ------------------------------------------------------------

original_sales_lookup = (
    sales_df[
        [
            "Order_ID",
            "Customer_ID",
            "Product_ID",
            "Quantity"
        ]
    ]
    .drop_duplicates("Order_ID")
    .rename(
        columns={
            "Customer_ID": "Sales_Customer_ID",
            "Product_ID": "Sales_Product_ID",
            "Quantity": "Sales_Quantity"
        }
    )
)

returns_clean = returns_clean.merge(
    original_sales_lookup,
    on="Order_ID",
    how="left"
)

# ------------------------------------------------------------
# 5. Validate customer and product relationships
# ------------------------------------------------------------

returns_clean["Customer_Match"] = (
    returns_clean["Customer_ID"]
    ==
    returns_clean["Sales_Customer_ID"]
)

returns_clean["Product_Match"] = (
    returns_clean["Product_ID"]
    ==
    returns_clean["Sales_Product_ID"]
)

# ------------------------------------------------------------
# 6. Validate return quantity
# ------------------------------------------------------------

returns_clean["Return_Quantity_Valid"] = (
    returns_clean["Sales_Quantity"].notna()
    &
    (returns_clean["Sales_Quantity"] > 0)
    &
    (returns_clean["Return_Quantity"] <= returns_clean["Sales_Quantity"])
)

# ------------------------------------------------------------
# 7. Create data-quality classification
# ------------------------------------------------------------

def classify_return(row):

    # Valid relationship with cleaned sales
    if row["Sales_Record_Exists"]:
        return "Valid"

    # Original sales existed but was removed during cleaning
    if (
        row["Original_Sales_Record_Exists"]
        and row["Sales_Quantity"] == 0
    ):
        return "Orphan - Invalid Original Sale"

    # No matching sales record at all
    if not row["Original_Sales_Record_Exists"]:
        return "Orphan - No Sales Record"

    return "Requires Investigation"


returns_clean["Data_Quality_Status"] = (
    returns_clean.apply(
        classify_return,
        axis=1
    )
)

# ------------------------------------------------------------
# 8. Create analytical eligibility flag
# ------------------------------------------------------------

returns_clean["Valid_For_Return_Rate"] = (
    returns_clean["Sales_Record_Exists"]
    &
    returns_clean["Customer_Match"]
    &
    returns_clean["Product_Match"]
    &
    returns_clean["Return_Quantity_Valid"]
)

# ------------------------------------------------------------
# 9. Display quality summary
# ------------------------------------------------------------

print("=" * 70)
print("RETURNS DATA QUALITY SUMMARY")
print("=" * 70)

print(
    "\nData quality status:"
)

print(
    returns_clean["Data_Quality_Status"]
    .value_counts()
)

print(
    "\nValid for return-rate analysis:",
    returns_clean["Valid_For_Return_Rate"].sum()
)

print(
    "Not valid for return-rate analysis:",
    (~returns_clean["Valid_For_Return_Rate"]).sum()
)

# ------------------------------------------------------------
# 10. Display flagged records
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FLAGGED RETURN RECORDS")
print("=" * 70)

flagged_returns = returns_clean[
    ~returns_clean["Valid_For_Return_Rate"]
].copy()

display(
    flagged_returns[
        [
            "Return_ID",
            "Order_ID",
            "Customer_ID",
            "Product_ID",
            "Return_Quantity",
            "Sales_Quantity",
            "Refund_Amount",
            "Return_Status",
            "Data_Quality_Status"
        ]
    ]
)

# ------------------------------------------------------------
# 11. Final validation
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL RETURNS VALIDATION")
print("=" * 70)

print(
    "Rows:",
    len(returns_clean)
)

print(
    "Columns:",
    len(returns_clean.columns)
)

print(
    "Duplicate Return_ID:",
    returns_clean["Return_ID"].duplicated().sum()
)

print(
    "Missing Return_ID:",
    returns_clean["Return_ID"].isna().sum()
)

print(
    "Missing Return_Date:",
    returns_clean["Return_Date"].isna().sum()
)

print(
    "Missing Customer_ID:",
    returns_clean["Customer_ID"].isna().sum()
)

print(
    "Missing Product_ID:",
    returns_clean["Product_ID"].isna().sum()
)

print(
    "Negative Return_Quantity:",
    (returns_clean["Return_Quantity"] < 0).sum()
)

print(
    "Negative Refund_Amount:",
    (returns_clean["Refund_Amount"] < 0).sum()
)

======================================================================
RETURNS DATA QUALITY SUMMARY
======================================================================

Data quality status:
Data_Quality_Status
Valid                             4497
Orphan - Invalid Original Sale       3
Name: count, dtype: int64

Valid for return-rate analysis: 4247
Not valid for return-rate analysis: 253

======================================================================
FLAGGED RETURN RECORDS
======================================================================

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Quantity,Sales_Quantity,Refund_Amount,Return_Status,Data_Quality_Status
13,RET00014,ORD071789,CUST00967,PROD0075,2,1,32716.58,Approved,Valid
20,RET00021,ORD030579,CUST02673,PROD0011,2,1,9422.54,Approved,Valid
34,RET00035,ORD020948,CUST01352,PROD0094,2,1,25354.70,Approved,Valid
37,RET00038,ORD069543,CUST01771,PROD0072,2,1,13627.54,Approved,Valid
57,RET00058,ORD019778,CUST04488,PROD0058,2,1,5648.56,Approved,Valid
...,...,...,...,...,...,...,...,...,...
4338,RET04339,ORD069657,CUST00277,PROD0157,2,1,28646.16,Approved,Valid
4347,RET04348,ORD073776,CUST05436,PROD0180,2,1,3980.72,Pending,Valid
4369,RET04370,ORD059412,CUST02896,PROD0079,2,1,11146.66,Rejected,Valid
4375,RET04376,ORD056422,CUST04608,PROD0017,2,1,19973.86,Approved,Valid
4468,RET04469,ORD032589,CUST01178,PROD0059,2,1,8064.46,Rejected,Valid

======================================================================
FINAL RETURNS VALIDATION
======================================================================
Rows: 4500
Columns: 19
Duplicate Return_ID: 0
Missing Return_ID: 0
Missing Return_Date: 0
Missing Customer_ID: 0
Missing Product_ID: 0
Negative Return_Quantity: 0
Negative Refund_Amount: 0

In [16]:
# ============================================================
# CLEAN AND VALIDATE RETURNS DATA
# ============================================================

returns_clean = returns_df.copy()

# ------------------------------------------------------------
# 1. Standardize data types
# ------------------------------------------------------------

returns_clean["Return_Date"] = pd.to_datetime(
    returns_clean["Return_Date"],
    errors="coerce"
)

returns_clean["Return_Quantity"] = pd.to_numeric(
    returns_clean["Return_Quantity"],
    errors="coerce"
)

returns_clean["Refund_Amount"] = pd.to_numeric(
    returns_clean["Refund_Amount"],
    errors="coerce"
)

# ------------------------------------------------------------
# 2. Identify whether return Order_ID exists in cleaned sales
# ------------------------------------------------------------

returns_clean["Sales_Record_Exists"] = (
    returns_clean["Order_ID"].isin(
        sales_clean["Order_ID"]
    )
)

# ------------------------------------------------------------
# 3. Identify whether return Order_ID existed in original sales
# ------------------------------------------------------------

returns_clean["Original_Sales_Record_Exists"] = (
    returns_clean["Order_ID"].isin(
        sales_df["Order_ID"]
    )
)

# ------------------------------------------------------------
# 4. Bring original sales quantity where available
# ------------------------------------------------------------

original_sales_lookup = (
    sales_df[
        [
            "Order_ID",
            "Customer_ID",
            "Product_ID",
            "Quantity"
        ]
    ]
    .drop_duplicates("Order_ID")
    .rename(
        columns={
            "Customer_ID": "Sales_Customer_ID",
            "Product_ID": "Sales_Product_ID",
            "Quantity": "Sales_Quantity"
        }
    )
)

returns_clean = returns_clean.merge(
    original_sales_lookup,
    on="Order_ID",
    how="left"
)

# ------------------------------------------------------------
# 5. Validate customer and product relationships
# ------------------------------------------------------------

returns_clean["Customer_Match"] = (
    returns_clean["Customer_ID"]
    ==
    returns_clean["Sales_Customer_ID"]
)

returns_clean["Product_Match"] = (
    returns_clean["Product_ID"]
    ==
    returns_clean["Sales_Product_ID"]
)

# ------------------------------------------------------------
# 6. Validate return quantity
# ------------------------------------------------------------

returns_clean["Return_Quantity_Valid"] = (
    returns_clean["Sales_Quantity"].notna()
    &
    (returns_clean["Sales_Quantity"] > 0)
    &
    (returns_clean["Return_Quantity"] <= returns_clean["Sales_Quantity"])
)

# ------------------------------------------------------------
# 7. Create data-quality classification
# ------------------------------------------------------------

def classify_return(row):

    # Valid relationship with cleaned sales
    if row["Sales_Record_Exists"]:
        return "Valid"

    # Original sales existed but was removed during cleaning
    if (
        row["Original_Sales_Record_Exists"]
        and row["Sales_Quantity"] == 0
    ):
        return "Orphan - Invalid Original Sale"

    # No matching sales record at all
    if not row["Original_Sales_Record_Exists"]:
        return "Orphan - No Sales Record"

    return "Requires Investigation"


returns_clean["Data_Quality_Status"] = (
    returns_clean.apply(
        classify_return,
        axis=1
    )
)

# ------------------------------------------------------------
# 8. Create analytical eligibility flag
# ------------------------------------------------------------

returns_clean["Valid_For_Return_Rate"] = (
    returns_clean["Sales_Record_Exists"]
    &
    returns_clean["Customer_Match"]
    &
    returns_clean["Product_Match"]
    &
    returns_clean["Return_Quantity_Valid"]
)

# ------------------------------------------------------------
# 9. Display quality summary
# ------------------------------------------------------------

print("=" * 70)
print("RETURNS DATA QUALITY SUMMARY")
print("=" * 70)

print(
    "\nData quality status:"
)

print(
    returns_clean["Data_Quality_Status"]
    .value_counts()
)

print(
    "\nValid for return-rate analysis:",
    returns_clean["Valid_For_Return_Rate"].sum()
)

print(
    "Not valid for return-rate analysis:",
    (~returns_clean["Valid_For_Return_Rate"]).sum()
)

# ------------------------------------------------------------
# 10. Display flagged records
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FLAGGED RETURN RECORDS")
print("=" * 70)

flagged_returns = returns_clean[
    ~returns_clean["Valid_For_Return_Rate"]
].copy()

display(
    flagged_returns[
        [
            "Return_ID",
            "Order_ID",
            "Customer_ID",
            "Product_ID",
            "Return_Quantity",
            "Sales_Quantity",
            "Refund_Amount",
            "Return_Status",
            "Data_Quality_Status"
        ]
    ]
)

# ------------------------------------------------------------
# 11. Final validation
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL RETURNS VALIDATION")
print("=" * 70)

print(
    "Rows:",
    len(returns_clean)
)

print(
    "Columns:",
    len(returns_clean.columns)
)

print(
    "Duplicate Return_ID:",
    returns_clean["Return_ID"].duplicated().sum()
)

print(
    "Missing Return_ID:",
    returns_clean["Return_ID"].isna().sum()
)

print(
    "Missing Return_Date:",
    returns_clean["Return_Date"].isna().sum()
)

print(
    "Missing Customer_ID:",
    returns_clean["Customer_ID"].isna().sum()
)

print(
    "Missing Product_ID:",
    returns_clean["Product_ID"].isna().sum()
)

print(
    "Negative Return_Quantity:",
    (returns_clean["Return_Quantity"] < 0).sum()
)

print(
    "Negative Refund_Amount:",
    (returns_clean["Refund_Amount"] < 0).sum()
)

======================================================================
RETURNS DATA QUALITY SUMMARY
======================================================================

Data quality status:
Data_Quality_Status
Valid                             4497
Orphan - Invalid Original Sale       3
Name: count, dtype: int64

Valid for return-rate analysis: 4247
Not valid for return-rate analysis: 253

======================================================================
FLAGGED RETURN RECORDS
======================================================================

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Quantity,Sales_Quantity,Refund_Amount,Return_Status,Data_Quality_Status
13,RET00014,ORD071789,CUST00967,PROD0075,2,1,32716.58,Approved,Valid
20,RET00021,ORD030579,CUST02673,PROD0011,2,1,9422.54,Approved,Valid
34,RET00035,ORD020948,CUST01352,PROD0094,2,1,25354.70,Approved,Valid
37,RET00038,ORD069543,CUST01771,PROD0072,2,1,13627.54,Approved,Valid
57,RET00058,ORD019778,CUST04488,PROD0058,2,1,5648.56,Approved,Valid
...,...,...,...,...,...,...,...,...,...
4338,RET04339,ORD069657,CUST00277,PROD0157,2,1,28646.16,Approved,Valid
4347,RET04348,ORD073776,CUST05436,PROD0180,2,1,3980.72,Pending,Valid
4369,RET04370,ORD059412,CUST02896,PROD0079,2,1,11146.66,Rejected,Valid
4375,RET04376,ORD056422,CUST04608,PROD0017,2,1,19973.86,Approved,Valid
4468,RET04469,ORD032589,CUST01178,PROD0059,2,1,8064.46,Rejected,Valid

======================================================================
FINAL RETURNS VALIDATION
======================================================================
Rows: 4500
Columns: 19
Duplicate Return_ID: 0
Missing Return_ID: 0
Missing Return_Date: 0
Missing Customer_ID: 0
Missing Product_ID: 0
Negative Return_Quantity: 0
Negative Refund_Amount: 0

In [17]:
# ============================================================
# CUMULATIVE RETURN QUANTITY INVESTIGATION
# ============================================================

# 1. Returns linked to an original sales record
returns_with_sales = returns_clean[
    returns_clean["Original_Sales_Record_Exists"]
].copy()

# 2. Aggregate returns by Order + Product
return_summary = (
    returns_with_sales
    .groupby(
        ["Order_ID", "Product_ID"],
        as_index=False
    )
    .agg(
        Return_Record_Count=("Return_ID", "count"),
        Total_Return_Quantity=("Return_Quantity", "sum"),
        Total_Refund_Amount=("Refund_Amount", "sum")
    )
)

# 3. Get original sales quantity
sales_quantity_lookup = (
    sales_df[
        ["Order_ID", "Product_ID", "Quantity"]
    ]
    .drop_duplicates(
        ["Order_ID", "Product_ID"]
    )
    .rename(
        columns={"Quantity": "Original_Sales_Quantity"}
    )
)

return_summary = return_summary.merge(
    sales_quantity_lookup,
    on=["Order_ID", "Product_ID"],
    how="left"
)

# 4. Validate cumulative return quantity
return_summary["Cumulative_Return_Exceeds_Sales"] = (
    return_summary["Total_Return_Quantity"]
    >
    return_summary["Original_Sales_Quantity"]
)

return_summary["Multiple_Return_Records"] = (
    return_summary["Return_Record_Count"] > 1
)

# ============================================================
# SUMMARY
# ============================================================

print("=" * 70)
print("CUMULATIVE RETURN ANALYSIS")
print("=" * 70)

print(
    "\nUnique Order + Product combinations:",
    len(return_summary)
)

print(
    "Multiple return combinations:",
    return_summary["Multiple_Return_Records"].sum()
)

print(
    "Cumulative returns exceeding sales quantity:",
    return_summary["Cumulative_Return_Exceeds_Sales"].sum()
)

# ============================================================
# SHOW ALL ANOMALOUS ORDER + PRODUCT COMBINATIONS
# ============================================================

anomalies = return_summary[
    return_summary["Cumulative_Return_Exceeds_Sales"]
].copy()

print("\n" + "=" * 70)
print("CUMULATIVE RETURN QUANTITY ANOMALIES")
print("=" * 70)

print(
    "\nNumber of anomalous combinations:",
    len(anomalies)
)

display(
    anomalies[
        [
            "Order_ID",
            "Product_ID",
            "Return_Record_Count",
            "Total_Return_Quantity",
            "Original_Sales_Quantity",
            "Total_Refund_Amount"
        ]
    ]
    .sort_values(
        "Total_Return_Quantity",
        ascending=False
    )
)

# ============================================================
# INVESTIGATE THE 253 RECORDS
# ============================================================

previously_flagged = returns_clean[
    ~returns_clean["Valid_For_Return_Rate"]
].copy()

flagged_analysis = previously_flagged.merge(
    return_summary[
        [
            "Order_ID",
            "Product_ID",
            "Return_Record_Count",
            "Total_Return_Quantity",
            "Original_Sales_Quantity",
            "Cumulative_Return_Exceeds_Sales",
            "Multiple_Return_Records"
        ]
    ],
    on=["Order_ID", "Product_ID"],
    how="left"
)

print("\n" + "=" * 70)
print("253 PREVIOUSLY FLAGGED RETURNS")
print("=" * 70)

print(
    "Previously flagged records:",
    len(previously_flagged)
)

print(
    "Flagged records belonging to cumulative anomalies:",
    flagged_analysis[
        "Cumulative_Return_Exceeds_Sales"
    ].sum()
)

print(
    "Flagged records belonging to multiple-return combinations:",
    flagged_analysis[
        "Multiple_Return_Records"
    ].sum()
)

display(
    flagged_analysis[
        [
            "Return_ID",
            "Order_ID",
            "Product_ID",
            "Return_Quantity",
            "Sales_Quantity",
            "Return_Record_Count",
            "Total_Return_Quantity",
            "Original_Sales_Quantity",
            "Multiple_Return_Records",
            "Cumulative_Return_Exceeds_Sales",
            "Data_Quality_Status"
        ]
    ]
    .head(50)
)

======================================================================
CUMULATIVE RETURN ANALYSIS
======================================================================

Unique Order + Product combinations: 4500
Multiple return combinations: 0
Cumulative returns exceeding sales quantity: 253

======================================================================
CUMULATIVE RETURN QUANTITY ANOMALIES
======================================================================

Number of anomalous combinations: 253

,Order_ID,Product_ID,Return_Record_Count,Total_Return_Quantity,Original_Sales_Quantity,Total_Refund_Amount
16,ORD000250,PROD0010,1,2,1,23544.02
20,ORD000368,PROD0132,1,2,1,7803.10
38,ORD000674,PROD0023,1,2,1,24189.08
48,ORD000830,PROD0053,1,2,1,4170.74
64,ORD001097,PROD0111,1,2,1,9178.00
...,...,...,...,...,...,...
4421,ORD073859,PROD0085,1,2,1,14749.82
4475,ORD074675,PROD0067,1,2,1,8457.74
4467,ORD074624,PROD0123,1,2,1,20551.36
742,ORD012088,PROD0049,1,1,0,1295.82
2646,ORD043819,PROD0028,1,1,0,19962.64

======================================================================
253 PREVIOUSLY FLAGGED RETURNS
======================================================================
Previously flagged records: 253
Flagged records belonging to cumulative anomalies: 253
Flagged records belonging to multiple-return combinations: 0

,Return_ID,Order_ID,Product_ID,Return_Quantity,Sales_Quantity,Return_Record_Count,Total_Return_Quantity,Original_Sales_Quantity,Multiple_Return_Records,Cumulative_Return_Exceeds_Sales,Data_Quality_Status
0,RET00014,ORD071789,PROD0075,2,1,1,2,1,False,True,Valid
1,RET00021,ORD030579,PROD0011,2,1,1,2,1,False,True,Valid
2,RET00035,ORD020948,PROD0094,2,1,1,2,1,False,True,Valid
3,RET00038,ORD069543,PROD0072,2,1,1,2,1,False,True,Valid
4,RET00058,ORD019778,PROD0058,2,1,1,2,1,False,True,Valid
5,RET00083,ORD056657,PROD0083,2,1,1,2,1,False,True,Valid
6,RET00118,ORD015807,PROD0169,2,1,1,2,1,False,True,Valid
7,RET00146,ORD001204,PROD0007,2,1,1,2,1,False,True,Valid
8,RET00147,ORD005760,PROD0140,2,1,1,2,1,False,True,Valid
9,RET00188,ORD020208,PROD0045,2,1,1,2,1,False,True,Valid
10,RET00234,ORD011186,PROD0137,2,1,1,2,1,False,True,Valid
11,RET00240,ORD060929,PROD0116,2,1,1,2,1,False,True,Valid
12,RET00249,ORD021764,PROD0080,2,1,1,2,1,False,True,Valid
13,RET00264,ORD034903,PROD0083,2,1,1,2,1,False,True,Valid
14,RET00285,ORD006746,PROD0065,2,1,1,2,1,False,True,Valid
15,RET00315,ORD017197,PROD0096,2,1,1,2,1,False,True,Valid
16,RET00333,ORD052485,PROD0039,2,1,1,2,1,False,True,Valid
17,RET00354,ORD006097,PROD0169,2,1,1,2,1,False,True,Valid
18,RET00384,ORD025969,PROD0076,2,1,1,2,1,False,True,Valid
19,RET00388,ORD034495,PROD0043,2,1,1,2,1,False,True,Valid
20,RET00401,ORD057992,PROD0058,2,1,1,2,1,False,True,Valid
21,RET00402,ORD010693,PROD0083,2,1,1,2,1,False,True,Valid
22,RET00415,ORD016706,PROD0171,2,1,1,2,1,False,True,Valid
23,RET00419,ORD039634,PROD0166,2,1,1,2,1,False,True,Valid
24,RET00450,ORD034639,PROD0088,2,1,1,2,1,False,True,Valid
25,RET00461,ORD025367,PROD0152,2,1,1,2,1,False,True,Valid
26,RET00465,ORD057038,PROD0071,2,1,1,2,1,False,True,Valid
27,RET00487,ORD058211,PROD0175,2,1,1,2,1,False,True,Valid
28,RET00500,ORD059600,PROD0133,2,1,1,2,1,False,True,Valid
29,RET00564,ORD072026,PROD0014,2,1,1,2,1,False,True,Valid
30,RET00595,ORD016190,PROD0038,2,1,1,2,1,False,True,Valid
31,RET00646,ORD060619,PROD0036,2,1,1,2,1,False,True,Valid
32,RET00656,ORD061391,PROD0083,2,1,1,2,1,False,True,Valid
33,RET00660,ORD022386,PROD0122,2,1,1,2,1,False,True,Valid
34,RET00678,ORD062183,PROD0099,2,1,1,2,1,False,True,Valid
35,RET00692,ORD065285,PROD0102,2,1,1,2,1,False,True,Valid
36,RET00702,ORD040448,PROD0087,2,1,1,2,1,False,True,Valid
37,RET00705,ORD049034,PROD0126,2,1,1,2,1,False,True,Valid
38,RET00724,ORD046833,PROD0096,2,1,1,2,1,False,True,Valid
39,RET00750,ORD070989,PROD0015,2,1,1,2,1,False,True,Valid
40,RET00752,ORD047764,PROD0034,2,1,1,2,1,False,True,Valid
41,RET00782,ORD052164,PROD0159,2,1,1,2,1,False,True,Valid
42,RET00805,ORD021548,PROD0009,2,1,1,2,1,False,True,Valid
43,RET00816,ORD040659,PROD0095,2,1,1,2,1,False,True,Valid
44,RET00836,ORD072536,PROD0007,2,1,1,2,1,False,True,Valid
45,RET00844,ORD059852,PROD0115,2,1,1,2,1,False,True,Valid
46,RET00862,ORD043535,PROD0082,2,1,1,2,1,False,True,Valid
47,RET00889,ORD039007,PROD0110,2,1,1,2,1,False,True,Valid
48,RET00902,ORD001427,PROD0125,2,1,1,2,1,False,True,Valid
49,RET00919,ORD023698,PROD0114,2,1,1,2,1,False,True,Valid

In [18]:
# ============================================================
# FINALIZE RETURNS DATA QUALITY FLAGS
# ============================================================

print("=" * 70)
print("FINALIZING RETURNS DATA QUALITY FLAGS")
print("=" * 70)

# ------------------------------------------------------------
# 1. Quantity anomaly
# ------------------------------------------------------------

returns_clean["Quantity_Anomaly"] = (
    returns_clean["Original_Sales_Record_Exists"]
    &
    returns_clean["Sales_Quantity"].notna()
    &
    (returns_clean["Sales_Quantity"] > 0)
    &
    (
        returns_clean["Return_Quantity"]
        >
        returns_clean["Sales_Quantity"]
    )
)

# ------------------------------------------------------------
# 2. Orphan return
# ------------------------------------------------------------

returns_clean["Orphan_Return"] = (
    ~returns_clean["Sales_Record_Exists"]
)

# ------------------------------------------------------------
# 3. Basic return record validity
# ------------------------------------------------------------

returns_clean["Return_Record_Valid"] = (
    returns_clean["Return_ID"].notna()
    &
    returns_clean["Order_ID"].notna()
    &
    returns_clean["Return_Date"].notna()
    &
    returns_clean["Customer_ID"].notna()
    &
    returns_clean["Product_ID"].notna()
    &
    returns_clean["Return_Quantity"].notna()
    &
    (returns_clean["Return_Quantity"] > 0)
    &
    returns_clean["Refund_Amount"].notna()
    &
    (returns_clean["Refund_Amount"] >= 0)
)

# ------------------------------------------------------------
# 4. Valid return for quantity-based analysis
# ------------------------------------------------------------

returns_clean["Valid_For_Return_Rate"] = (
    returns_clean["Return_Record_Valid"]
    &
    returns_clean["Sales_Record_Exists"]
    &
    returns_clean["Customer_Match"]
    &
    returns_clean["Product_Match"]
    &
    ~returns_clean["Quantity_Anomaly"]
)

# ------------------------------------------------------------
# 5. Final data quality status
# ------------------------------------------------------------

def final_return_status(row):

    if not row["Return_Record_Valid"]:
        return "Invalid Return Record"

    if row["Orphan_Return"]:
        return "Orphan Return"

    if row["Quantity_Anomaly"]:
        return "Quantity Anomaly"

    return "Valid"


returns_clean["Final_Data_Quality_Status"] = (
    returns_clean.apply(
        final_return_status,
        axis=1
    )
)

# ------------------------------------------------------------
# 6. Summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL RETURN QUALITY SUMMARY")
print("=" * 70)

display(
    returns_clean["Final_Data_Quality_Status"]
    .value_counts()
    .rename_axis("Data_Quality_Status")
    .reset_index(name="Records")
)

print(
    "\nTotal return records:",
    len(returns_clean)
)

print(
    "Valid return records:",
    (
        returns_clean["Final_Data_Quality_Status"]
        == "Valid"
    ).sum()
)

print(
    "Quantity anomalies:",
    returns_clean["Quantity_Anomaly"].sum()
)

print(
    "Orphan returns:",
    returns_clean["Orphan_Return"].sum()
)

print(
    "Valid for return-rate analysis:",
    returns_clean["Valid_For_Return_Rate"].sum()
)

# ------------------------------------------------------------
# 7. Validate that categories add up correctly
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CONSISTENCY CHECK")
print("=" * 70)

category_total = (
    returns_clean["Final_Data_Quality_Status"]
    .value_counts()
    .sum()
)

print(
    "Category total:",
    category_total
)

print(
    "Actual total:",
    len(returns_clean)
)

print(
    "Counts match:",
    category_total == len(returns_clean)
)

# ------------------------------------------------------------
# 8. Show anomaly examples
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("QUANTITY ANOMALY EXAMPLES")
print("=" * 70)

display(
    returns_clean[
        returns_clean["Quantity_Anomaly"]
    ][
        [
            "Return_ID",
            "Order_ID",
            "Product_ID",
            "Return_Quantity",
            "Sales_Quantity",
            "Refund_Amount",
            "Return_Status",
            "Final_Data_Quality_Status"
        ]
    ]
    .head(20)
)

# ------------------------------------------------------------
# 9. Show orphan returns
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("ORPHAN RETURNS")
print("=" * 70)

display(
    returns_clean[
        returns_clean["Orphan_Return"]
    ][
        [
            "Return_ID",
            "Order_ID",
            "Customer_ID",
            "Product_ID",
            "Return_Quantity",
            "Sales_Quantity",
            "Refund_Amount",
            "Return_Status",
            "Final_Data_Quality_Status"
        ]
    ]
)

# ------------------------------------------------------------
# 10. Final validation checks
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL VALIDATION CHECKS")
print("=" * 70)

print(
    "Duplicate Return_ID:",
    returns_clean["Return_ID"].duplicated().sum()
)

print(
    "Missing Return_ID:",
    returns_clean["Return_ID"].isna().sum()
)

print(
    "Missing Return_Date:",
    returns_clean["Return_Date"].isna().sum()
)

print(
    "Missing Customer_ID:",
    returns_clean["Customer_ID"].isna().sum()
)

print(
    "Missing Product_ID:",
    returns_clean["Product_ID"].isna().sum()
)

print(
    "Invalid Return Quantity:",
    (
        returns_clean["Return_Quantity"] <= 0
    ).sum()
)

print(
    "Negative Refund Amount:",
    (
        returns_clean["Refund_Amount"] < 0
    ).sum()
)

======================================================================
FINALIZING RETURNS DATA QUALITY FLAGS
======================================================================

======================================================================
FINAL RETURN QUALITY SUMMARY
======================================================================

  Data_Quality_Status  Records
0               Valid     4247
1    Quantity Anomaly      250
2       Orphan Return        3

Total return records: 4500
Valid return records: 4247
Quantity anomalies: 250
Orphan returns: 3
Valid for return-rate analysis: 4247

======================================================================
CONSISTENCY CHECK
======================================================================
Category total: 4500
Actual total: 4500
Counts match: True

======================================================================
QUANTITY ANOMALY EXAMPLES
======================================================================

,Return_ID,Order_ID,Product_ID,Return_Quantity,Sales_Quantity,Refund_Amount,Return_Status,Final_Data_Quality_Status
13,RET00014,ORD071789,PROD0075,2,1,32716.58,Approved,Quantity Anomaly
20,RET00021,ORD030579,PROD0011,2,1,9422.54,Approved,Quantity Anomaly
34,RET00035,ORD020948,PROD0094,2,1,25354.70,Approved,Quantity Anomaly
37,RET00038,ORD069543,PROD0072,2,1,13627.54,Approved,Quantity Anomaly
57,RET00058,ORD019778,PROD0058,2,1,5648.56,Approved,Quantity Anomaly
82,RET00083,ORD056657,PROD0083,2,1,27269.86,Approved,Quantity Anomaly
117,RET00118,ORD015807,PROD0169,2,1,12709.76,Approved,Quantity Anomaly
145,RET00146,ORD001204,PROD0007,2,1,13240.46,Approved,Quantity Anomaly
146,RET00147,ORD005760,PROD0140,2,1,32116.74,Approved,Quantity Anomaly
187,RET00188,ORD020208,PROD0045,2,1,5768.48,Approved,Quantity Anomaly
233,RET00234,ORD011186,PROD0137,2,1,4271.64,Approved,Quantity Anomaly
239,RET00240,ORD060929,PROD0116,2,1,3625.08,Approved,Quantity Anomaly
248,RET00249,ORD021764,PROD0080,2,1,14213.30,Approved,Quantity Anomaly
263,RET00264,ORD034903,PROD0083,2,1,27269.86,Approved,Quantity Anomaly
284,RET00285,ORD006746,PROD0065,2,1,8732.24,Approved,Quantity Anomaly
314,RET00315,ORD017197,PROD0096,2,1,5016.42,Approved,Quantity Anomaly
332,RET00333,ORD052485,PROD0039,2,1,1519.90,Approved,Quantity Anomaly
353,RET00354,ORD006097,PROD0169,2,1,12709.76,Approved,Quantity Anomaly
383,RET00384,ORD025969,PROD0076,2,1,14895.84,Approved,Quantity Anomaly
387,RET00388,ORD034495,PROD0043,2,1,36152.34,Approved,Quantity Anomaly

======================================================================
ORPHAN RETURNS
======================================================================

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Quantity,Sales_Quantity,Refund_Amount,Return_Status,Final_Data_Quality_Status
1525,RET01526,ORD043819,CUST01904,PROD0028,1,0,19962.64,Approved,Orphan Return
2988,RET02989,ORD012088,CUST02470,PROD0049,1,0,1295.82,Pending,Orphan Return
3581,RET03582,ORD072496,CUST05481,PROD0120,2,0,13057.24,Approved,Orphan Return

======================================================================
FINAL VALIDATION CHECKS
======================================================================
Duplicate Return_ID: 0
Missing Return_ID: 0
Missing Return_Date: 0
Missing Customer_ID: 0
Missing Product_ID: 0
Invalid Return Quantity: 0
Negative Refund Amount: 0

In [25]:
# ============================================================
# LOAD ALL TABLES FOR FINAL ANALYTICAL MODEL
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

print("=" * 70)
print("LOADING FINAL ANALYTICAL TABLES")
print("=" * 70)

# ------------------------------------------------------------
# 1. DEFINE PROJECT PATHS
# ------------------------------------------------------------

project_path = Path("C:/Users/shubh/Desktop/AI_Sales_Intelligence")

raw_path = project_path / "data" / "raw"
cleaned_path = project_path / "data" / "cleaned"

# ------------------------------------------------------------
# 2. LOAD CLEAN SALES
# ------------------------------------------------------------

sales = pd.read_csv(
    cleaned_path / "sales_clean.csv"
)

sales["Order_Date"] = pd.to_datetime(
    sales["Order_Date"],
    errors="coerce"
)

# ------------------------------------------------------------
# 3. LOAD RETURNS
# ------------------------------------------------------------

# Use the returns_clean dataframe if it already exists.
# Otherwise load the raw returns file.

if "returns_clean" in globals():
    return_data = returns_clean.copy()
else:
    return_data = pd.read_csv(
        raw_path / "returns.csv"
    )

return_data["Return_Date"] = pd.to_datetime(
    return_data["Return_Date"],
    errors="coerce"
)

# ------------------------------------------------------------
# 4. LOAD DIMENSION / TARGET TABLES
# ------------------------------------------------------------

customer = pd.read_csv(
    raw_path / "customer.csv"
)

product = pd.read_csv(
    raw_path / "product.csv"
)

date = pd.read_csv(
    raw_path / "date.csv"
)

region = pd.read_csv(
    raw_path / "region.csv"
)

target = pd.read_csv(
    raw_path / "targets.csv"
)

date["Date"] = pd.to_datetime(
    date["Date"],
    errors="coerce"
)

# ------------------------------------------------------------
# 5. DISPLAY TABLE SIZES
# ------------------------------------------------------------

print("\nTable sizes:")
print("-" * 70)

tables = {
    "sales": sales,
    "return": return_data,
    "customer": customer,
    "product": product,
    "date": date,
    "region": region,
    "target": target
}

for name, df in tables.items():
    print(f"{name:12} → {df.shape}")

# ------------------------------------------------------------
# 6. CHECK THAT ALL TABLES LOADED
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TABLE LOADING CHECK")
print("=" * 70)

for name, df in tables.items():
    print(
        f"{name:12} → "
        f"Rows: {len(df):,} | "
        f"Columns: {len(df.columns)}"
    )

print("\nAll tables loaded successfully.")

======================================================================
LOADING FINAL ANALYTICAL TABLES
======================================================================

Table sizes:
----------------------------------------------------------------------
sales        → (74920, 14)
return       → (4500, 23)
customer     → (6000, 10)
product      → (180, 8)
date         → (912, 9)
region       → (25, 5)
target       → (1500, 6)

======================================================================
TABLE LOADING CHECK
======================================================================
sales        → Rows: 74,920 | Columns: 14
return       → Rows: 4,500 | Columns: 23
customer     → Rows: 6,000 | Columns: 10
product      → Rows: 180 | Columns: 8
date         → Rows: 912 | Columns: 9
region       → Rows: 25 | Columns: 5
target       → Rows: 1,500 | Columns: 6

All tables loaded successfully.

In [26]:
# ============================================================
# FINAL ANALYTICAL MODEL + RELATIONSHIP VALIDATION
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("FINAL ANALYTICAL MODEL")
print("=" * 70)


# ============================================================
# 1. CREATE WORKING COPIES
# ============================================================

sales_model = sales.copy()
return_model = return_data.copy()
customer_model = customer.copy()
product_model = product.copy()
date_model = date.copy()
region_model = region.copy()
target_model = target.copy()


# ============================================================
# 2. STANDARDIZE IMPORTANT DATA TYPES
# ============================================================

sales_model["Order_Date"] = pd.to_datetime(
    sales_model["Order_Date"],
    errors="coerce"
)

return_model["Return_Date"] = pd.to_datetime(
    return_model["Return_Date"],
    errors="coerce"
)

date_model["Date"] = pd.to_datetime(
    date_model["Date"],
    errors="coerce"
)

# Numeric sales columns
sales_numeric = [
    "Quantity",
    "Unit_Price",
    "Discount_Percent",
    "Sales_Amount",
    "Cost_Amount",
    "Profit"
]

for col in sales_numeric:
    sales_model[col] = pd.to_numeric(
        sales_model[col],
        errors="coerce"
    )

return_model["Return_Quantity"] = pd.to_numeric(
    return_model["Return_Quantity"],
    errors="coerce"
)

return_model["Refund_Amount"] = pd.to_numeric(
    return_model["Refund_Amount"],
    errors="coerce"
)


# ============================================================
# 3. SALES BUSINESS METRICS
# ============================================================

# Gross sales before discount
sales_model["Gross_Sales"] = (
    sales_model["Quantity"]
    * sales_model["Unit_Price"]
)

# Discount value
sales_model["Discount_Amount"] = (
    sales_model["Gross_Sales"]
    * sales_model["Discount_Percent"]
    / 100
)

# Profit margin
sales_model["Profit_Margin_Percent"] = np.where(
    sales_model["Sales_Amount"] != 0,
    sales_model["Profit"]
    / sales_model["Sales_Amount"]
    * 100,
    np.nan
)

# Selling price per unit
sales_model["Selling_Price_Per_Unit"] = np.where(
    sales_model["Quantity"] != 0,
    sales_model["Sales_Amount"]
    / sales_model["Quantity"],
    np.nan
)

# Cost per unit
sales_model["Cost_Per_Unit"] = np.where(
    sales_model["Quantity"] != 0,
    sales_model["Cost_Amount"]
    / sales_model["Quantity"],
    np.nan
)

# Date attributes
sales_model["Year"] = sales_model["Order_Date"].dt.year
sales_model["Month"] = sales_model["Order_Date"].dt.month
sales_model["Month_Name"] = sales_model["Order_Date"].dt.month_name()
sales_model["Quarter"] = (
    "Q" + sales_model["Order_Date"].dt.quarter.astype("string")
)


# ============================================================
# 4. RETURN BUSINESS METRICS
# ============================================================

return_model["Year"] = return_model["Return_Date"].dt.year
return_model["Month"] = return_model["Return_Date"].dt.month
return_model["Month_Name"] = return_model["Return_Date"].dt.month_name()
return_model["Quarter"] = (
    "Q" + return_model["Return_Date"].dt.quarter.astype("string")
)

# Valid return flag
return_model["Is_Valid_Return"] = (
    return_model["Final_Data_Quality_Status"] == "Valid"
)

# Quantity eligible for return-rate calculation
return_model["Analytical_Return_Quantity"] = np.where(
    return_model["Is_Valid_Return"],
    return_model["Return_Quantity"],
    0
)

# Refund amount from valid return records
return_model["Analytical_Refund_Amount"] = np.where(
    return_model["Is_Valid_Return"],
    return_model["Refund_Amount"],
    0
)


# ============================================================
# 5. RELATIONSHIP VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("RELATIONSHIP VALIDATION")
print("=" * 70)

checks = {}

# Sales relationships
checks["Sales → Customer"] = (
    sales_model["Customer_ID"]
    .isin(customer_model["Customer_ID"])
    .all()
)

checks["Sales → Product"] = (
    sales_model["Product_ID"]
    .isin(product_model["Product_ID"])
    .all()
)

checks["Sales → Region"] = (
    sales_model["Region_ID"]
    .isin(region_model["Region_ID"])
    .all()
)

# Returns relationships
checks["Return → Customer"] = (
    return_model["Customer_ID"]
    .isin(customer_model["Customer_ID"])
    .all()
)

checks["Return → Product"] = (
    return_model["Product_ID"]
    .isin(product_model["Product_ID"])
    .all()
)

# Target relationship
checks["Target → Region"] = (
    target_model["Region_ID"]
    .isin(region_model["Region_ID"])
    .all()
)

# Date relationships
checks["Sales → Date"] = (
    sales_model["Order_Date"]
    .dt.normalize()
    .isin(date_model["Date"])
    .all()
)

checks["Return → Date"] = (
    return_model["Return_Date"]
    .dt.normalize()
    .isin(date_model["Date"])
    .all()
)

for relationship, result in checks.items():
    print(
        f"{relationship:25} : "
        f"{'PASS' if result else 'FAIL'}"
    )


# ============================================================
# 6. SHOW FAILED RELATIONSHIPS IF ANY
# ============================================================

print("\n" + "=" * 70)
print("FAILED RELATIONSHIP DETAILS")
print("=" * 70)

# Sales → Customer
missing = sales_model[
    ~sales_model["Customer_ID"].isin(
        customer_model["Customer_ID"]
    )
]

print(
    f"Sales → Customer missing: {len(missing):,}"
)

# Sales → Product
missing = sales_model[
    ~sales_model["Product_ID"].isin(
        product_model["Product_ID"]
    )
]

print(
    f"Sales → Product missing : {len(missing):,}"
)

# Sales → Region
missing = sales_model[
    ~sales_model["Region_ID"].isin(
        region_model["Region_ID"]
    )
]

print(
    f"Sales → Region missing  : {len(missing):,}"
)

# Return → Customer
missing = return_model[
    ~return_model["Customer_ID"].isin(
        customer_model["Customer_ID"]
    )
]

print(
    f"Return → Customer missing: {len(missing):,}"
)

# Return → Product
missing = return_model[
    ~return_model["Product_ID"].isin(
        product_model["Product_ID"]
    )
]

print(
    f"Return → Product missing : {len(missing):,}"
)

# Target → Region
missing = target_model[
    ~target_model["Region_ID"].isin(
        region_model["Region_ID"]
    )
]

print(
    f"Target → Region missing  : {len(missing):,}"
)


# ============================================================
# 7. PRIMARY KEY VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("PRIMARY KEY VALIDATION")
print("=" * 70)

primary_keys = {
    "Sales Order_ID": (sales_model, "Order_ID"),
    "Return Return_ID": (return_model, "Return_ID"),
    "Customer Customer_ID": (customer_model, "Customer_ID"),
    "Product Product_ID": (product_model, "Product_ID"),
    "Date Date": (date_model, "Date"),
    "Region Region_ID": (region_model, "Region_ID"),
    "Target Target_ID": (target_model, "Target_ID")
}

for name, (df, key) in primary_keys.items():

    duplicates = df[key].duplicated().sum()
    missing = df[key].isna().sum()

    print(
        f"{name:25} | "
        f"Duplicates: {duplicates:,} | "
        f"Missing: {missing:,}"
    )


# ============================================================
# 8. FACT TABLE QUALITY SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("FACT TABLE SUMMARY")
print("=" * 70)

print(f"\nSales records       : {len(sales_model):,}")
print(f"Return records      : {len(return_model):,}")
print(f"Target records      : {len(target_model):,}")

print(
    f"Valid returns       : "
    f"{return_model['Is_Valid_Return'].sum():,}"
)

print(
    f"Quantity anomalies  : "
    f"{(
        return_model['Final_Data_Quality_Status']
        == 'Quantity Anomaly'
    ).sum():,}"
)

print(
    f"Orphan returns      : "
    f"{(
        return_model['Final_Data_Quality_Status']
        == 'Orphan Return'
    ).sum():,}"
)


# ============================================================
# 9. FINAL ANALYTICAL MODEL SUMMARY
# ============================================================

model_summary = pd.DataFrame({
    "Table": [
        "sales",
        "return",
        "target",
        "customer",
        "product",
        "date",
        "region"
    ],
    "Rows": [
        len(sales_model),
        len(return_model),
        len(target_model),
        len(customer_model),
        len(product_model),
        len(date_model),
        len(region_model)
    ],
    "Role": [
        "Sales transactions",
        "Return transactions",
        "Regional targets",
        "Customer attributes",
        "Product attributes",
        "Calendar attributes",
        "Regional attributes"
    ]
})

print("\n" + "=" * 70)
print("ANALYTICAL MODEL SUMMARY")
print("=" * 70)

display(model_summary)


# ============================================================
# 10. SAVE ANALYTICAL MODEL
# ============================================================

from pathlib import Path

output_dir = Path(
    "C:/Users/shubh/Desktop/AI_Sales_Intelligence/data/cleaned"
)

output_dir.mkdir(
    parents=True,
    exist_ok=True
)

sales_model.to_csv(
    output_dir / "sales_model.csv",
    index=False
)

return_model.to_csv(
    output_dir / "return_model.csv",
    index=False
)

customer_model.to_csv(
    output_dir / "customer_model.csv",
    index=False
)

product_model.to_csv(
    output_dir / "product_model.csv",
    index=False
)

date_model.to_csv(
    output_dir / "date_model.csv",
    index=False
)

region_model.to_csv(
    output_dir / "region_model.csv",
    index=False
)

target_model.to_csv(
    output_dir / "target_model.csv",
    index=False
)

model_summary.to_csv(
    output_dir / "analytical_model_summary.csv",
    index=False
)


# ============================================================
# COMPLETE
# ============================================================

print("\n" + "=" * 70)
print("ANALYTICAL MODEL CREATED SUCCESSFULLY")
print("=" * 70)

print(f"\nSaved to:")
print(output_dir)

print("\nFiles:")
print("✓ sales_model.csv")
print("✓ return_model.csv")
print("✓ customer_model.csv")
print("✓ product_model.csv")
print("✓ date_model.csv")
print("✓ region_model.csv")
print("✓ target_model.csv")
print("✓ analytical_model_summary.csv")

======================================================================
FINAL ANALYTICAL MODEL
======================================================================

======================================================================
RELATIONSHIP VALIDATION
======================================================================
Sales → Customer          : PASS
Sales → Product           : PASS
Sales → Region            : PASS
Return → Customer         : PASS
Return → Product          : PASS
Target → Region           : PASS
Sales → Date              : PASS
Return → Date             : FAIL

======================================================================
FAILED RELATIONSHIP DETAILS
======================================================================
Sales → Customer missing: 0
Sales → Product missing : 0
Sales → Region missing  : 0
Return → Customer missing: 0
Return → Product missing : 0
Target → Region missing  : 0

======================================================================
PRIMARY KEY VALIDATION
======================================================================
Sales Order_ID            | Duplicates: 0 | Missing: 0
Return Return_ID          | Duplicates: 0 | Missing: 0
Customer Customer_ID      | Duplicates: 0 | Missing: 0
Product Product_ID        | Duplicates: 0 | Missing: 0
Date Date                 | Duplicates: 0 | Missing: 0
Region Region_ID          | Duplicates: 0 | Missing: 0
Target Target_ID          | Duplicates: 0 | Missing: 0

======================================================================
FACT TABLE SUMMARY
======================================================================

Sales records       : 74,920
Return records      : 4,500
Target records      : 1,500
Valid returns       : 4,247
Quantity anomalies  : 250
Orphan returns      : 3

======================================================================
ANALYTICAL MODEL SUMMARY
======================================================================

      Table   Rows                 Role
0     sales  74920   Sales transactions
1    return   4500  Return transactions
2    target   1500     Regional targets
3  customer   6000  Customer attributes
4   product    180   Product attributes
5      date    912  Calendar attributes
6    region     25  Regional attributes

======================================================================
ANALYTICAL MODEL CREATED SUCCESSFULLY
======================================================================

Saved to:
C:\Users\shubh\Desktop\AI_Sales_Intelligence\data\cleaned

Files:
✓ sales_model.csv
✓ return_model.csv
✓ customer_model.csv
✓ product_model.csv
✓ date_model.csv
✓ region_model.csv
✓ target_model.csv
✓ analytical_model_summary.csv

In [27]:
# ============================================================
# INVESTIGATE RETURN → DATE RELATIONSHIP FAILURE
# ============================================================

print("=" * 70)
print("INVESTIGATING RETURN → DATE RELATIONSHIP")
print("=" * 70)

# Find return dates that do not exist in date table
missing_return_dates = return_model[
    ~return_model["Return_Date"]
    .dt.normalize()
    .isin(date_model["Date"])
].copy()

print(f"\nReturn records with unmatched dates: {len(missing_return_dates):,}")

# Show unique unmatched dates
unmatched_dates = (
    missing_return_dates["Return_Date"]
    .dt.normalize()
    .drop_duplicates()
    .sort_values()
)

print(f"Unique unmatched dates: {len(unmatched_dates):,}")

print("\nUnmatched dates:")
display(unmatched_dates.to_frame(name="Return_Date").head(50))


# ------------------------------------------------------------
# COMPARE DATE RANGES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATE RANGE COMPARISON")
print("=" * 70)

print(
    f"Return date range : "
    f"{return_model['Return_Date'].min()} "
    f"→ "
    f"{return_model['Return_Date'].max()}"
)

print(
    f"Date table range  : "
    f"{date_model['Date'].min()} "
    f"→ "
    f"{date_model['Date'].max()}"
)


# ------------------------------------------------------------
# CHECK DATA TYPES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATE DATA TYPES")
print("=" * 70)

print(
    "Return_Date dtype:",
    return_model["Return_Date"].dtype
)

print(
    "Date dtype       :",
    date_model["Date"].dtype
)


# ------------------------------------------------------------
# CHECK TIME COMPONENTS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TIME COMPONENT CHECK")
print("=" * 70)

return_has_time = (
    return_model["Return_Date"]
    .dropna()
    .dt.time
    .astype(str)
    .nunique()
)

date_has_time = (
    date_model["Date"]
    .dropna()
    .dt.time
    .astype(str)
    .nunique()
)

print(f"Unique time values in Return_Date: {return_has_time}")
print(f"Unique time values in Date       : {date_has_time}")


# ------------------------------------------------------------
# SAMPLE RETURN DATES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("SAMPLE RETURN DATES")
print("=" * 70)

display(
    return_model[
        ["Return_ID", "Return_Date"]
    ].head(10)
)

print("\nSample Date dimension:")
display(
    date_model[
        ["Date"]
    ].head(10)
)

======================================================================
INVESTIGATING RETURN → DATE RELATIONSHIP
======================================================================

Return records with unmatched dates: 26
Unique unmatched dates: 10

Unmatched dates:

     Return_Date
178   2026-07-01
355   2026-07-02
1988  2026-07-03
274   2026-07-04
1946  2026-07-05
957   2026-07-06
4307  2026-07-07
485   2026-07-09
2795  2026-07-10
3754  2026-07-14

======================================================================
DATE RANGE COMPARISON
======================================================================
Return date range : 2024-01-05 00:00:00 → 2026-07-14 00:00:00
Date table range  : 2024-01-01 00:00:00 → 2026-06-30 00:00:00

======================================================================
DATE DATA TYPES
======================================================================
Return_Date dtype: datetime64[ns]
Date dtype       : datetime64[ns]

======================================================================
TIME COMPONENT CHECK
======================================================================
Unique time values in Return_Date: 1
Unique time values in Date       : 1

======================================================================
SAMPLE RETURN DATES
======================================================================

  Return_ID Return_Date
0  RET00001  2026-03-22
1  RET00002  2024-07-19
2  RET00003  2024-03-31
3  RET00004  2025-04-11
4  RET00005  2025-11-28
5  RET00006  2024-12-25
6  RET00007  2025-03-23
7  RET00008  2024-01-20
8  RET00009  2025-10-15
9  RET00010  2024-03-04

Sample Date dimension:

        Date
0 2024-01-01
1 2024-01-02
2 2024-01-03
3 2024-01-04
4 2024-01-05
5 2024-01-06
6 2024-01-07
7 2024-01-08
8 2024-01-09
9 2024-01-10

In [28]:
# ================================================================
# FIX DATE DIMENSION COVERAGE
# ================================================================

import pandas as pd

print("=" * 70)
print("FIXING DATE DIMENSION COVERAGE")
print("=" * 70)

# ------------------------------------------------
# 1. Identify required date range
# ------------------------------------------------

required_start = min(
    sales_model["Order_Date"].min(),
    return_model["Return_Date"].min()
)

required_end = max(
    sales_model["Order_Date"].max(),
    return_model["Return_Date"].max()
)

print(f"\nRequired date range:")
print(f"{required_start.date()} → {required_end.date()}")

print("\nCurrent date dimension:")
print(
    f"{date_model['Date'].min().date()} "
    f"→ "
    f"{date_model['Date'].max().date()}"
)

# ------------------------------------------------
# 2. Generate missing dates
# ------------------------------------------------

required_dates = pd.date_range(
    start=required_start,
    end=required_end,
    freq="D"
)

existing_dates = set(
    pd.to_datetime(date_model["Date"])
)

missing_dates = [
    d for d in required_dates
    if d not in existing_dates
]

print(f"\nMissing dates to add: {len(missing_dates)}")

# ------------------------------------------------
# 3. Add missing dates
# ------------------------------------------------

if missing_dates:

    new_dates = pd.DataFrame({
        "Date": missing_dates
    })

    # Create calendar attributes
    new_dates["Year"] = new_dates["Date"].dt.year
    new_dates["Month"] = new_dates["Date"].dt.month
    new_dates["Month_Name"] = new_dates["Date"].dt.month_name()
    new_dates["Quarter"] = (
        "Q" + new_dates["Date"].dt.quarter.astype(str)
    )

    new_dates["Day"] = new_dates["Date"].dt.day
    new_dates["Day_Name"] = new_dates["Date"].dt.day_name()
    new_dates["Week_Number"] = (
        new_dates["Date"].dt.isocalendar().week.astype(int)
    )

    new_dates["Is_Weekend"] = (
        new_dates["Date"].dt.dayofweek >= 5
    )

    # Match the existing date_model column structure
    new_dates = new_dates[
        [col for col in date_model.columns if col in new_dates.columns]
    ]

    # Add any columns that exist in date_model
    # but were not generated above
    for col in date_model.columns:
        if col not in new_dates.columns:
            new_dates[col] = pd.NA

    new_dates = new_dates[date_model.columns]

    # Combine
    date_model = pd.concat(
        [date_model, new_dates],
        ignore_index=True
    )

    # Remove accidental duplicates
    date_model = (
        date_model
        .drop_duplicates(subset=["Date"])
        .sort_values("Date")
        .reset_index(drop=True)
    )

# ------------------------------------------------
# 4. Display result
# ------------------------------------------------

print("\nUpdated date dimension:")
print(f"Rows: {len(date_model):,}")
print(
    f"Date range: "
    f"{date_model['Date'].min().date()} "
    f"→ "
    f"{date_model['Date'].max().date()}"
)

print("\nNewly added dates:")
display(
    date_model[
        date_model["Date"].isin(missing_dates)
    ].head(20)
)

# ------------------------------------------------
# 5. Validate date uniqueness
# ------------------------------------------------

duplicate_dates = date_model["Date"].duplicated().sum()

print("\n" + "=" * 70)
print("DATE DIMENSION VALIDATION")
print("=" * 70)

print(f"Duplicate dates : {duplicate_dates}")
print(f"Missing dates   : {date_model['Date'].isna().sum()}")

# ------------------------------------------------
# 6. Validate Sales → Date
# ------------------------------------------------

sales_date_missing = (
    ~pd.to_datetime(sales_model["Order_Date"])
    .dt.normalize()
    .isin(pd.to_datetime(date_model["Date"]))
).sum()

# ------------------------------------------------
# 7. Validate Return → Date
# ------------------------------------------------

return_date_missing = (
    ~pd.to_datetime(return_model["Return_Date"])
    .dt.normalize()
    .isin(pd.to_datetime(date_model["Date"]))
).sum()

print("\nRelationship validation:")
print(
    f"Sales → Date   : "
    f"{'PASS' if sales_date_missing == 0 else 'FAIL'}"
)

print(
    f"Return → Date  : "
    f"{'PASS' if return_date_missing == 0 else 'FAIL'}"
)

print(f"\nUnmatched Sales dates  : {sales_date_missing}")
print(f"Unmatched Return dates : {return_date_missing}")

# ------------------------------------------------
# 8. Save updated date model
# ------------------------------------------------

date_model_path = cleaned_path / "date_model.csv"

date_model.to_csv(
    date_model_path,
    index=False
)

print("\nSaved:")
print(date_model_path)

print("\n" + "=" * 70)
print("DATE DIMENSION FIX COMPLETE")
print("=" * 70)

======================================================================
FIXING DATE DIMENSION COVERAGE
======================================================================

Required date range:
2024-01-01 → 2026-07-14

Current date dimension:
2024-01-01 → 2026-06-30

Missing dates to add: 14

Updated date dimension:
Rows: 926
Date range: 2024-01-01 → 2026-07-14

Newly added dates:

,Date,Year,Quarter,Month_Number,Month_Name,Week_Number,Day_Name,Is_Weekend,Financial_Year
912,2026-07-01,2026,Q3,<NA>,July,27,Wednesday,False,NaN
913,2026-07-02,2026,Q3,<NA>,July,27,Thursday,False,NaN
914,2026-07-03,2026,Q3,<NA>,July,27,Friday,False,NaN
915,2026-07-04,2026,Q3,<NA>,July,27,Saturday,True,NaN
916,2026-07-05,2026,Q3,<NA>,July,27,Sunday,True,NaN
917,2026-07-06,2026,Q3,<NA>,July,28,Monday,False,NaN
918,2026-07-07,2026,Q3,<NA>,July,28,Tuesday,False,NaN
919,2026-07-08,2026,Q3,<NA>,July,28,Wednesday,False,NaN
920,2026-07-09,2026,Q3,<NA>,July,28,Thursday,False,NaN
921,2026-07-10,2026,Q3,<NA>,July,28,Friday,False,NaN
922,2026-07-11,2026,Q3,<NA>,July,28,Saturday,True,NaN
923,2026-07-12,2026,Q3,<NA>,July,28,Sunday,True,NaN
924,2026-07-13,2026,Q3,<NA>,July,29,Monday,False,NaN
925,2026-07-14,2026,Q3,<NA>,July,29,Tuesday,False,NaN

======================================================================
DATE DIMENSION VALIDATION
======================================================================
Duplicate dates : 0
Missing dates   : 0

Relationship validation:
Sales → Date   : PASS
Return → Date  : PASS

Unmatched Sales dates  : 0
Unmatched Return dates : 0

Saved:
C:\Users\shubh\Desktop\AI_Sales_Intelligence\data\cleaned\date_model.csv

======================================================================
DATE DIMENSION FIX COMPLETE
======================================================================

In [31]:
# ================================================================
# FINAL END-TO-END ANALYTICAL MODEL VALIDATION
# CORRECTED FOR ACTUAL MODEL STRUCTURE
# ================================================================

import pandas as pd

print("=" * 80)
print("FINAL ANALYTICAL MODEL VALIDATION")
print("=" * 80)


# ================================================================
# 1. TABLE SUMMARY
# ================================================================

tables = {
    "sales": sales_model,
    "return": return_model,
    "customer": customer_model,
    "product": product_model,
    "date": date_model,
    "region": region_model,
    "target": target_model
}

print("\n" + "=" * 80)
print("1. TABLE ROW COUNTS")
print("=" * 80)

for name, df in tables.items():
    print(f"{name:<12} : {len(df):>8,} rows")


# ================================================================
# 2. PRIMARY KEY VALIDATION
# ================================================================

print("\n" + "=" * 80)
print("2. PRIMARY KEY VALIDATION")
print("=" * 80)

primary_keys = {
    "sales": "Order_ID",
    "return": "Return_ID",
    "customer": "Customer_ID",
    "product": "Product_ID",
    "date": "Date",
    "region": "Region_ID",
    "target": "Target_ID"
}

pk_results = []

for table_name, pk in primary_keys.items():

    df = tables[table_name]

    duplicate_count = df[pk].duplicated().sum()
    missing_count = df[pk].isna().sum()

    status = (
        "PASS"
        if duplicate_count == 0 and missing_count == 0
        else "FAIL"
    )

    pk_results.append({
        "Table": table_name,
        "Primary_Key": pk,
        "Duplicates": duplicate_count,
        "Missing": missing_count,
        "Status": status
    })

    print(
        f"{table_name:<12} | "
        f"Key: {pk:<15} | "
        f"Duplicates: {duplicate_count:<5} | "
        f"Missing: {missing_count:<5} | "
        f"{status}"
    )

pk_results_df = pd.DataFrame(pk_results)


# ================================================================
# 3. DIRECT RELATIONSHIP VALIDATION
# ================================================================

print("\n" + "=" * 80)
print("3. DIRECT RELATIONSHIP VALIDATION")
print("=" * 80)


def validate_relationship(
    child_df,
    child_column,
    parent_df,
    parent_column
):
    child_values = child_df[child_column]
    parent_values = set(parent_df[parent_column].dropna())

    unmatched = (
        ~child_values.isin(parent_values)
    ).sum()

    return unmatched


direct_relationships = [
    (
        "Sales → Customer",
        sales_model,
        "Customer_ID",
        customer_model,
        "Customer_ID"
    ),
    (
        "Sales → Product",
        sales_model,
        "Product_ID",
        product_model,
        "Product_ID"
    ),
    (
        "Sales → Region",
        sales_model,
        "Region_ID",
        region_model,
        "Region_ID"
    ),
    (
        "Return → Customer",
        return_model,
        "Customer_ID",
        customer_model,
        "Customer_ID"
    ),
    (
        "Return → Product",
        return_model,
        "Product_ID",
        product_model,
        "Product_ID"
    ),
    (
        "Target → Region",
        target_model,
        "Region_ID",
        region_model,
        "Region_ID"
    )
]

relationship_results = []

for (
    relationship_name,
    child_df,
    child_column,
    parent_df,
    parent_column
) in direct_relationships:

    unmatched = validate_relationship(
        child_df,
        child_column,
        parent_df,
        parent_column
    )

    status = "PASS" if unmatched == 0 else "FAIL"

    relationship_results.append({
        "Relationship": relationship_name,
        "Unmatched": unmatched,
        "Status": status
    })

    print(
        f"{relationship_name:<25} | "
        f"Unmatched: {unmatched:<5} | "
        f"{status}"
    )


# ================================================================
# 4. DATE RELATIONSHIP VALIDATION
# ================================================================

print("\n" + "=" * 80)
print("4. DATE RELATIONSHIP VALIDATION")
print("=" * 80)

sales_dates = pd.to_datetime(
    sales_model["Order_Date"]
).dt.normalize()

return_dates = pd.to_datetime(
    return_model["Return_Date"]
).dt.normalize()

date_values = set(
    pd.to_datetime(
        date_model["Date"]
    ).dt.normalize()
)

sales_date_unmatched = (
    ~sales_dates.isin(date_values)
).sum()

return_date_unmatched = (
    ~return_dates.isin(date_values)
).sum()

print(
    f"Sales → Date   | "
    f"Unmatched: {sales_date_unmatched:<5} | "
    f"{'PASS' if sales_date_unmatched == 0 else 'FAIL'}"
)

print(
    f"Return → Date  | "
    f"Unmatched: {return_date_unmatched:<5} | "
    f"{'PASS' if return_date_unmatched == 0 else 'FAIL'}"
)

relationship_results.extend([
    {
        "Relationship": "Sales → Date",
        "Unmatched": sales_date_unmatched,
        "Status": "PASS" if sales_date_unmatched == 0 else "FAIL"
    },
    {
        "Relationship": "Return → Date",
        "Unmatched": return_date_unmatched,
        "Status": "PASS" if return_date_unmatched == 0 else "FAIL"
    }
])


# ================================================================
# 5. RETURN → SALES VALIDATION
# ================================================================

print("\n" + "=" * 80)
print("5. RETURN → SALES VALIDATION")
print("=" * 80)

sales_lookup = sales_model[
    [
        "Order_ID",
        "Customer_ID",
        "Product_ID",
        "Quantity",
        "Region_ID"
    ]
].copy()

return_sales_check = return_model[
    [
        "Return_ID",
        "Order_ID",
        "Customer_ID",
        "Product_ID"
    ]
].merge(
    sales_lookup,
    on="Order_ID",
    how="left",
    suffixes=("_Return", "_Sales")
)

order_missing = (
    return_sales_check["Customer_ID_Sales"].isna()
).sum()

customer_mismatch = (
    return_sales_check["Customer_ID_Return"]
    != return_sales_check["Customer_ID_Sales"]
).sum()

product_mismatch = (
    return_sales_check["Product_ID_Return"]
    != return_sales_check["Product_ID_Sales"]
).sum()

print(
    f"Returns with missing Sales order : "
    f"{order_missing}"
)

print(
    f"Customer mismatches              : "
    f"{customer_mismatch}"
)

print(
    f"Product mismatches               : "
    f"{product_mismatch}"
)

return_sales_pass = (
    order_missing == 0
    and customer_mismatch == 0
    and product_mismatch == 0
)

print(
    f"\nReturn → Sales consistency : "
    f"{'PASS' if return_sales_pass else 'FAIL'}"
)


# ================================================================
# 6. SALES DATA QUALITY
# ================================================================

print("\n" + "=" * 80)
print("6. SALES DATA QUALITY")
print("=" * 80)

sales_checks = {
    "Missing values":
        sales_model.isna().sum().sum(),

    "Duplicate records":
        sales_model.duplicated().sum(),

    "Duplicate Order_ID":
        sales_model["Order_ID"].duplicated().sum(),

    "Quantity <= 0":
        (sales_model["Quantity"] <= 0).sum(),

    "Negative Sales":
        (sales_model["Sales_Amount"] < 0).sum(),

    "Negative Cost":
        (sales_model["Cost_Amount"] < 0).sum(),

    "Negative Profit":
        (sales_model["Profit"] < 0).sum(),

    "Discount < 0":
        (sales_model["Discount_Percent"] < 0).sum(),

    "Discount > 100":
        (sales_model["Discount_Percent"] > 100).sum()
}

for check, value in sales_checks.items():
    print(f"{check:<25} : {value:,}")


# ================================================================
# 7. RETURN DATA QUALITY
# ================================================================

print("\n" + "=" * 80)
print("7. RETURN DATA QUALITY")
print("=" * 80)

return_checks = {
    "Missing values":
        return_model.isna().sum().sum(),

    "Duplicate records":
        return_model.duplicated().sum(),

    "Duplicate Return_ID":
        return_model["Return_ID"].duplicated().sum(),

    "Return Quantity <= 0":
        (return_model["Return_Quantity"] <= 0).sum(),

    "Negative Refund":
        (return_model["Refund_Amount"] < 0).sum(),

    "Valid Returns":
        (return_model["Is_Valid_Return"] == True).sum(),

    "Quantity Anomalies":
        (
            return_model["Final_Data_Quality_Status"]
            == "Quantity Anomaly"
        ).sum(),

    "Orphan Returns":
        (
            return_model["Final_Data_Quality_Status"]
            == "Orphan Return"
        ).sum()
}

for check, value in return_checks.items():
    print(f"{check:<25} : {value:,}")


# ================================================================
# 8. DIMENSION VALIDATION
# ================================================================

print("\n" + "=" * 80)
print("8. DIMENSION TABLE VALIDATION")
print("=" * 80)

dimension_checks = {
    "Customer": (
        len(customer_model),
        customer_model["Customer_ID"].nunique()
    ),

    "Product": (
        len(product_model),
        product_model["Product_ID"].nunique()
    ),

    "Date": (
        len(date_model),
        date_model["Date"].nunique()
    ),

    "Region": (
        len(region_model),
        region_model["Region_ID"].nunique()
    )
}

dimension_pass = True

for dimension, (rows, unique_keys) in dimension_checks.items():

    status = "PASS" if rows == unique_keys else "FAIL"

    if status == "FAIL":
        dimension_pass = False

    print(
        f"{dimension:<12} | "
        f"Rows: {rows:>6,} | "
        f"Unique Keys: {unique_keys:>6,} | "
        f"{status}"
    )


# ================================================================
# 9. RETURN QUALITY DISTRIBUTION
# ================================================================

print("\n" + "=" * 80)
print("9. RETURN QUALITY DISTRIBUTION")
print("=" * 80)

return_quality = (
    return_model[
        "Final_Data_Quality_Status"
    ]
    .value_counts()
    .rename_axis("Status")
    .reset_index(name="Records")
)

return_quality["Percentage"] = (
    return_quality["Records"]
    / len(return_model)
    * 100
)

display(return_quality)


# ================================================================
# 10. OVERALL MODEL STATUS
# ================================================================

print("\n" + "=" * 80)
print("10. OVERALL MODEL STATUS")
print("=" * 80)

pk_pass = (
    pk_results_df["Status"] == "PASS"
).all()

relationship_pass = (
    pd.DataFrame(relationship_results)["Status"]
    == "PASS"
).all()

sales_quality_pass = (
    sales_checks["Missing values"] == 0
    and sales_checks["Duplicate records"] == 0
    and sales_checks["Duplicate Order_ID"] == 0
    and sales_checks["Quantity <= 0"] == 0
    and sales_checks["Negative Sales"] == 0
    and sales_checks["Negative Cost"] == 0
    and sales_checks["Discount < 0"] == 0
    and sales_checks["Discount > 100"] == 0
)

return_quality_pass = (
    return_checks["Missing values"] == 0
    and return_checks["Duplicate records"] == 0
    and return_checks["Duplicate Return_ID"] == 0
    and return_checks["Return Quantity <= 0"] == 0
    and return_checks["Negative Refund"] == 0
)

overall_status = (
    pk_pass
    and relationship_pass
    and return_sales_pass
    and dimension_pass
    and sales_quality_pass
    and return_quality_pass
)

print(
    f"Primary Keys       : "
    f"{'PASS' if pk_pass else 'FAIL'}"
)

print(
    f"Relationships      : "
    f"{'PASS' if relationship_pass else 'FAIL'}"
)

print(
    f"Return → Sales     : "
    f"{'PASS' if return_sales_pass else 'FAIL'}"
)

print(
    f"Dimensions         : "
    f"{'PASS' if dimension_pass else 'FAIL'}"
)

print(
    f"Sales Quality      : "
    f"{'PASS' if sales_quality_pass else 'FAIL'}"
)

print(
    f"Return Quality     : "
    f"{'PASS' if return_quality_pass else 'FAIL'}"
)

print("\n" + "-" * 80)

if overall_status:
    print("FINAL MODEL STATUS : PASS")
    print(
        "The analytical model is ready for KPI development."
    )
else:
    print("FINAL MODEL STATUS : REVIEW REQUIRED")
    print(
        "Resolve failed checks before KPI development."
    )

print("-" * 80)

================================================================================
FINAL ANALYTICAL MODEL VALIDATION
================================================================================

================================================================================
1. TABLE ROW COUNTS
================================================================================
sales        :   74,920 rows
return       :    4,500 rows
customer     :    6,000 rows
product      :      180 rows
date         :      926 rows
region       :       25 rows
target       :    1,500 rows

================================================================================
2. PRIMARY KEY VALIDATION
================================================================================
sales        | Key: Order_ID        | Duplicates: 0     | Missing: 0     | PASS
return       | Key: Return_ID       | Duplicates: 0     | Missing: 0     | PASS
customer     | Key: Customer_ID     | Duplicates: 0     | Missing: 0     | PASS
product      | Key: Product_ID      | Duplicates: 0     | Missing: 0     | PASS
date         | Key: Date            | Duplicates: 0     | Missing: 0     | PASS
region       | Key: Region_ID       | Duplicates: 0     | Missing: 0     | PASS
target       | Key: Target_ID       | Duplicates: 0     | Missing: 0     | PASS

================================================================================
3. DIRECT RELATIONSHIP VALIDATION
================================================================================
Sales → Customer          | Unmatched: 0     | PASS
Sales → Product           | Unmatched: 0     | PASS
Sales → Region            | Unmatched: 0     | PASS
Return → Customer         | Unmatched: 0     | PASS
Return → Product          | Unmatched: 0     | PASS
Target → Region           | Unmatched: 0     | PASS

================================================================================
4. DATE RELATIONSHIP VALIDATION
================================================================================
Sales → Date   | Unmatched: 0     | PASS
Return → Date  | Unmatched: 0     | PASS

================================================================================
5. RETURN → SALES VALIDATION
================================================================================
Returns with missing Sales order : 3
Customer mismatches              : 3
Product mismatches               : 3

Return → Sales consistency : FAIL

================================================================================
6. SALES DATA QUALITY
================================================================================
Missing values            : 0
Duplicate records         : 0
Duplicate Order_ID        : 0
Quantity <= 0             : 0
Negative Sales            : 0
Negative Cost             : 0
Negative Profit           : 906
Discount < 0              : 0
Discount > 100            : 0

================================================================================
7. RETURN DATA QUALITY
================================================================================
Missing values            : 0
Duplicate records         : 0
Duplicate Return_ID       : 0
Return Quantity <= 0      : 0
Negative Refund           : 0
Valid Returns             : 4,247
Quantity Anomalies        : 250
Orphan Returns            : 3

================================================================================
8. DIMENSION TABLE VALIDATION
================================================================================
Customer     | Rows:  6,000 | Unique Keys:  6,000 | PASS
Product      | Rows:    180 | Unique Keys:    180 | PASS
Date         | Rows:    926 | Unique Keys:    926 | PASS
Region       | Rows:     25 | Unique Keys:     25 | PASS

================================================================================
9. RETURN QUALITY DISTRIBUTION
================================================================================

             Status  Records  Percentage
0             Valid     4247   94.377778
1  Quantity Anomaly      250    5.555556
2     Orphan Return        3    0.066667

================================================================================
10. OVERALL MODEL STATUS
================================================================================
Primary Keys       : PASS
Relationships      : PASS
Return → Sales     : FAIL
Dimensions         : PASS
Sales Quality      : PASS
Return Quality     : PASS

--------------------------------------------------------------------------------
FINAL MODEL STATUS : REVIEW REQUIRED
Resolve failed checks before KPI development.
--------------------------------------------------------------------------------

In [32]:
# ================================================================
# FINAL ANALYTICAL MODEL VALIDATION
# FINAL CORRECTED VERSION
# ================================================================

import pandas as pd

print("=" * 80)
print("FINAL ANALYTICAL MODEL VALIDATION")
print("=" * 80)


# ================================================================
# 1. TABLE ROW COUNTS
# ================================================================

tables = {
    "sales": sales_model,
    "return": return_model,
    "customer": customer_model,
    "product": product_model,
    "date": date_model,
    "region": region_model,
    "target": target_model
}

print("\n" + "=" * 80)
print("1. TABLE ROW COUNTS")
print("=" * 80)

for name, df in tables.items():
    print(f"{name:<12} : {len(df):>8,} rows")


# ================================================================
# 2. PRIMARY KEY VALIDATION
# ================================================================

print("\n" + "=" * 80)
print("2. PRIMARY KEY VALIDATION")
print("=" * 80)

primary_keys = {
    "sales": "Order_ID",
    "return": "Return_ID",
    "customer": "Customer_ID",
    "product": "Product_ID",
    "date": "Date",
    "region": "Region_ID",
    "target": "Target_ID"
}

pk_results = []

for table_name, pk in primary_keys.items():

    df = tables[table_name]

    duplicate_count = df[pk].duplicated().sum()
    missing_count = df[pk].isna().sum()

    status = (
        "PASS"
        if duplicate_count == 0 and missing_count == 0
        else "FAIL"
    )

    pk_results.append({
        "Table": table_name,
        "Primary_Key": pk,
        "Duplicates": duplicate_count,
        "Missing": missing_count,
        "Status": status
    })

    print(
        f"{table_name:<12} | "
        f"Key: {pk:<15} | "
        f"Duplicates: {duplicate_count:<5} | "
        f"Missing: {missing_count:<5} | "
        f"{status}"
    )

pk_results_df = pd.DataFrame(pk_results)


# ================================================================
# 3. DIRECT RELATIONSHIP VALIDATION
# ================================================================

print("\n" + "=" * 80)
print("3. DIRECT RELATIONSHIP VALIDATION")
print("=" * 80)


def validate_relationship(
    child_df,
    child_column,
    parent_df,
    parent_column
):

    child_values = child_df[child_column]
    parent_values = set(
        parent_df[parent_column].dropna()
    )

    unmatched = (
        ~child_values.isin(parent_values)
    ).sum()

    return unmatched


direct_relationships = [
    (
        "Sales → Customer",
        sales_model,
        "Customer_ID",
        customer_model,
        "Customer_ID"
    ),
    (
        "Sales → Product",
        sales_model,
        "Product_ID",
        product_model,
        "Product_ID"
    ),
    (
        "Sales → Region",
        sales_model,
        "Region_ID",
        region_model,
        "Region_ID"
    ),
    (
        "Return → Customer",
        return_model,
        "Customer_ID",
        customer_model,
        "Customer_ID"
    ),
    (
        "Return → Product",
        return_model,
        "Product_ID",
        product_model,
        "Product_ID"
    ),
    (
        "Target → Region",
        target_model,
        "Region_ID",
        region_model,
        "Region_ID"
    )
]

relationship_results = []

for (
    relationship_name,
    child_df,
    child_column,
    parent_df,
    parent_column
) in direct_relationships:

    unmatched = validate_relationship(
        child_df,
        child_column,
        parent_df,
        parent_column
    )

    status = (
        "PASS"
        if unmatched == 0
        else "FAIL"
    )

    relationship_results.append({
        "Relationship": relationship_name,
        "Unmatched": unmatched,
        "Status": status
    })

    print(
        f"{relationship_name:<25} | "
        f"Unmatched: {unmatched:<5} | "
        f"{status}"
    )


# ================================================================
# 4. DATE RELATIONSHIPS
# ================================================================

print("\n" + "=" * 80)
print("4. DATE RELATIONSHIP VALIDATION")
print("=" * 80)

sales_dates = pd.to_datetime(
    sales_model["Order_Date"]
).dt.normalize()

return_dates = pd.to_datetime(
    return_model["Return_Date"]
).dt.normalize()

date_values = set(
    pd.to_datetime(
        date_model["Date"]
    ).dt.normalize()
)

sales_date_unmatched = (
    ~sales_dates.isin(date_values)
).sum()

return_date_unmatched = (
    ~return_dates.isin(date_values)
).sum()

print(
    f"Sales → Date   | "
    f"Unmatched: {sales_date_unmatched:<5} | "
    f"{'PASS' if sales_date_unmatched == 0 else 'FAIL'}"
)

print(
    f"Return → Date  | "
    f"Unmatched: {return_date_unmatched:<5} | "
    f"{'PASS' if return_date_unmatched == 0 else 'FAIL'}"
)

relationship_results.extend([
    {
        "Relationship": "Sales → Date",
        "Unmatched": sales_date_unmatched,
        "Status":
            "PASS"
            if sales_date_unmatched == 0
            else "FAIL"
    },
    {
        "Relationship": "Return → Date",
        "Unmatched": return_date_unmatched,
        "Status":
            "PASS"
            if return_date_unmatched == 0
            else "FAIL"
    }
])


# ================================================================
# 5. RETURN → SALES VALIDATION
# ================================================================

print("\n" + "=" * 80)
print("5. RETURN → SALES VALIDATION")
print("=" * 80)

# Known orphan returns
known_orphan_returns = return_model[
    return_model["Orphan_Return"] == True
].copy()

print(
    f"Known orphan returns preserved : "
    f"{len(known_orphan_returns):,}"
)

# Returns that should have a valid sales relationship
returns_expected_to_match = return_model[
    return_model["Orphan_Return"] == False
].copy()

sales_lookup = sales_model[
    [
        "Order_ID",
        "Customer_ID",
        "Product_ID",
        "Quantity",
        "Region_ID"
    ]
].copy()

return_sales_check = returns_expected_to_match[
    [
        "Return_ID",
        "Order_ID",
        "Customer_ID",
        "Product_ID"
    ]
].merge(
    sales_lookup,
    on="Order_ID",
    how="left",
    suffixes=("_Return", "_Sales")
)

missing_sales_orders = (
    return_sales_check["Customer_ID_Sales"].isna()
).sum()

customer_mismatches = (
    return_sales_check["Customer_ID_Return"]
    != return_sales_check["Customer_ID_Sales"]
).sum()

product_mismatches = (
    return_sales_check["Product_ID_Return"]
    != return_sales_check["Product_ID_Sales"]
).sum()

print(
    f"Non-orphan returns checked      : "
    f"{len(returns_expected_to_match):,}"
)

print(
    f"Missing Sales orders            : "
    f"{missing_sales_orders:,}"
)

print(
    f"Customer mismatches             : "
    f"{customer_mismatches:,}"
)

print(
    f"Product mismatches              : "
    f"{product_mismatches:,}"
)

return_sales_pass = (
    missing_sales_orders == 0
    and customer_mismatches == 0
    and product_mismatches == 0
)

print(
    f"\nReturn → Sales consistency "
    f"(excluding known orphans): "
    f"{'PASS' if return_sales_pass else 'FAIL'}"
)


# ================================================================
# 6. SALES DATA QUALITY
# ================================================================

print("\n" + "=" * 80)
print("6. SALES DATA QUALITY")
print("=" * 80)

sales_checks = {
    "Missing values":
        sales_model.isna().sum().sum(),

    "Duplicate records":
        sales_model.duplicated().sum(),

    "Duplicate Order_ID":
        sales_model["Order_ID"].duplicated().sum(),

    "Quantity <= 0":
        (sales_model["Quantity"] <= 0).sum(),

    "Negative Sales":
        (sales_model["Sales_Amount"] < 0).sum(),

    "Negative Cost":
        (sales_model["Cost_Amount"] < 0).sum(),

    "Negative Profit":
        (sales_model["Profit"] < 0).sum(),

    "Discount < 0":
        (sales_model["Discount_Percent"] < 0).sum(),

    "Discount > 100":
        (sales_model["Discount_Percent"] > 100).sum()
}

for check, value in sales_checks.items():
    print(
        f"{check:<25} : {value:,}"
    )


# ================================================================
# 7. RETURN DATA QUALITY
# ================================================================

print("\n" + "=" * 80)
print("7. RETURN DATA QUALITY")
print("=" * 80)

return_checks = {
    "Missing values":
        return_model.isna().sum().sum(),

    "Duplicate records":
        return_model.duplicated().sum(),

    "Duplicate Return_ID":
        return_model["Return_ID"].duplicated().sum(),

    "Return Quantity <= 0":
        (
            return_model["Return_Quantity"] <= 0
        ).sum(),

    "Negative Refund":
        (
            return_model["Refund_Amount"] < 0
        ).sum(),

    "Valid Returns":
        (
            return_model["Is_Valid_Return"] == True
        ).sum(),

    "Quantity Anomalies":
        (
            return_model[
                "Final_Data_Quality_Status"
            ] == "Quantity Anomaly"
        ).sum(),

    "Orphan Returns":
        (
            return_model[
                "Final_Data_Quality_Status"
            ] == "Orphan Return"
        ).sum()
}

for check, value in return_checks.items():
    print(
        f"{check:<25} : {value:,}"
    )


# ================================================================
# 8. DIMENSION VALIDATION
# ================================================================

print("\n" + "=" * 80)
print("8. DIMENSION TABLE VALIDATION")
print("=" * 80)

dimension_checks = {
    "Customer": (
        len(customer_model),
        customer_model["Customer_ID"].nunique()
    ),

    "Product": (
        len(product_model),
        product_model["Product_ID"].nunique()
    ),

    "Date": (
        len(date_model),
        date_model["Date"].nunique()
    ),

    "Region": (
        len(region_model),
        region_model["Region_ID"].nunique()
    )
}

dimension_pass = True

for dimension, (rows, unique_keys) in dimension_checks.items():

    status = (
        "PASS"
        if rows == unique_keys
        else "FAIL"
    )

    if status == "FAIL":
        dimension_pass = False

    print(
        f"{dimension:<12} | "
        f"Rows: {rows:>6,} | "
        f"Unique Keys: {unique_keys:>6,} | "
        f"{status}"
    )


# ================================================================
# 9. RETURN QUALITY DISTRIBUTION
# ================================================================

print("\n" + "=" * 80)
print("9. RETURN QUALITY DISTRIBUTION")
print("=" * 80)

return_quality = (
    return_model[
        "Final_Data_Quality_Status"
    ]
    .value_counts()
    .rename_axis("Status")
    .reset_index(name="Records")
)

return_quality["Percentage"] = (
    return_quality["Records"]
    / len(return_model)
    * 100
)

display(return_quality)


# ================================================================
# 10. OVERALL MODEL STATUS
# ================================================================

print("\n" + "=" * 80)
print("10. OVERALL MODEL STATUS")
print("=" * 80)

pk_pass = (
    pk_results_df["Status"] == "PASS"
).all()

relationship_pass = (
    pd.DataFrame(relationship_results)["Status"]
    == "PASS"
).all()

sales_quality_pass = (
    sales_checks["Missing values"] == 0
    and sales_checks["Duplicate records"] == 0
    and sales_checks["Duplicate Order_ID"] == 0
    and sales_checks["Quantity <= 0"] == 0
    and sales_checks["Negative Sales"] == 0
    and sales_checks["Negative Cost"] == 0
    and sales_checks["Discount < 0"] == 0
    and sales_checks["Discount > 100"] == 0
)

return_quality_pass = (
    return_checks["Missing values"] == 0
    and return_checks["Duplicate records"] == 0
    and return_checks["Duplicate Return_ID"] == 0
    and return_checks["Return Quantity <= 0"] == 0
    and return_checks["Negative Refund"] == 0
)

overall_status = (
    pk_pass
    and relationship_pass
    and return_sales_pass
    and dimension_pass
    and sales_quality_pass
    and return_quality_pass
)

print(
    f"Primary Keys       : "
    f"{'PASS' if pk_pass else 'FAIL'}"
)

print(
    f"Relationships      : "
    f"{'PASS' if relationship_pass else 'FAIL'}"
)

print(
    f"Return → Sales     : "
    f"{'PASS' if return_sales_pass else 'FAIL'}"
)

print(
    f"Dimensions         : "
    f"{'PASS' if dimension_pass else 'FAIL'}"
)

print(
    f"Sales Quality      : "
    f"{'PASS' if sales_quality_pass else 'FAIL'}"
)

print(
    f"Return Quality     : "
    f"{'PASS' if return_quality_pass else 'FAIL'}"
)

print("\n" + "-" * 80)

if overall_status:
    print("FINAL MODEL STATUS : PASS")
    print(
        "The analytical model is ready for KPI development."
    )
else:
    print("FINAL MODEL STATUS : REVIEW REQUIRED")
    print(
        "Resolve failed checks before KPI development."
    )

print("-" * 80)

================================================================================
FINAL ANALYTICAL MODEL VALIDATION
================================================================================

================================================================================
1. TABLE ROW COUNTS
================================================================================
sales        :   74,920 rows
return       :    4,500 rows
customer     :    6,000 rows
product      :      180 rows
date         :      926 rows
region       :       25 rows
target       :    1,500 rows

================================================================================
2. PRIMARY KEY VALIDATION
================================================================================
sales        | Key: Order_ID        | Duplicates: 0     | Missing: 0     | PASS
return       | Key: Return_ID       | Duplicates: 0     | Missing: 0     | PASS
customer     | Key: Customer_ID     | Duplicates: 0     | Missing: 0     | PASS
product      | Key: Product_ID      | Duplicates: 0     | Missing: 0     | PASS
date         | Key: Date            | Duplicates: 0     | Missing: 0     | PASS
region       | Key: Region_ID       | Duplicates: 0     | Missing: 0     | PASS
target       | Key: Target_ID       | Duplicates: 0     | Missing: 0     | PASS

================================================================================
3. DIRECT RELATIONSHIP VALIDATION
================================================================================
Sales → Customer          | Unmatched: 0     | PASS
Sales → Product           | Unmatched: 0     | PASS
Sales → Region            | Unmatched: 0     | PASS
Return → Customer         | Unmatched: 0     | PASS
Return → Product          | Unmatched: 0     | PASS
Target → Region           | Unmatched: 0     | PASS

================================================================================
4. DATE RELATIONSHIP VALIDATION
================================================================================
Sales → Date   | Unmatched: 0     | PASS
Return → Date  | Unmatched: 0     | PASS

================================================================================
5. RETURN → SALES VALIDATION
================================================================================
Known orphan returns preserved : 3
Non-orphan returns checked      : 4,497
Missing Sales orders            : 0
Customer mismatches             : 0
Product mismatches              : 0

Return → Sales consistency (excluding known orphans): PASS

================================================================================
6. SALES DATA QUALITY
================================================================================
Missing values            : 0
Duplicate records         : 0
Duplicate Order_ID        : 0
Quantity <= 0             : 0
Negative Sales            : 0
Negative Cost             : 0
Negative Profit           : 906
Discount < 0              : 0
Discount > 100            : 0

================================================================================
7. RETURN DATA QUALITY
================================================================================
Missing values            : 0
Duplicate records         : 0
Duplicate Return_ID       : 0
Return Quantity <= 0      : 0
Negative Refund           : 0
Valid Returns             : 4,247
Quantity Anomalies        : 250
Orphan Returns            : 3

================================================================================
8. DIMENSION TABLE VALIDATION
================================================================================
Customer     | Rows:  6,000 | Unique Keys:  6,000 | PASS
Product      | Rows:    180 | Unique Keys:    180 | PASS
Date         | Rows:    926 | Unique Keys:    926 | PASS
Region       | Rows:     25 | Unique Keys:     25 | PASS

================================================================================
9. RETURN QUALITY DISTRIBUTION
================================================================================

             Status  Records  Percentage
0             Valid     4247   94.377778
1  Quantity Anomaly      250    5.555556
2     Orphan Return        3    0.066667

================================================================================
10. OVERALL MODEL STATUS
================================================================================
Primary Keys       : PASS
Relationships      : PASS
Return → Sales     : PASS
Dimensions         : PASS
Sales Quality      : PASS
Return Quality     : PASS

--------------------------------------------------------------------------------
FINAL MODEL STATUS : PASS
The analytical model is ready for KPI development.
--------------------------------------------------------------------------------

KPI Specification & Metric Definitions

In [33]:
# ============================================================
# KPI SPECIFICATION
# AI Sales Intelligence Project
# ============================================================

kpi_spec = [
    # --------------------------------------------------------
    # SALES
    # --------------------------------------------------------
    {
        "KPI_Category": "Sales",
        "KPI_Name": "Total Revenue",
        "Business_Definition": "Total realized sales value generated from all valid sales transactions.",
        "Formula": "SUM(Sales_Amount)",
        "Source_Table": "sales",
        "Primary_Column": "Sales_Amount",
        "Business_Use": "Measures overall sales performance."
    },
    {
        "KPI_Category": "Sales",
        "KPI_Name": "Total Cost",
        "Business_Definition": "Total cost associated with sales transactions.",
        "Formula": "SUM(Cost_Amount)",
        "Source_Table": "sales",
        "Primary_Column": "Cost_Amount",
        "Business_Use": "Measures total cost of sales."
    },
    {
        "KPI_Category": "Sales",
        "KPI_Name": "Total Profit",
        "Business_Definition": "Total profit generated from sales transactions.",
        "Formula": "SUM(Profit)",
        "Source_Table": "sales",
        "Primary_Column": "Profit",
        "Business_Use": "Measures absolute profitability."
    },
    {
        "KPI_Category": "Sales",
        "KPI_Name": "Profit Margin %",
        "Business_Definition": "Percentage of revenue retained as profit.",
        "Formula": "Total Profit / Total Revenue * 100",
        "Source_Table": "sales",
        "Primary_Column": "Profit, Sales_Amount",
        "Business_Use": "Measures profitability efficiency."
    },
    {
        "KPI_Category": "Sales",
        "KPI_Name": "Total Orders",
        "Business_Definition": "Number of unique customer orders.",
        "Formula": "COUNT(DISTINCT Order_ID)",
        "Source_Table": "sales",
        "Primary_Column": "Order_ID",
        "Business_Use": "Measures transaction volume."
    },
    {
        "KPI_Category": "Sales",
        "KPI_Name": "Units Sold",
        "Business_Definition": "Total number of units sold.",
        "Formula": "SUM(Quantity)",
        "Source_Table": "sales",
        "Primary_Column": "Quantity",
        "Business_Use": "Measures sales volume."
    },
    {
        "KPI_Category": "Sales",
        "KPI_Name": "Average Order Value",
        "Business_Definition": "Average revenue generated per order.",
        "Formula": "Total Revenue / Total Orders",
        "Source_Table": "sales",
        "Primary_Column": "Sales_Amount, Order_ID",
        "Business_Use": "Measures average customer transaction value."
    },
    {
        "KPI_Category": "Sales",
        "KPI_Name": "Average Selling Price",
        "Business_Definition": "Average realized selling price per unit.",
        "Formula": "Total Revenue / Units Sold",
        "Source_Table": "sales",
        "Primary_Column": "Sales_Amount, Quantity",
        "Business_Use": "Measures average realized unit price."
    },

    # --------------------------------------------------------
    # DISCOUNT
    # --------------------------------------------------------
    {
        "KPI_Category": "Discount",
        "KPI_Name": "Average Discount %",
        "Business_Definition": "Average percentage discount applied to sales transactions.",
        "Formula": "AVG(Discount_Percent)",
        "Source_Table": "sales",
        "Primary_Column": "Discount_Percent",
        "Business_Use": "Measures overall discounting behavior."
    },
    {
        "KPI_Category": "Discount",
        "KPI_Name": "Discount Amount",
        "Business_Definition": "Total monetary value given as discounts.",
        "Formula": "SUM(Gross_Sales - Sales_Amount)",
        "Source_Table": "sales",
        "Primary_Column": "Gross_Sales, Sales_Amount",
        "Business_Use": "Measures revenue sacrificed through discounts."
    },
    {
        "KPI_Category": "Discount",
        "KPI_Name": "Discount Impact on Profit",
        "Business_Definition": "Relationship between discount levels and resulting profitability.",
        "Formula": "Compare Profit / Margin across discount bands.",
        "Source_Table": "sales",
        "Primary_Column": "Discount_Percent, Profit",
        "Business_Use": "Identifies whether higher discounts improve or reduce profitability."
    },

    # --------------------------------------------------------
    # CUSTOMER
    # --------------------------------------------------------
    {
        "KPI_Category": "Customer",
        "KPI_Name": "Unique Customers",
        "Business_Definition": "Number of distinct customers who placed orders.",
        "Formula": "COUNT(DISTINCT Customer_ID)",
        "Source_Table": "sales",
        "Primary_Column": "Customer_ID",
        "Business_Use": "Measures customer reach."
    },
    {
        "KPI_Category": "Customer",
        "KPI_Name": "Revenue per Customer",
        "Business_Definition": "Average revenue generated per customer.",
        "Formula": "Total Revenue / Unique Customers",
        "Source_Table": "sales",
        "Primary_Column": "Sales_Amount, Customer_ID",
        "Business_Use": "Measures customer value."
    },
    {
        "KPI_Category": "Customer",
        "KPI_Name": "Repeat Customers",
        "Business_Definition": "Customers who placed more than one order.",
        "Formula": "COUNT(Customer_ID where Order_Count > 1)",
        "Source_Table": "sales",
        "Primary_Column": "Customer_ID, Order_ID",
        "Business_Use": "Measures customer retention behavior."
    },
    {
        "KPI_Category": "Customer",
        "KPI_Name": "One-Time Customers",
        "Business_Definition": "Customers who placed exactly one order.",
        "Formula": "COUNT(Customer_ID where Order_Count = 1)",
        "Source_Table": "sales",
        "Primary_Column": "Customer_ID, Order_ID",
        "Business_Use": "Identifies customers with limited engagement."
    },

    # --------------------------------------------------------
    # PRODUCT
    # --------------------------------------------------------
    {
        "KPI_Category": "Product",
        "KPI_Name": "Product Revenue",
        "Business_Definition": "Revenue generated by each product.",
        "Formula": "SUM(Sales_Amount) by Product_ID",
        "Source_Table": "sales",
        "Primary_Column": "Product_ID, Sales_Amount",
        "Business_Use": "Identifies revenue-driving products."
    },
    {
        "KPI_Category": "Product",
        "KPI_Name": "Product Profit",
        "Business_Definition": "Profit generated by each product.",
        "Formula": "SUM(Profit) by Product_ID",
        "Source_Table": "sales",
        "Primary_Column": "Product_ID, Profit",
        "Business_Use": "Identifies profitable products."
    },
    {
        "KPI_Category": "Product",
        "KPI_Name": "Product Margin %",
        "Business_Definition": "Profitability percentage for each product.",
        "Formula": "Product Profit / Product Revenue * 100",
        "Source_Table": "sales",
        "Primary_Column": "Product_ID, Profit, Sales_Amount",
        "Business_Use": "Compares product profitability."
    },

    # --------------------------------------------------------
    # REGIONAL
    # --------------------------------------------------------
    {
        "KPI_Category": "Regional",
        "KPI_Name": "Regional Revenue",
        "Business_Definition": "Revenue generated by each region.",
        "Formula": "SUM(Sales_Amount) by Region_ID",
        "Source_Table": "sales",
        "Primary_Column": "Region_ID, Sales_Amount",
        "Business_Use": "Measures regional sales performance."
    },
    {
        "KPI_Category": "Regional",
        "KPI_Name": "Regional Profit",
        "Business_Definition": "Profit generated by each region.",
        "Formula": "SUM(Profit) by Region_ID",
        "Source_Table": "sales",
        "Primary_Column": "Region_ID, Profit",
        "Business_Use": "Measures regional profitability."
    },
    {
        "KPI_Category": "Regional",
        "KPI_Name": "Target Achievement %",
        "Business_Definition": "Percentage of target revenue achieved.",
        "Formula": "Actual Revenue / Target Revenue * 100",
        "Source_Table": "sales + target",
        "Primary_Column": "Sales_Amount + Target",
        "Business_Use": "Measures performance against business targets."
    },

    # --------------------------------------------------------
    # RETURNS
    # --------------------------------------------------------
    {
        "KPI_Category": "Return",
        "KPI_Name": "Valid Return Quantity",
        "Business_Definition": "Quantity returned from records classified as valid returns.",
        "Formula": "SUM(Analytical_Return_Quantity)",
        "Source_Table": "return",
        "Primary_Column": "Analytical_Return_Quantity",
        "Business_Use": "Measures valid returned units."
    },
    {
        "KPI_Category": "Return",
        "KPI_Name": "Return Rate %",
        "Business_Definition": "Percentage of sold units that were validly returned.",
        "Formula": "Valid Returned Quantity / Units Sold * 100",
        "Source_Table": "return + sales",
        "Primary_Column": "Analytical_Return_Quantity + Quantity",
        "Business_Use": "Measures product return risk."
    },
    {
        "KPI_Category": "Return",
        "KPI_Name": "Refund Amount",
        "Business_Definition": "Total refund value associated with returns.",
        "Formula": "SUM(Analytical_Refund_Amount)",
        "Source_Table": "return",
        "Primary_Column": "Analytical_Refund_Amount",
        "Business_Use": "Measures financial impact of returns."
    },

    # --------------------------------------------------------
    # TIME
    # --------------------------------------------------------
    {
        "KPI_Category": "Time",
        "KPI_Name": "Monthly Revenue",
        "Business_Definition": "Revenue generated during each month.",
        "Formula": "SUM(Sales_Amount) by Year and Month",
        "Source_Table": "sales",
        "Primary_Column": "Sales_Amount, Year, Month",
        "Business_Use": "Tracks revenue trends."
    },
    {
        "KPI_Category": "Time",
        "KPI_Name": "MoM Revenue Growth %",
        "Business_Definition": "Percentage change in revenue compared with the previous month.",
        "Formula": "(Current Revenue - Previous Revenue) / Previous Revenue * 100",
        "Source_Table": "sales",
        "Primary_Column": "Sales_Amount, Year, Month",
        "Business_Use": "Measures short-term growth."
    },
    {
        "KPI_Category": "Time",
        "KPI_Name": "YoY Revenue Growth %",
        "Business_Definition": "Percentage change in revenue compared with the same period in the previous year.",
        "Formula": "(Current Revenue - Previous Year Revenue) / Previous Year Revenue * 100",
        "Source_Table": "sales",
        "Primary_Column": "Sales_Amount, Year, Month",
        "Business_Use": "Measures year-over-year growth."
    }
]


# Convert specification into a DataFrame
kpi_spec_df = pd.DataFrame(kpi_spec)

# Display specification
print(f"Total KPIs defined: {len(kpi_spec_df)}")
display(kpi_spec_df)

Total KPIs defined: 27

,KPI_Category,KPI_Name,Business_Definition,Formula,Source_Table,Primary_Column,Business_Use
0,Sales,Total Revenue,Total realized sales value generated from all ...,SUM(Sales_Amount),sales,Sales_Amount,Measures overall sales performance.
1,Sales,Total Cost,Total cost associated with sales transactions.,SUM(Cost_Amount),sales,Cost_Amount,Measures total cost of sales.
2,Sales,Total Profit,Total profit generated from sales transactions.,SUM(Profit),sales,Profit,Measures absolute profitability.
3,Sales,Profit Margin %,Percentage of revenue retained as profit.,Total Profit / Total Revenue * 100,sales,"Profit, Sales_Amount",Measures profitability efficiency.
4,Sales,Total Orders,Number of unique customer orders.,COUNT(DISTINCT Order_ID),sales,Order_ID,Measures transaction volume.
5,Sales,Units Sold,Total number of units sold.,SUM(Quantity),sales,Quantity,Measures sales volume.
6,Sales,Average Order Value,Average revenue generated per order.,Total Revenue / Total Orders,sales,"Sales_Amount, Order_ID",Measures average customer transaction value.
7,Sales,Average Selling Price,Average realized selling price per unit.,Total Revenue / Units Sold,sales,"Sales_Amount, Quantity",Measures average realized unit price.
8,Discount,Average Discount %,Average percentage discount applied to sales t...,AVG(Discount_Percent),sales,Discount_Percent,Measures overall discounting behavior.
9,Discount,Discount Amount,Total monetary value given as discounts.,SUM(Gross_Sales - Sales_Amount),sales,"Gross_Sales, Sales_Amount",Measures revenue sacrificed through discounts.
10,Discount,Discount Impact on Profit,Relationship between discount levels and resul...,Compare Profit / Margin across discount bands.,sales,"Discount_Percent, Profit",Identifies whether higher discounts improve or...
11,Customer,Unique Customers,Number of distinct customers who placed orders.,COUNT(DISTINCT Customer_ID),sales,Customer_ID,Measures customer reach.
12,Customer,Revenue per Customer,Average revenue generated per customer.,Total Revenue / Unique Customers,sales,"Sales_Amount, Customer_ID",Measures customer value.
13,Customer,Repeat Customers,Customers who placed more than one order.,COUNT(Customer_ID where Order_Count > 1),sales,"Customer_ID, Order_ID",Measures customer retention behavior.
14,Customer,One-Time Customers,Customers who placed exactly one order.,COUNT(Customer_ID where Order_Count = 1),sales,"Customer_ID, Order_ID",Identifies customers with limited engagement.
15,Product,Product Revenue,Revenue generated by each product.,SUM(Sales_Amount) by Product_ID,sales,"Product_ID, Sales_Amount",Identifies revenue-driving products.
16,Product,Product Profit,Profit generated by each product.,SUM(Profit) by Product_ID,sales,"Product_ID, Profit",Identifies profitable products.
17,Product,Product Margin %,Profitability percentage for each product.,Product Profit / Product Revenue * 100,sales,"Product_ID, Profit, Sales_Amount",Compares product profitability.
18,Regional,Regional Revenue,Revenue generated by each region.,SUM(Sales_Amount) by Region_ID,sales,"Region_ID, Sales_Amount",Measures regional sales performance.
19,Regional,Regional Profit,Profit generated by each region.,SUM(Profit) by Region_ID,sales,"Region_ID, Profit",Measures regional profitability.
20,Regional,Target Achievement %,Percentage of target revenue achieved.,Actual Revenue / Target Revenue * 100,sales + target,Sales_Amount + Target,Measures performance against business targets.
21,Return,Valid Return Quantity,Quantity returned from records classified as v...,SUM(Analytical_Return_Quantity),return,Analytical_Return_Quantity,Measures valid returned units.
22,Return,Return Rate %,Percentage of sold units that were validly ret...,Valid Returned Quantity / Units Sold * 100,return + sales,Analytical_Return_Quantity + Quantity,Measures product return risk.
23,Return,Refund Amount,Total refund value associated with returns.,SUM(Analytical_Refund_Amount),return,Analytical_Refund_Amount,Measures financial impact of returns.
24,Time,Monthly Revenue,Revenue generated during each month.,SUM(Sales_Amount) by Year and Month,sales,"Sales_Amount, Year, Month",Tracks revenue trends.
25,Time,MoM Revenue Growth %,Percentage change in revenue compared with the...,(Current Revenue - Previous Revenue) / Previou...,sales,"Sales_Amount, Year, Month",Measures short-term growth.
26,Time,YoY Revenue Growth %,Percentage change in revenue compared with the...,(Current Revenue - Previous Year Revenue) / Pr...,sales,"Sales_Amount, Year, Month",Measures year-over-year growth.

In [34]:
# ============================================================
# SAVE KPI SPECIFICATION
# ============================================================

kpi_path = cleaned_path / "kpi_specification.csv"

kpi_spec_df.to_csv(kpi_path, index=False)

print(f"KPI specification saved to:")
print(kpi_path)

KPI specification saved to:
C:\Users\shubh\Desktop\AI_Sales_Intelligence\data\cleaned\kpi_specification.csv

SQL Database Setup

In [35]:
# ============================================================
# SQL DATABASE SETUP
# AI Sales Intelligence Project
# ============================================================

import sqlite3
from pathlib import Path
import pandas as pd

# Project paths
project_path = Path(r"C:\Users\shubh\Desktop\AI_Sales_Intelligence")
cleaned_path = project_path / "data" / "cleaned"
database_path = project_path / "data" / "sales_intelligence.db"

# ------------------------------------------------------------
# Load analytical model tables
# ------------------------------------------------------------

sales_sql = pd.read_csv(cleaned_path / "sales_model.csv")
return_sql = pd.read_csv(cleaned_path / "return_model.csv")
customer_sql = pd.read_csv(cleaned_path / "customer_model.csv")
product_sql = pd.read_csv(cleaned_path / "product_model.csv")
date_sql = pd.read_csv(cleaned_path / "date_model.csv")
region_sql = pd.read_csv(cleaned_path / "region_model.csv")
target_sql = pd.read_csv(cleaned_path / "target_model.csv")

# Convert date columns
sales_sql["Order_Date"] = pd.to_datetime(sales_sql["Order_Date"])
return_sql["Return_Date"] = pd.to_datetime(return_sql["Return_Date"])
date_sql["Date"] = pd.to_datetime(date_sql["Date"])

# ------------------------------------------------------------
# Create SQLite connection
# ------------------------------------------------------------

conn = sqlite3.connect(database_path)

# ------------------------------------------------------------
# Load tables into SQLite
# ------------------------------------------------------------

sales_sql.to_sql("sales", conn, if_exists="replace", index=False)
return_sql.to_sql("return", conn, if_exists="replace", index=False)
customer_sql.to_sql("customer", conn, if_exists="replace", index=False)
product_sql.to_sql("product", conn, if_exists="replace", index=False)
date_sql.to_sql("date", conn, if_exists="replace", index=False)
region_sql.to_sql("region", conn, if_exists="replace", index=False)
target_sql.to_sql("target", conn, if_exists="replace", index=False)

print("SQL database created successfully.")
print(f"Database: {database_path}")

# ------------------------------------------------------------
# Verify table row counts
# ------------------------------------------------------------

tables = [
    "sales",
    "return",
    "customer",
    "product",
    "date",
    "region",
    "target"
]

for table in tables:
    count = pd.read_sql_query(
        f'SELECT COUNT(*) AS row_count FROM "{table}"',
        conn
    ).iloc[0, 0]

    print(f"{table:10} → {count:,} rows")

SQL database created successfully.
Database: C:\Users\shubh\Desktop\AI_Sales_Intelligence\data\sales_intelligence.db
sales      → 74,920 rows
return     → 4,500 rows
customer   → 6,000 rows
product    → 180 rows
date       → 926 rows
region     → 25 rows
target     → 1,500 rows

In [36]:
# ============================================================
# SQL KPI 1 — OVERALL SALES PERFORMANCE
# ============================================================

sales_kpi_query = """
SELECT
    SUM(Sales_Amount) AS Total_Revenue,
    SUM(Cost_Amount) AS Total_Cost,
    SUM(Profit) AS Total_Profit,
    COUNT(DISTINCT Order_ID) AS Total_Orders,
    SUM(Quantity) AS Units_Sold,

    ROUND(
        SUM(Profit) * 100.0 / NULLIF(SUM(Sales_Amount), 0),
        2
    ) AS Profit_Margin_Percent,

    ROUND(
        SUM(Sales_Amount) * 1.0 /
        NULLIF(COUNT(DISTINCT Order_ID), 0),
        2
    ) AS Average_Order_Value,

    ROUND(
        SUM(Sales_Amount) * 1.0 /
        NULLIF(SUM(Quantity), 0),
        2
    ) AS Average_Selling_Price

FROM sales;
"""

sales_kpi = pd.read_sql_query(sales_kpi_query, conn)

display(sales_kpi)

,Total_Revenue,Total_Cost,Total_Profit,Total_Orders,Units_Sold,Profit_Margin_Percent,Average_Order_Value,Average_Selling_Price
0,1.361625e+09,1.028040e+09,3.335848e+08,74920,177177,24.5,18174.39,7685.11

In [37]:
# ============================================================
# SQL KPI 2 — MONTHLY SALES PERFORMANCE
# ============================================================

monthly_sales_query = """
SELECT
    Year,
    Month,
    Month_Name,

    SUM(Sales_Amount) AS Revenue,
    SUM(Cost_Amount) AS Cost,
    SUM(Profit) AS Profit,
    SUM(Quantity) AS Units_Sold,
    COUNT(DISTINCT Order_ID) AS Orders,

    ROUND(
        SUM(Profit) * 100.0 /
        NULLIF(SUM(Sales_Amount), 0),
        2
    ) AS Profit_Margin_Percent,

    ROUND(
        SUM(Sales_Amount) * 1.0 /
        NULLIF(COUNT(DISTINCT Order_ID), 0),
        2
    ) AS Average_Order_Value

FROM sales

GROUP BY
    Year,
    Month,
    Month_Name

ORDER BY
    Year,
    Month;
"""

monthly_sales = pd.read_sql_query(monthly_sales_query, conn)

display(monthly_sales.head(12))

,Year,Month,Month_Name,Revenue,Cost,Profit,Units_Sold,Orders,Profit_Margin_Percent,Average_Order_Value
0,2024,1,January,45928721.52,34838455.29,11090266.23,5980,2577,24.15,17822.55
1,2024,2,February,42757973.40,32221260.66,10536712.74,5459,2333,24.64,18327.46
2,2024,3,March,47293209.21,35837882.15,11455327.06,6185,2564,24.22,18445.09
3,2024,4,April,44229524.02,33815616.23,10413907.79,5808,2460,23.55,17979.48
4,2024,5,May,47834619.98,36080220.35,11754399.63,6038,2533,24.57,18884.57
5,2024,6,June,45395067.75,34272187.61,11122880.14,5845,2535,24.50,17907.32
6,2024,7,July,44538880.51,33871110.71,10667769.80,5915,2533,23.95,17583.45
7,2024,8,August,48460455.71,36476797.39,11983658.32,6196,2657,24.73,18238.79
8,2024,9,September,42664906.93,32111640.03,10553266.90,5530,2399,24.74,17784.45
9,2024,10,October,47151653.05,35680294.80,11471358.25,6176,2594,24.33,18177.20
10,2024,11,November,45848582.06,34482987.54,11365594.52,5923,2481,24.79,18479.88
11,2024,12,December,47163245.19,35632565.51,11530679.68,6195,2557,24.45,18444.76

In [38]:
# ============================================================
# SQL KPI 3 — CUSTOMER PERFORMANCE
# ============================================================

customer_performance_query = """
SELECT
    s.Customer_ID,

    c.Customer_Name,

    COUNT(DISTINCT s.Order_ID) AS Total_Orders,

    SUM(s.Quantity) AS Units_Sold,

    ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

    ROUND(SUM(s.Profit), 2) AS Profit,

    ROUND(
        SUM(s.Profit) * 100.0 /
        NULLIF(SUM(s.Sales_Amount), 0),
        2
    ) AS Profit_Margin_Percent,

    ROUND(
        SUM(s.Sales_Amount) * 1.0 /
        NULLIF(COUNT(DISTINCT s.Order_ID), 0),
        2
    ) AS Average_Order_Value

FROM sales s

LEFT JOIN customer c
    ON s.Customer_ID = c.Customer_ID

GROUP BY
    s.Customer_ID,
    c.Customer_Name

ORDER BY
    Revenue DESC;
"""

customer_performance = pd.read_sql_query(
    customer_performance_query,
    conn
)

display(customer_performance.head(20))

,Customer_ID,Customer_Name,Total_Orders,Units_Sold,Revenue,Profit,Profit_Margin_Percent,Average_Order_Value
0,CUST03370,Rohan Deshmukh,18,70,682579.18,215680.31,31.60,37921.07
1,CUST02369,Vivaan Sharma,26,65,656467.23,162061.30,24.69,25248.74
2,CUST02987,Amit Sharma,25,70,630590.67,114788.84,18.20,25223.63
3,CUST02176,Aarav Joshi,20,68,629769.19,147672.45,23.45,31488.46
4,CUST01171,Aarav Gupta,22,65,612137.04,151644.59,24.77,27824.41
5,CUST03244,Neha Mhaske,19,61,600454.29,155811.64,25.95,31602.86
6,CUST00947,Meera Deshmukh,21,53,592453.93,141721.69,23.92,28212.09
7,CUST05687,Amit Kumar,17,50,576083.55,134145.68,23.29,33887.27
8,CUST00992,Sneha Sharma,23,57,572539.20,141653.78,24.74,24893.01
9,CUST03036,Pooja Singh,21,58,569817.88,139394.75,24.46,27134.18
10,CUST03758,Sneha Mehta,21,53,555275.89,146087.08,26.31,26441.71
11,CUST05424,Aarav Joshi,16,58,544745.38,111299.86,20.43,34046.59
12,CUST00349,Amit Singh,20,65,543035.24,123959.62,22.83,27151.76
13,CUST02022,Neha Patil,23,61,541358.75,101352.10,18.72,23537.34
14,CUST05362,Rahul Singh,19,52,539423.17,140032.67,25.96,28390.69
15,CUST04253,Meera Joshi,20,60,538140.37,136884.12,25.44,26907.02
16,CUST01139,Karan Joshi,22,62,534445.22,116100.30,21.72,24292.96
17,CUST01817,Amit Patil,21,52,529895.41,118662.35,22.39,25233.11
18,CUST00778,Karan Shah,21,52,527205.51,146329.42,27.76,25105.02
19,CUST03037,Isha Sharma,17,58,521696.75,159437.07,30.56,30688.04

In [39]:
# ============================================================
# SQL KPI 4 — PRODUCT PERFORMANCE
# ============================================================

product_performance_query = """
SELECT
    s.Product_ID,

    p.Product_Name,
    p.Category,

    SUM(s.Quantity) AS Units_Sold,

    ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

    ROUND(SUM(s.Profit), 2) AS Profit,

    ROUND(
        SUM(s.Profit) * 100.0 /
        NULLIF(SUM(s.Sales_Amount), 0),
        2
    ) AS Profit_Margin_Percent,

    COUNT(DISTINCT s.Order_ID) AS Orders

FROM sales s

LEFT JOIN product p
    ON s.Product_ID = p.Product_ID

GROUP BY
    s.Product_ID,
    p.Product_Name,
    p.Category

ORDER BY
    Revenue DESC;
"""

product_performance = pd.read_sql_query(
    product_performance_query,
    conn
)

display(product_performance.head(20))

,Product_ID,Product_Name,Category,Units_Sold,Revenue,Profit,Profit_Margin_Percent,Orders
0,PROD0112,Beauty Fragrance 112,Beauty,1081,18542050.87,6856343.58,36.98,450
1,PROD0042,Home Decor 042,Home,981,17183296.19,5953161.35,34.65,413
2,PROD0028,Electronics Audio 028,Electronics,940,17153275.64,6028479.04,35.14,396
3,PROD0043,Home Appliances 043,Home,1030,16928062.10,5368732.60,31.71,435
4,PROD0054,Home Appliances 054,Home,1007,16407111.84,4701925.10,28.66,418
5,PROD0015,Electronics Accessories 015,Electronics,990,16277749.88,4558486.28,28.00,428
6,PROD0021,Electronics Laptops 021,Electronics,963,16141749.44,5571611.06,34.52,403
7,PROD0140,Beauty Haircare 140,Beauty,1054,15407580.42,5337643.34,34.64,441
8,PROD0089,Fashion Women 089,Fashion,925,15402986.30,4518872.05,29.34,410
9,PROD0164,Sports Equipment 164,Sports,1063,14899523.00,3809244.00,25.57,441
10,PROD0121,Beauty Fragrance 121,Beauty,1027,14663693.49,3773231.44,25.73,415
11,PROD0158,Sports Fitness 158,Sports,1001,14620445.39,3525201.23,24.11,422
12,PROD0036,Electronics Laptops 036,Electronics,1018,14510322.18,3814990.22,26.29,429
13,PROD0034,Electronics Smartphones 034,Electronics,1026,14497702.66,4824010.36,33.27,441
14,PROD0115,Beauty Skincare 115,Beauty,932,14377843.95,3539848.95,24.62,399
15,PROD0075,Fashion Men 075,Fashion,965,14326240.17,4250839.22,29.67,405
16,PROD0032,Electronics Accessories 032,Electronics,947,14251350.97,4299792.00,30.17,385
17,PROD0068,Home Appliances 068,Home,1120,14245044.18,1430967.38,10.05,451
18,PROD0119,Beauty Skincare 119,Beauty,991,14098989.80,4900577.35,34.76,416
19,PROD0098,Fashion Footwear 098,Fashion,986,13897143.59,4793208.39,34.49,425

In [50]:
# ============================================================
# SQL KPI 5 — REGIONAL PERFORMANCE
# ============================================================

regional_performance_query = """
SELECT
    s.Region_ID,

    r.Region,

    COUNT(DISTINCT s.Order_ID) AS Orders,

    COUNT(DISTINCT s.Customer_ID) AS Customers,

    SUM(s.Quantity) AS Units_Sold,

    ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

    ROUND(SUM(s.Profit), 2) AS Profit,

    ROUND(
        SUM(s.Profit) * 100.0 /
        NULLIF(SUM(s.Sales_Amount), 0),
        2
    ) AS Profit_Margin_Percent

FROM sales s

LEFT JOIN region r
    ON s.Region_ID = r.Region_ID

GROUP BY
    s.Region_ID,
    r.Region

ORDER BY
    Revenue DESC;
"""

regional_performance = pd.read_sql_query(
    regional_performance_query,
    conn
)

display(regional_performance)

,Region_ID,Region,Orders,Customers,Units_Sold,Revenue,Profit,Profit_Margin_Percent
0,R010,North,3423,270,8048,62018868.77,15081725.51,24.32
1,R016,South,3351,270,8002,60793443.84,15054323.08,24.76
2,R012,East,3176,252,7557,59016775.67,14394347.75,24.39
3,R013,East,3149,250,7466,57432530.12,13911127.14,24.22
4,R001,West,3120,251,7533,57291084.41,13873429.45,24.22
5,R019,South,3065,245,7284,56816977.30,13994283.62,24.63
6,R018,South,3106,249,7314,56736100.91,13922039.93,24.54
7,R007,North,3092,254,7413,56662601.89,13632532.88,24.06
8,R005,North,3021,241,7157,55801455.08,13592293.37,24.36
9,R009,North,3055,246,7265,55745634.78,13845945.45,24.84
10,R023,South,3061,244,7176,55028194.09,13502673.09,24.54
11,R025,Central,3076,247,7109,54432599.19,13382915.44,24.59
12,R017,South,3023,246,7115,53353217.01,12985975.51,24.34
13,R003,West,2940,231,6984,53307380.49,13173935.87,24.71
14,R015,South,2871,232,6794,53043517.74,13036433.45,24.58
15,R020,South,2886,229,6831,52908898.93,13037669.74,24.64
16,R022,South,2926,240,6839,52692788.45,13044708.33,24.76
17,R021,South,2866,227,6767,52461439.25,12877007.89,24.55
18,R002,West,2913,232,6827,52409297.51,12827894.61,24.48
19,R006,North,2830,224,6764,52337762.36,12711869.27,24.29
20,R011,North,2880,230,6808,52151407.41,12687508.55,24.33
21,R004,West,2900,235,6793,51950987.34,12957278.96,24.94
22,R024,Central,2932,240,6888,51678178.75,12659590.56,24.50
23,R008,North,2619,206,6207,48109034.60,11709190.29,24.34
24,R014,East,2639,209,6236,47444860.85,11688054.78,24.64

In [41]:
# ============================================================
# SQL KPI 6 — DISCOUNT VS PROFITABILITY
# ============================================================

discount_analysis_query = """
SELECT

    CASE
        WHEN Discount_Percent = 0 THEN '0%'
        WHEN Discount_Percent <= 5 THEN '1-5%'
        WHEN Discount_Percent <= 10 THEN '6-10%'
        WHEN Discount_Percent <= 15 THEN '11-15%'
        WHEN Discount_Percent <= 20 THEN '16-20%'
        ELSE '20%+'
    END AS Discount_Band,

    COUNT(*) AS Transactions,

    ROUND(SUM(Sales_Amount), 2) AS Revenue,

    ROUND(SUM(Profit), 2) AS Profit,

    ROUND(
        SUM(Profit) * 100.0 /
        NULLIF(SUM(Sales_Amount), 0),
        2
    ) AS Profit_Margin_Percent,

    ROUND(AVG(Discount_Percent), 2) AS Average_Discount

FROM sales

GROUP BY Discount_Band

ORDER BY
    MIN(Discount_Percent);
"""

discount_analysis = pd.read_sql_query(
    discount_analysis_query,
    conn
)

display(discount_analysis)

,Discount_Band,Transactions,Revenue,Profit,Profit_Margin_Percent,Average_Discount
0,0%,4950,1.008796e+08,3.173451e+07,31.46,0.00
1,1-5%,14017,2.720361e+08,7.981408e+07,29.34,2.87
2,6-10%,23464,4.339846e+08,1.119029e+08,25.79,7.57
3,11-15%,20660,3.636283e+08,7.934578e+07,21.82,12.31
4,16-20%,9372,1.539243e+08,2.657168e+07,17.26,17.04
5,20%+,2457,3.717219e+07,4.215770e+06,11.34,22.34

In [42]:
# ============================================================
# SQL KPI 7 — VALID RETURN ANALYSIS
# ============================================================

return_analysis_query = """
SELECT

    COUNT(*) AS Valid_Return_Records,

    SUM(Analytical_Return_Quantity) AS Valid_Return_Quantity,

    ROUND(
        SUM(Analytical_Refund_Amount),
        2
    ) AS Refund_Amount,

    ROUND(
        SUM(Analytical_Refund_Amount) /
        NULLIF(COUNT(*), 0),
        2
    ) AS Average_Refund_Amount

FROM return

WHERE Is_Valid_Return = 1;
"""

return_analysis = pd.read_sql_query(
    return_analysis_query,
    conn
)

display(return_analysis)

,Valid_Return_Records,Valid_Return_Quantity,Refund_Amount,Average_Refund_Amount
0,4247,4686,39550141.62,9312.49

In [43]:
# ============================================================
# SQL KPI 8 — RETURN RATE
# ============================================================

return_rate_query = """
WITH sales_units AS (

    SELECT
        SUM(Quantity) AS Units_Sold
    FROM sales

),

valid_returns AS (

    SELECT
        SUM(Analytical_Return_Quantity) AS Returned_Units
    FROM return
    WHERE Is_Valid_Return = 1

)

SELECT

    sales_units.Units_Sold,

    valid_returns.Returned_Units,

    ROUND(
        valid_returns.Returned_Units * 100.0 /
        NULLIF(sales_units.Units_Sold, 0),
        2
    ) AS Return_Rate_Percent

FROM sales_units
CROSS JOIN valid_returns;
"""

return_rate = pd.read_sql_query(
    return_rate_query,
    conn
)

display(return_rate)

   Units_Sold  Returned_Units  Return_Rate_Percent
0      177177            4686                 2.64

In [51]:
# ============================================================
# SAVE SQL ANALYTICS OUTPUTS
# ============================================================

sql_output_path = cleaned_path / "sql_outputs"

# Create output folder if it doesn't exist
sql_output_path.mkdir(parents=True, exist_ok=True)

outputs = {
    "sales_kpi.csv": sales_kpi,
    "monthly_sales.csv": monthly_sales,
    "customer_performance.csv": customer_performance,
    "product_performance.csv": product_performance,
    "regional_performance.csv": regional_performance,
    "discount_analysis.csv": discount_analysis,
    "return_analysis.csv": return_analysis,
    "return_rate.csv": return_rate
}

for filename, dataframe in outputs.items():
    dataframe.to_csv(
        sql_output_path / filename,
        index=False
    )
    print(f"Saved: {filename}")

print("\nAll SQL analytical outputs saved successfully.")
print(f"Output folder: {sql_output_path}")

Saved: sales_kpi.csv
Saved: monthly_sales.csv
Saved: customer_performance.csv
Saved: product_performance.csv
Saved: regional_performance.csv
Saved: discount_analysis.csv
Saved: return_analysis.csv
Saved: return_rate.csv

All SQL analytical outputs saved successfully.
Output folder: C:\Users\shubh\Desktop\AI_Sales_Intelligence\data\cleaned\sql_outputs

In [55]:
# ============================================
# ADVANCED SQL 1: MoM & YoY Revenue Growth
# Using LAG() Window Function
# ============================================

mom_yoy_query = """
WITH monthly_revenue AS (
    SELECT
        d.Year,
        d.Month_Number,
        d.Month_Name,

        ROUND(SUM(s.Sales_Amount), 2) AS Revenue

    FROM sales s

    LEFT JOIN date d
        ON DATE(s.Order_Date) = DATE(d.Date)

    GROUP BY
        d.Year,
        d.Month_Number,
        d.Month_Name
),

revenue_with_previous AS (
    SELECT
        Year,
        Month_Number,
        Month_Name,
        Revenue,

        -- Previous month's revenue
        LAG(Revenue) OVER (
            ORDER BY Year, Month_Number
        ) AS Previous_Month_Revenue,

        -- Same month in previous year
        LAG(Revenue, 12) OVER (
            ORDER BY Year, Month_Number
        ) AS Previous_Year_Revenue

    FROM monthly_revenue
)

SELECT
    Year,
    Month_Number,
    Month_Name,
    Revenue,

    ROUND(Previous_Month_Revenue, 2)
        AS Previous_Month_Revenue,

    ROUND(
        (Revenue - Previous_Month_Revenue) * 100.0
        / NULLIF(Previous_Month_Revenue, 0),
        2
    ) AS MoM_Growth_Percent,

    ROUND(Previous_Year_Revenue, 2)
        AS Previous_Year_Revenue,

    ROUND(
        (Revenue - Previous_Year_Revenue) * 100.0
        / NULLIF(Previous_Year_Revenue, 0),
        2
    ) AS YoY_Growth_Percent

FROM revenue_with_previous

ORDER BY
    Year,
    Month_Number;
"""

monthly_growth = pd.read_sql_query(
    mom_yoy_query,
    conn
)

display(monthly_growth)

,Year,Month_Number,Month_Name,Revenue,Previous_Month_Revenue,MoM_Growth_Percent,Previous_Year_Revenue,YoY_Growth_Percent
0,2024,1.0,January,45928721.52,NaN,NaN,NaN,NaN
1,2024,2.0,February,42757973.40,45928721.52,-6.90,NaN,NaN
2,2024,3.0,March,47293209.21,42757973.40,10.61,NaN,NaN
3,2024,4.0,April,44229524.02,47293209.21,-6.48,NaN,NaN
4,2024,5.0,May,47834619.98,44229524.02,8.15,NaN,NaN
5,2024,6.0,June,45395067.75,47834619.98,-5.10,NaN,NaN
6,2024,7.0,July,44538880.51,45395067.75,-1.89,NaN,NaN
7,2024,8.0,August,48460455.71,44538880.51,8.80,NaN,NaN
8,2024,9.0,September,42664906.93,48460455.71,-11.96,NaN,NaN
9,2024,10.0,October,47151653.05,42664906.93,10.52,NaN,NaN
10,2024,11.0,November,45848582.06,47151653.05,-2.76,NaN,NaN
11,2024,12.0,December,47163245.19,45848582.06,2.87,NaN,NaN
12,2025,1.0,January,47196919.38,47163245.19,0.07,45928721.52,2.76
13,2025,2.0,February,42175078.09,47196919.38,-10.64,42757973.40,-1.36
14,2025,3.0,March,44920726.16,42175078.09,6.51,47293209.21,-5.02
15,2025,4.0,April,42678296.19,44920726.16,-4.99,44229524.02,-3.51
16,2025,5.0,May,46038208.94,42678296.19,7.87,47834619.98,-3.76
17,2025,6.0,June,45201618.70,46038208.94,-1.82,45395067.75,-0.43
18,2025,7.0,July,45913674.74,45201618.70,1.58,44538880.51,3.09
19,2025,8.0,August,46927485.11,45913674.74,2.21,48460455.71,-3.16
20,2025,9.0,September,43899251.14,46927485.11,-6.45,42664906.93,2.89
21,2025,10.0,October,45585179.36,43899251.14,3.84,47151653.05,-3.32
22,2025,11.0,November,43337990.48,45585179.36,-4.93,45848582.06,-5.48
23,2025,12.0,December,47139270.74,43337990.48,8.77,47163245.19,-0.05
24,2026,1.0,January,46503689.37,47139270.74,-1.35,47196919.38,-1.47
25,2026,2.0,February,43268831.63,46503689.37,-6.96,42175078.09,2.59
26,2026,3.0,March,45608262.08,43268831.63,5.41,44920726.16,1.53
27,2026,4.0,April,41994344.40,45608262.08,-7.92,42678296.19,-1.60
28,2026,5.0,May,48674859.39,41994344.40,15.91,46038208.94,5.73
29,2026,6.0,June,45294511.51,48674859.39,-6.94,45201618.70,0.21

In [56]:
# Create advanced SQL output folder
advanced_sql_path = cleaned_path / "sql_outputs" / "advanced"
advanced_sql_path.mkdir(parents=True, exist_ok=True)

# Save MoM + YoY analysis
monthly_growth.to_csv(
    advanced_sql_path / "monthly_growth.csv",
    index=False
)

print("Saved: monthly_growth.csv")
print(f"Output folder: {advanced_sql_path}")

Saved: monthly_growth.csv
Output folder: C:\Users\shubh\Desktop\AI_Sales_Intelligence\data\cleaned\sql_outputs\advanced

In [57]:
# ============================================
# ADVANCED SQL 2: Product Ranking
# Using RANK() and ROW_NUMBER()
# ============================================

product_ranking_query = """
WITH product_performance AS (
    SELECT
        p.Product_ID,
        p.Product_Name,
        p.Category,

        SUM(s.Quantity) AS Units_Sold,

        ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

        ROUND(SUM(s.Profit), 2) AS Profit,

        ROUND(
            SUM(s.Profit) * 100.0 /
            NULLIF(SUM(s.Sales_Amount), 0),
            2
        ) AS Profit_Margin_Percent,

        COUNT(DISTINCT s.Order_ID) AS Orders

    FROM sales s

    LEFT JOIN product p
        ON s.Product_ID = p.Product_ID

    GROUP BY
        p.Product_ID,
        p.Product_Name,
        p.Category
),

ranked_products AS (
    SELECT
        Product_ID,
        Product_Name,
        Category,
        Units_Sold,
        Revenue,
        Profit,
        Profit_Margin_Percent,
        Orders,

        -- Ranking based on revenue
        RANK() OVER (
            ORDER BY Revenue DESC
        ) AS Revenue_Rank,

        -- Ranking based on profit
        RANK() OVER (
            ORDER BY Profit DESC
        ) AS Profit_Rank,

        -- Unique sequential ranking
        ROW_NUMBER() OVER (
            ORDER BY Revenue DESC
        ) AS Revenue_Row_Number

    FROM product_performance
)

SELECT *
FROM ranked_products
ORDER BY Revenue_Rank;
"""

product_ranking = pd.read_sql_query(
    product_ranking_query,
    conn
)

display(product_ranking)

,Product_ID,Product_Name,Category,Units_Sold,Revenue,Profit,Profit_Margin_Percent,Orders,Revenue_Rank,Profit_Rank,Revenue_Row_Number
0,PROD0112,Beauty Fragrance 112,Beauty,1081,18542050.87,6856343.58,36.98,450,1,1,1
1,PROD0042,Home Decor 042,Home,981,17183296.19,5953161.35,34.65,413,2,3,2
2,PROD0028,Electronics Audio 028,Electronics,940,17153275.64,6028479.04,35.14,396,3,2,3
3,PROD0043,Home Appliances 043,Home,1030,16928062.10,5368732.60,31.71,435,4,5,4
4,PROD0054,Home Appliances 054,Home,1007,16407111.84,4701925.10,28.66,418,5,11,5
...,...,...,...,...,...,...,...,...,...,...,...
175,PROD0039,Home Kitchen 039,Home,970,673892.31,112446.61,16.69,415,176,175,176
176,PROD0035,Electronics Smartphones 035,Electronics,1008,655142.68,97325.56,14.86,422,177,176,177
177,PROD0110,Beauty Skincare 110,Beauty,1008,410210.08,75755.68,18.47,440,178,178,178
178,PROD0012,Electronics Laptops 012,Electronics,1022,309532.23,80123.89,25.89,413,179,177,179
179,PROD0081,Fashion Men 081,Fashion,1004,231325.01,65976.25,28.52,426,180,179,180

In [58]:
product_ranking.to_csv(
    advanced_sql_path / "product_ranking.csv",
    index=False
)

print("Saved: product_ranking.csv")

Saved: product_ranking.csv

In [59]:
# ============================================
# ADVANCED SQL 3: Customer Ranking
# Using RANK(), ROW_NUMBER() and NTILE()
# ============================================

customer_ranking_query = """
WITH customer_performance AS (
    SELECT
        c.Customer_ID,
        c.Customer_Name,

        COUNT(DISTINCT s.Order_ID) AS Total_Orders,

        SUM(s.Quantity) AS Units_Sold,

        ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

        ROUND(SUM(s.Profit), 2) AS Profit,

        ROUND(
            SUM(s.Profit) * 100.0 /
            NULLIF(SUM(s.Sales_Amount), 0),
            2
        ) AS Profit_Margin_Percent

    FROM sales s

    LEFT JOIN customer c
        ON s.Customer_ID = c.Customer_ID

    GROUP BY
        c.Customer_ID,
        c.Customer_Name
),

ranked_customers AS (
    SELECT
        Customer_ID,
        Customer_Name,
        Total_Orders,
        Units_Sold,
        Revenue,
        Profit,
        Profit_Margin_Percent,

        -- Revenue ranking
        RANK() OVER (
            ORDER BY Revenue DESC
        ) AS Revenue_Rank,

        -- Profit ranking
        RANK() OVER (
            ORDER BY Profit DESC
        ) AS Profit_Rank,

        -- Unique customer ordering
        ROW_NUMBER() OVER (
            ORDER BY Revenue DESC
        ) AS Customer_Row_Number,

        -- Divide customers into 4 groups based on revenue
        NTILE(4) OVER (
            ORDER BY Revenue DESC
        ) AS Revenue_Quartile

    FROM customer_performance
)

SELECT
    *,
    CASE
        WHEN Revenue_Quartile = 1 THEN 'High Value'
        WHEN Revenue_Quartile = 2 THEN 'Medium-High Value'
        WHEN Revenue_Quartile = 3 THEN 'Medium-Low Value'
        WHEN Revenue_Quartile = 4 THEN 'Low Value'
    END AS Customer_Value_Segment

FROM ranked_customers

ORDER BY Revenue_Rank;
"""

customer_ranking = pd.read_sql_query(
    customer_ranking_query,
    conn
)

display(customer_ranking)

,Customer_ID,Customer_Name,Total_Orders,Units_Sold,Revenue,Profit,Profit_Margin_Percent,Revenue_Rank,Profit_Rank,Customer_Row_Number,Revenue_Quartile,Customer_Value_Segment
0,CUST03370,Rohan Deshmukh,18,70,682579.18,215680.31,31.60,1,1,1,1,High Value
1,CUST02369,Vivaan Sharma,26,65,656467.23,162061.30,24.69,2,2,2,1,High Value
2,CUST02987,Amit Sharma,25,70,630590.67,114788.84,18.20,3,121,3,1,High Value
3,CUST02176,Aarav Joshi,20,68,629769.19,147672.45,23.45,4,8,4,1,High Value
4,CUST01171,Aarav Gupta,22,65,612137.04,151644.59,24.77,5,6,5,1,High Value
...,...,...,...,...,...,...,...,...,...,...,...,...
5995,CUST04054,Vivaan Gupta,3,4,29726.08,9306.96,31.31,5996,5979,5996,4,Low Value
5996,CUST03449,Isha Deshmukh,3,3,25823.60,5632.51,21.81,5997,5995,5997,4,Low Value
5997,CUST05075,Sneha Joshi,4,11,25491.51,4954.61,19.44,5998,5996,5998,4,Low Value
5998,CUST05613,Rohan Shah,4,6,21742.57,3605.18,16.58,5999,5999,5999,4,Low Value
5999,CUST01391,Aarav Gupta,3,3,18419.30,4408.29,23.93,6000,5997,6000,4,Low Value

In [60]:
top_10_customers = customer_ranking.head(10)

display(top_10_customers)

,Customer_ID,Customer_Name,Total_Orders,Units_Sold,Revenue,Profit,Profit_Margin_Percent,Revenue_Rank,Profit_Rank,Customer_Row_Number,Revenue_Quartile,Customer_Value_Segment
0,CUST03370,Rohan Deshmukh,18,70,682579.18,215680.31,31.60,1,1,1,1,High Value
1,CUST02369,Vivaan Sharma,26,65,656467.23,162061.30,24.69,2,2,2,1,High Value
2,CUST02987,Amit Sharma,25,70,630590.67,114788.84,18.20,3,121,3,1,High Value
3,CUST02176,Aarav Joshi,20,68,629769.19,147672.45,23.45,4,8,4,1,High Value
4,CUST01171,Aarav Gupta,22,65,612137.04,151644.59,24.77,5,6,5,1,High Value
5,CUST03244,Neha Mhaske,19,61,600454.29,155811.64,25.95,6,5,6,1,High Value
6,CUST00947,Meera Deshmukh,21,53,592453.93,141721.69,23.92,7,13,7,1,High Value
7,CUST05687,Amit Kumar,17,50,576083.55,134145.68,23.29,8,30,8,1,High Value
8,CUST00992,Sneha Sharma,23,57,572539.20,141653.78,24.74,9,14,9,1,High Value
9,CUST03036,Pooja Singh,21,58,569817.88,139394.75,24.46,10,19,10,1,High Value

In [61]:
customer_segments = (
    customer_ranking
    .groupby("Customer_Value_Segment")
    .agg(
        Customers=("Customer_ID", "count"),
        Revenue=("Revenue", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Total_Orders", "sum")
    )
    .reset_index()
    .sort_values("Revenue", ascending=False)
)

display(customer_segments)

  Customer_Value_Segment  Customers       Revenue        Profit  Orders
0             High Value       1500  5.182176e+08  1.292165e+08   23687
2      Medium-High Value       1500  3.731349e+08  9.186565e+07   19924
3       Medium-Low Value       1500  2.860555e+08  6.881030e+07   17400
1              Low Value       1500  1.842170e+08  4.369234e+07   13909

In [62]:
customer_ranking.to_csv(
    advanced_sql_path / "customer_ranking.csv",
    index=False
)

customer_segments.to_csv(
    advanced_sql_path / "customer_segments.csv",
    index=False
)

print("Saved: customer_ranking.csv")
print("Saved: customer_segments.csv")

Saved: customer_ranking.csv
Saved: customer_segments.csv

In [66]:
# ============================================
# ADVANCED SQL 4: Target vs Actual Performance
# ============================================

target_vs_actual_query = """
WITH actual_sales AS (
    SELECT
        s.Region_ID,
        d.Year,
        d.Month_Number,

        ROUND(SUM(s.Sales_Amount), 2) AS Actual_Revenue,
        ROUND(SUM(s.Profit), 2) AS Actual_Profit,
        SUM(s.Quantity) AS Actual_Units,
        COUNT(DISTINCT s.Order_ID) AS Actual_Orders

    FROM sales s

    LEFT JOIN date d
        ON DATE(s.Order_Date) = DATE(d.Date)

    GROUP BY
        s.Region_ID,
        d.Year,
        d.Month_Number
),

target_data AS (
    SELECT
        t.Region_ID,
        d.Year,
        d.Month_Number,

        ROUND(SUM(t.Sales_Target), 2) AS Target_Revenue,
        ROUND(SUM(t.Profit_Target), 2) AS Target_Profit

    FROM target t

    LEFT JOIN date d
        ON DATE(t.Date) = DATE(d.Date)

    GROUP BY
        t.Region_ID,
        d.Year,
        d.Month_Number
)

SELECT
    a.Region_ID,
    r.Region,

    a.Year,
    a.Month_Number,

    a.Actual_Revenue,
    t.Target_Revenue,

    ROUND(
        a.Actual_Revenue - t.Target_Revenue,
        2
    ) AS Revenue_Variance,

    ROUND(
        a.Actual_Revenue * 100.0 /
        NULLIF(t.Target_Revenue, 0),
        2
    ) AS Revenue_Achievement_Percent,

    a.Actual_Profit,
    t.Target_Profit,

    ROUND(
        a.Actual_Profit - t.Target_Profit,
        2
    ) AS Profit_Variance,

    ROUND(
        a.Actual_Profit * 100.0 /
        NULLIF(t.Target_Profit, 0),
        2
    ) AS Profit_Achievement_Percent,

    a.Actual_Units,
    a.Actual_Orders

FROM actual_sales a

LEFT JOIN target_data t
    ON a.Region_ID = t.Region_ID
    AND a.Year = t.Year
    AND a.Month_Number = t.Month_Number

LEFT JOIN region r
    ON a.Region_ID = r.Region_ID

ORDER BY
    a.Year,
    a.Month_Number,
    a.Region_ID;
"""

target_vs_actual = pd.read_sql_query(
    target_vs_actual_query,
    conn
)

display(target_vs_actual)

,Region_ID,Region,Year,Month_Number,Actual_Revenue,Target_Revenue,Revenue_Variance,Revenue_Achievement_Percent,Actual_Profit,Target_Profit,Profit_Variance,Profit_Achievement_Percent,Actual_Units,Actual_Orders
0,R001,West,2024,1.0,2208071.37,NaN,NaN,NaN,534846.69,NaN,NaN,NaN,282,126
1,R002,West,2024,1.0,1652573.06,NaN,NaN,NaN,437169.08,NaN,NaN,NaN,211,97
2,R003,West,2024,1.0,1577638.32,1955192.10,-377553.78,80.69,393086.95,380654.99,12431.96,103.27,198,89
3,R004,West,2024,1.0,1763150.64,NaN,NaN,NaN,434552.48,NaN,NaN,NaN,217,92
4,R005,North,2024,1.0,1723186.32,NaN,NaN,NaN,424375.19,NaN,NaN,NaN,209,93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,R021,South,2026,6.0,1814917.67,2347340.14,-532422.47,77.32,440799.52,318045.26,122754.26,138.60,242,96
746,R022,South,2026,6.0,1879847.28,1587920.79,291926.49,118.38,465543.64,407686.68,57856.96,114.19,246,97
747,R023,South,2026,6.0,1861524.96,NaN,NaN,NaN,526091.08,NaN,NaN,NaN,243,108
748,R024,Central,2026,6.0,1645948.23,NaN,NaN,NaN,393388.48,NaN,NaN,NaN,239,112
749,R025,Central,2026,6.0,1706289.80,1413807.51,292482.29,120.69,427101.74,336461.85,90639.89,126.94,223,97

In [67]:
print("Rows:", len(target_vs_actual))
print("Columns:", list(target_vs_actual.columns))

Rows: 750
Columns: ['Region_ID', 'Region', 'Year', 'Month_Number', 'Actual_Revenue', 'Target_Revenue', 'Revenue_Variance', 'Revenue_Achievement_Percent', 'Actual_Profit', 'Target_Profit', 'Profit_Variance', 'Profit_Achievement_Percent', 'Actual_Units', 'Actual_Orders']

In [68]:
target_vs_actual[
    target_vs_actual["Target_Revenue"].isna()
].head(10)

,Region_ID,Region,Year,Month_Number,Actual_Revenue,Target_Revenue,Revenue_Variance,Revenue_Achievement_Percent,Actual_Profit,Target_Profit,Profit_Variance,Profit_Achievement_Percent,Actual_Units,Actual_Orders
0,R001,West,2024,1.0,2208071.37,NaN,NaN,NaN,534846.69,NaN,NaN,NaN,282,126
1,R002,West,2024,1.0,1652573.06,NaN,NaN,NaN,437169.08,NaN,NaN,NaN,211,97
3,R004,West,2024,1.0,1763150.64,NaN,NaN,NaN,434552.48,NaN,NaN,NaN,217,92
4,R005,North,2024,1.0,1723186.32,NaN,NaN,NaN,424375.19,NaN,NaN,NaN,209,93
5,R006,North,2024,1.0,1421753.07,NaN,NaN,NaN,352220.21,NaN,NaN,NaN,202,88
7,R008,North,2024,1.0,1695969.12,NaN,NaN,NaN,396904.09,NaN,NaN,NaN,207,96
8,R009,North,2024,1.0,1644011.46,NaN,NaN,NaN,393404.42,NaN,NaN,NaN,221,96
10,R011,North,2024,1.0,1847535.81,NaN,NaN,NaN,413977.50,NaN,NaN,NaN,255,109
12,R013,East,2024,1.0,2280209.92,NaN,NaN,NaN,572865.48,NaN,NaN,NaN,299,125
13,R014,East,2024,1.0,1747358.34,NaN,NaN,NaN,418823.63,NaN,NaN,NaN,211,90

In [69]:
# ============================================
# OVERALL REGIONAL TARGET PERFORMANCE
# ============================================

regional_target_summary = (
    target_vs_actual
    .groupby(
        ["Region_ID", "Region"],
        as_index=False
    )
    .agg(
        Actual_Revenue=("Actual_Revenue", "sum"),
        Target_Revenue=("Target_Revenue", "sum"),
        Actual_Profit=("Actual_Profit", "sum"),
        Target_Profit=("Target_Profit", "sum")
    )
)

regional_target_summary["Revenue_Variance"] = (
    regional_target_summary["Actual_Revenue"]
    - regional_target_summary["Target_Revenue"]
)

regional_target_summary["Revenue_Achievement_Percent"] = (
    regional_target_summary["Actual_Revenue"]
    * 100
    / regional_target_summary["Target_Revenue"]
)

regional_target_summary["Profit_Variance"] = (
    regional_target_summary["Actual_Profit"]
    - regional_target_summary["Target_Profit"]
)

regional_target_summary["Profit_Achievement_Percent"] = (
    regional_target_summary["Actual_Profit"]
    * 100
    / regional_target_summary["Target_Profit"]
)

regional_target_summary = (
    regional_target_summary
    .round(2)
    .sort_values(
        "Revenue_Achievement_Percent",
        ascending=False
    )
)

display(regional_target_summary)

,Region_ID,Region,Actual_Revenue,Target_Revenue,Actual_Profit,Target_Profit,Revenue_Variance,Revenue_Achievement_Percent,Profit_Variance,Profit_Achievement_Percent
19,R020,South,52908898.93,7591889.11,13037669.74,1513541.00,45317009.82,696.91,11524128.74,861.40
22,R023,South,55028194.09,8522390.56,13502673.09,1567346.34,46505803.53,645.69,11935326.75,861.50
2,R003,West,53307380.49,12508100.89,13173935.87,2374827.25,40799279.60,426.18,10799108.62,554.73
5,R006,North,52337762.36,14305303.74,12711869.27,2712651.35,38032458.62,365.86,9999217.92,468.61
12,R013,East,57432530.12,16239628.84,13911127.14,2827328.76,41192901.28,353.66,11083798.38,492.02
23,R024,Central,51678178.75,16795287.92,12659590.56,3102091.73,34882890.83,307.69,9557498.83,408.10
7,R008,North,48109034.60,17127667.43,11709190.29,3115014.33,30981367.17,280.88,8594175.96,375.90
14,R015,South,53043517.74,19627791.70,13036433.45,3929399.52,33415726.04,270.25,9107033.93,331.77
11,R012,East,59016775.67,23356418.85,14394347.75,4841427.56,35660356.82,252.68,9552920.19,297.32
24,R025,Central,54432599.19,22011158.52,13382915.44,4290588.94,32421440.67,247.30,9092326.50,311.91
17,R018,South,56736100.91,23645869.99,13922039.93,4431002.50,33090230.92,239.94,9491037.43,314.20
3,R004,West,51950987.34,22139275.31,12957278.96,4467581.53,29811712.03,234.66,8489697.43,290.03
1,R002,West,52409297.51,23087483.14,12827894.61,4571161.63,29321814.37,227.00,8256732.98,280.63
13,R014,East,47444860.85,23345613.00,11688054.78,4492100.04,24099247.85,203.23,7195954.74,260.19
9,R010,North,62018868.77,30804180.53,15081725.51,5416167.02,31214688.24,201.33,9665558.49,278.46
16,R017,South,53353217.01,26678450.97,12985975.51,4863218.66,26674766.04,199.99,8122756.85,267.02
20,R021,South,52461439.25,26844615.24,12877007.89,4573236.61,25616824.01,195.43,8303771.28,281.57
6,R007,North,56662601.89,29719788.18,13632532.88,5354397.22,26942813.71,190.66,8278135.66,254.60
15,R016,South,60793443.84,34056754.17,15054323.08,6572261.13,26736689.67,178.51,8482061.95,229.06
0,R001,West,57291084.41,32591078.26,13873429.45,5247537.51,24700006.15,175.79,8625891.94,264.38
10,R011,North,52151407.41,30909763.69,12687508.55,5336433.40,21241643.72,168.72,7351075.15,237.75
18,R019,South,56816977.30,35509292.58,13994283.62,6560215.13,21307684.72,160.01,7434068.49,213.32
8,R009,North,55745634.78,36582790.15,13845945.45,6438714.39,19162844.63,152.38,7407231.06,215.04
21,R022,South,52692788.45,43394484.51,13044708.33,8531558.96,9298303.94,121.43,4513149.37,152.90
4,R005,North,55801455.08,48622241.11,13592293.37,9198426.01,7179213.97,114.77,4393867.36,147.77

In [70]:
# ============================================
# SAVE TARGET ANALYSIS
# ============================================

target_vs_actual.to_csv(
    advanced_sql_path / "target_vs_actual.csv",
    index=False
)

regional_target_summary.to_csv(
    advanced_sql_path / "regional_target_summary.csv",
    index=False
)

print("Saved: target_vs_actual.csv")
print("Saved: regional_target_summary.csv")

Saved: target_vs_actual.csv
Saved: regional_target_summary.csv

In [71]:
# ============================================
# ADVANCED SQL 5: Regional Ranking
# ============================================

regional_ranking_query = """
WITH regional_sales AS (
    SELECT
        s.Region_ID,

        ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

        ROUND(SUM(s.Profit), 2) AS Profit,

        SUM(s.Quantity) AS Units_Sold,

        COUNT(DISTINCT s.Order_ID) AS Orders,

        COUNT(DISTINCT s.Customer_ID) AS Customers,

        ROUND(
            SUM(s.Profit) * 100.0 /
            NULLIF(SUM(s.Sales_Amount), 0),
            2
        ) AS Profit_Margin_Percent

    FROM sales s

    GROUP BY
        s.Region_ID
),

regional_targets AS (
    SELECT
        t.Region_ID,

        ROUND(SUM(t.Sales_Target), 2) AS Target_Revenue,

        ROUND(SUM(t.Profit_Target), 2) AS Target_Profit

    FROM target t

    GROUP BY
        t.Region_ID
),

regional_analysis AS (
    SELECT
        rs.Region_ID,
        r.Region,

        rs.Revenue,
        rt.Target_Revenue,

        ROUND(
            rs.Revenue - rt.Target_Revenue,
            2
        ) AS Revenue_Variance,

        ROUND(
            rs.Revenue * 100.0 /
            NULLIF(rt.Target_Revenue, 0),
            2
        ) AS Revenue_Achievement_Percent,

        rs.Profit,
        rt.Target_Profit,

        ROUND(
            rs.Profit - rt.Target_Profit,
            2
        ) AS Profit_Variance,

        ROUND(
            rs.Profit * 100.0 /
            NULLIF(rt.Target_Profit, 0),
            2
        ) AS Profit_Achievement_Percent,

        rs.Profit_Margin_Percent,
        rs.Units_Sold,
        rs.Orders,
        rs.Customers

    FROM regional_sales rs

    LEFT JOIN regional_targets rt
        ON rs.Region_ID = rt.Region_ID

    LEFT JOIN region r
        ON rs.Region_ID = r.Region_ID
)

SELECT
    *,

    RANK() OVER (
        ORDER BY Revenue DESC
    ) AS Revenue_Rank,

    RANK() OVER (
        ORDER BY Profit DESC
    ) AS Profit_Rank,

    RANK() OVER (
        ORDER BY Profit_Margin_Percent DESC
    ) AS Margin_Rank,

    RANK() OVER (
        ORDER BY Revenue_Achievement_Percent DESC
    ) AS Target_Achievement_Rank

FROM regional_analysis

ORDER BY Revenue_Rank;
"""

regional_ranking = pd.read_sql_query(
    regional_ranking_query,
    conn
)

display(regional_ranking)

,Region_ID,Region,Revenue,Target_Revenue,Revenue_Variance,Revenue_Achievement_Percent,Profit,Target_Profit,Profit_Variance,Profit_Achievement_Percent,Profit_Margin_Percent,Units_Sold,Orders,Customers,Revenue_Rank,Profit_Rank,Margin_Rank,Target_Achievement_Rank
0,R010,North,62018868.77,30804180.53,31214688.24,201.33,15081725.51,5416167.02,9665558.49,278.46,24.32,8048,3423,270,1,1,21,15
1,R016,South,60793443.84,34056754.17,26736689.67,178.51,15054323.08,6572261.13,8482061.95,229.06,24.76,8002,3351,270,2,2,3,19
2,R012,East,59016775.67,23356418.85,35660356.82,252.68,14394347.75,4841427.56,9552920.19,297.32,24.39,7557,3176,252,3,3,16,9
3,R013,East,57432530.12,16239628.84,41192901.28,353.66,13911127.14,2827328.76,11083798.38,492.02,24.22,7466,3149,250,4,6,23,5
4,R001,West,57291084.41,32591078.26,24700006.15,175.79,13873429.45,5247537.51,8625891.94,264.38,24.22,7533,3120,251,5,7,23,20
5,R019,South,56816977.30,35509292.58,21307684.72,160.01,13994283.62,6560215.13,7434068.49,213.32,24.63,7284,3065,245,6,4,8,22
6,R018,South,56736100.91,23645869.99,33090230.92,239.94,13922039.93,4431002.50,9491037.43,314.20,24.54,7314,3106,249,7,5,12,11
7,R007,North,56662601.89,29719788.18,26942813.71,190.66,13632532.88,5354397.22,8278135.66,254.60,24.06,7413,3092,254,8,9,25,18
8,R005,North,55801455.08,48622241.11,7179213.97,114.77,13592293.37,9198426.01,4393867.36,147.77,24.36,7157,3021,241,9,10,17,25
9,R009,North,55745634.78,36582790.15,19162844.63,152.38,13845945.45,6438714.39,7407231.06,215.04,24.84,7265,3055,246,10,8,2,23
10,R023,South,55028194.09,8522390.56,46505803.53,645.69,13502673.09,1567346.34,11935326.75,861.50,24.54,7176,3061,244,11,11,12,2
11,R025,Central,54432599.19,22011158.52,32421440.67,247.30,13382915.44,4290588.94,9092326.50,311.91,24.59,7109,3076,247,12,12,9,10
12,R017,South,53353217.01,26678450.97,26674766.04,199.99,12985975.51,4863218.66,8122756.85,267.02,24.34,7115,3023,246,13,17,18,16
13,R003,West,53307380.49,12508100.89,40799279.60,426.18,13173935.87,2374827.25,10799108.62,554.73,24.71,6984,2940,231,14,13,5,3
14,R015,South,53043517.74,19627791.70,33415726.04,270.25,13036433.45,3929399.52,9107033.93,331.77,24.58,6794,2871,232,15,16,10,8
15,R020,South,52908898.93,7591889.11,45317009.82,696.91,13037669.74,1513541.00,11524128.74,861.40,24.64,6831,2886,229,16,15,6,1
16,R022,South,52692788.45,43394484.51,9298303.94,121.43,13044708.33,8531558.96,4513149.37,152.90,24.76,6839,2926,240,17,14,3,24
17,R021,South,52461439.25,26844615.24,25616824.01,195.43,12877007.89,4573236.61,8303771.28,281.57,24.55,6767,2866,227,18,19,11,17
18,R002,West,52409297.51,23087483.14,29321814.37,227.00,12827894.61,4571161.63,8256732.98,280.63,24.48,6827,2913,232,19,20,15,13
19,R006,North,52337762.36,14305303.74,38032458.62,365.86,12711869.27,2712651.35,9999217.92,468.61,24.29,6764,2830,224,20,21,22,4
20,R011,North,52151407.41,30909763.69,21241643.72,168.72,12687508.55,5336433.40,7351075.15,237.75,24.33,6808,2880,230,21,22,20,21
21,R004,West,51950987.34,22139275.31,29811712.03,234.66,12957278.96,4467581.53,8489697.43,290.03,24.94,6793,2900,235,22,18,1,12
22,R024,Central,51678178.75,16795287.92,34882890.83,307.69,12659590.56,3102091.73,9557498.83,408.10,24.50,6888,2932,240,23,23,14,6
23,R008,North,48109034.60,17127667.43,30981367.17,280.88,11709190.29,3115014.33,8594175.96,375.90,24.34,6207,2619,206,24,24,18,7
24,R014,East,47444860.85,23345613.00,24099247.85,203.23,11688054.78,4492100.04,7195954.74,260.19,24.64,6236,2639,209,25,25,6,14

In [72]:
regional_ranking.to_csv(
    advanced_sql_path / "regional_ranking.csv",
    index=False
)

print("Saved: regional_ranking.csv")

Saved: regional_ranking.csv

In [73]:
# ============================================
# ADVANCED SQL 6: TOP & BOTTOM PRODUCT ANALYSIS
# ============================================

top_bottom_products_query = """
WITH product_performance AS (
    SELECT
        p.Product_ID,
        p.Product_Name,
        p.Category,

        SUM(s.Quantity) AS Units_Sold,

        ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

        ROUND(SUM(s.Profit), 2) AS Profit,

        ROUND(
            SUM(s.Profit) * 100.0 /
            NULLIF(SUM(s.Sales_Amount), 0),
            2
        ) AS Profit_Margin_Percent,

        COUNT(DISTINCT s.Order_ID) AS Orders

    FROM sales s

    LEFT JOIN product p
        ON s.Product_ID = p.Product_ID

    GROUP BY
        p.Product_ID,
        p.Product_Name,
        p.Category
),

ranked_products AS (
    SELECT
        *,

        RANK() OVER (
            ORDER BY Revenue DESC
        ) AS Revenue_Rank,

        RANK() OVER (
            ORDER BY Profit DESC
        ) AS Profit_Rank,

        RANK() OVER (
            ORDER BY Profit_Margin_Percent DESC
        ) AS Margin_Rank

    FROM product_performance
),

benchmarks AS (
    SELECT
        AVG(Revenue) AS Average_Revenue,
        AVG(Profit_Margin_Percent) AS Average_Margin
    FROM product_performance
)

SELECT
    rp.Product_ID,
    rp.Product_Name,
    rp.Category,
    rp.Units_Sold,
    rp.Orders,
    rp.Revenue,
    rp.Profit,
    rp.Profit_Margin_Percent,

    rp.Revenue_Rank,
    rp.Profit_Rank,
    rp.Margin_Rank,

    CASE
        WHEN rp.Revenue_Rank <= 10
            THEN 'Top 10 Revenue'

        WHEN rp.Revenue_Rank >= (
            SELECT MAX(Revenue_Rank)
            FROM ranked_products
        ) - 9
            THEN 'Bottom 10 Revenue'

        ELSE 'Middle'
    END AS Revenue_Performance,

    CASE
        WHEN rp.Revenue > b.Average_Revenue
             AND rp.Profit_Margin_Percent < b.Average_Margin
            THEN 'High Revenue - Low Margin'

        WHEN rp.Revenue < b.Average_Revenue
             AND rp.Profit_Margin_Percent > b.Average_Margin
            THEN 'Low Revenue - High Margin'

        WHEN rp.Revenue > b.Average_Revenue
             AND rp.Profit_Margin_Percent > b.Average_Margin
            THEN 'High Revenue - High Margin'

        ELSE 'Other'
    END AS Business_Performance_Type

FROM ranked_products rp

CROSS JOIN benchmarks b

ORDER BY
    rp.Revenue_Rank;
"""

top_bottom_products = pd.read_sql_query(
    top_bottom_products_query,
    conn
)

display(top_bottom_products)

,Product_ID,Product_Name,Category,Units_Sold,Orders,Revenue,Profit,Profit_Margin_Percent,Revenue_Rank,Profit_Rank,Margin_Rank,Revenue_Performance,Business_Performance_Type
0,PROD0112,Beauty Fragrance 112,Beauty,1081,450,18542050.87,6856343.58,36.98,1,1,1,Top 10 Revenue,High Revenue - High Margin
1,PROD0042,Home Decor 042,Home,981,413,17183296.19,5953161.35,34.65,2,3,22,Top 10 Revenue,High Revenue - High Margin
2,PROD0028,Electronics Audio 028,Electronics,940,396,17153275.64,6028479.04,35.14,3,2,15,Top 10 Revenue,High Revenue - High Margin
3,PROD0043,Home Appliances 043,Home,1030,435,16928062.10,5368732.60,31.71,4,5,43,Top 10 Revenue,High Revenue - High Margin
4,PROD0054,Home Appliances 054,Home,1007,418,16407111.84,4701925.10,28.66,5,11,67,Top 10 Revenue,High Revenue - High Margin
...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,PROD0039,Home Kitchen 039,Home,970,415,673892.31,112446.61,16.69,176,175,130,Bottom 10 Revenue,Other
176,PROD0035,Electronics Smartphones 035,Electronics,1008,422,655142.68,97325.56,14.86,177,176,142,Bottom 10 Revenue,Other
177,PROD0110,Beauty Skincare 110,Beauty,1008,440,410210.08,75755.68,18.47,178,178,119,Bottom 10 Revenue,Other
178,PROD0012,Electronics Laptops 012,Electronics,1022,413,309532.23,80123.89,25.89,179,177,77,Bottom 10 Revenue,Low Revenue - High Margin
179,PROD0081,Fashion Men 081,Fashion,1004,426,231325.01,65976.25,28.52,180,179,68,Bottom 10 Revenue,Low Revenue - High Margin

In [74]:
business_performance_summary = (
    top_bottom_products
    .groupby("Business_Performance_Type")
    .agg(
        Products=("Product_ID", "count"),
        Revenue=("Revenue", "sum"),
        Profit=("Profit", "sum"),
        Units_Sold=("Units_Sold", "sum")
    )
    .reset_index()
    .sort_values("Revenue", ascending=False)
)

display(business_performance_summary)

,Business_Performance_Type,Products,Revenue,Profit,Units_Sold
0,High Revenue - High Margin,46,5.827501e+08,1.810617e+08,45599
1,High Revenue - Low Margin,35,3.866120e+08,6.326962e+07,34133
2,Low Revenue - High Margin,49,2.053312e+08,6.225695e+07,47945
3,Other,50,1.869317e+08,2.699646e+07,49500

In [75]:
top_10_products = (
    top_bottom_products
    .sort_values("Revenue_Rank")
    .head(10)
)

display(top_10_products)

,Product_ID,Product_Name,Category,Units_Sold,Orders,Revenue,Profit,Profit_Margin_Percent,Revenue_Rank,Profit_Rank,Margin_Rank,Revenue_Performance,Business_Performance_Type
0,PROD0112,Beauty Fragrance 112,Beauty,1081,450,18542050.87,6856343.58,36.98,1,1,1,Top 10 Revenue,High Revenue - High Margin
1,PROD0042,Home Decor 042,Home,981,413,17183296.19,5953161.35,34.65,2,3,22,Top 10 Revenue,High Revenue - High Margin
2,PROD0028,Electronics Audio 028,Electronics,940,396,17153275.64,6028479.04,35.14,3,2,15,Top 10 Revenue,High Revenue - High Margin
3,PROD0043,Home Appliances 043,Home,1030,435,16928062.10,5368732.60,31.71,4,5,43,Top 10 Revenue,High Revenue - High Margin
4,PROD0054,Home Appliances 054,Home,1007,418,16407111.84,4701925.10,28.66,5,11,67,Top 10 Revenue,High Revenue - High Margin
5,PROD0015,Electronics Accessories 015,Electronics,990,428,16277749.88,4558486.28,28.00,6,13,70,Top 10 Revenue,High Revenue - High Margin
6,PROD0021,Electronics Laptops 021,Electronics,963,403,16141749.44,5571611.06,34.52,7,4,25,Top 10 Revenue,High Revenue - High Margin
7,PROD0140,Beauty Haircare 140,Beauty,1054,441,15407580.42,5337643.34,34.64,8,6,23,Top 10 Revenue,High Revenue - High Margin
8,PROD0089,Fashion Women 089,Fashion,925,410,15402986.30,4518872.05,29.34,9,14,61,Top 10 Revenue,High Revenue - High Margin
9,PROD0164,Sports Equipment 164,Sports,1063,441,14899523.00,3809244.00,25.57,10,24,81,Top 10 Revenue,High Revenue - High Margin

In [76]:
bottom_10_products = (
    top_bottom_products
    .sort_values("Revenue", ascending=True)
    .head(10)
)

display(bottom_10_products)

,Product_ID,Product_Name,Category,Units_Sold,Orders,Revenue,Profit,Profit_Margin_Percent,Revenue_Rank,Profit_Rank,Margin_Rank,Revenue_Performance,Business_Performance_Type
179,PROD0081,Fashion Men 081,Fashion,1004,426,231325.01,65976.25,28.52,180,179,68,Bottom 10 Revenue,Low Revenue - High Margin
178,PROD0012,Electronics Laptops 012,Electronics,1022,413,309532.23,80123.89,25.89,179,177,77,Bottom 10 Revenue,Low Revenue - High Margin
177,PROD0110,Beauty Skincare 110,Beauty,1008,440,410210.08,75755.68,18.47,178,178,119,Bottom 10 Revenue,Other
176,PROD0035,Electronics Smartphones 035,Electronics,1008,422,655142.68,97325.56,14.86,177,176,142,Bottom 10 Revenue,Other
175,PROD0039,Home Kitchen 039,Home,970,415,673892.31,112446.61,16.69,176,175,130,Bottom 10 Revenue,Other
174,PROD0055,Home Appliances 055,Home,946,394,720259.85,257609.09,35.77,175,164,11,Bottom 10 Revenue,Low Revenue - High Margin
173,PROD0145,Sports Sportswear 145,Sports,902,391,844978.11,188267.99,22.28,174,168,102,Bottom 10 Revenue,Other
172,PROD0156,Sports Fitness 156,Sports,1073,462,871489.51,62747.95,7.20,173,180,180,Bottom 10 Revenue,Other
171,PROD0077,Fashion Women 077,Fashion,943,419,877578.62,306658.13,34.94,172,162,16,Bottom 10 Revenue,Low Revenue - High Margin
170,PROD0141,Beauty Fragrance 141,Beauty,889,370,1016897.57,169324.97,16.65,171,171,131,Bottom 10 Revenue,Other

In [77]:
# ============================================
# ADVANCED SQL 7: CUSTOMER REVENUE CONCENTRATION
# ============================================

customer_concentration_query = """
WITH customer_sales AS (
    SELECT
        c.Customer_ID,
        c.Customer_Name,

        COUNT(DISTINCT s.Order_ID) AS Total_Orders,

        SUM(s.Quantity) AS Units_Sold,

        ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

        ROUND(SUM(s.Profit), 2) AS Profit

    FROM sales s

    LEFT JOIN customer c
        ON s.Customer_ID = c.Customer_ID

    GROUP BY
        c.Customer_ID,
        c.Customer_Name
),

customer_metrics AS (
    SELECT
        *,

        RANK() OVER (
            ORDER BY Revenue DESC
        ) AS Revenue_Rank,

        SUM(Revenue) OVER () AS Total_Revenue

    FROM customer_sales
),

concentration AS (
    SELECT
        *,

        ROUND(
            Revenue * 100.0 /
            NULLIF(Total_Revenue, 0),
            4
        ) AS Revenue_Contribution_Percent,

        ROUND(
            SUM(Revenue) OVER (
                ORDER BY Revenue DESC
                ROWS BETWEEN UNBOUNDED PRECEDING
                AND CURRENT ROW
            ) * 100.0 /
            NULLIF(Total_Revenue, 0),
            4
        ) AS Cumulative_Revenue_Percent

    FROM customer_metrics
)

SELECT
    Customer_ID,
    Customer_Name,
    Total_Orders,
    Units_Sold,
    Revenue,
    Profit,
    Revenue_Rank,
    Revenue_Contribution_Percent,
    Cumulative_Revenue_Percent,

    CASE
        WHEN Cumulative_Revenue_Percent <= 20
            THEN 'Top Revenue Contributors'

        WHEN Cumulative_Revenue_Percent <= 50
            THEN 'Core Revenue Contributors'

        WHEN Cumulative_Revenue_Percent <= 80
            THEN 'Moderate Contributors'

        ELSE 'Long Tail Customers'
    END AS Revenue_Concentration_Segment

FROM concentration

ORDER BY
    Revenue_Rank;
"""

customer_concentration = pd.read_sql_query(
    customer_concentration_query,
    conn
)

display(customer_concentration)

,Customer_ID,Customer_Name,Total_Orders,Units_Sold,Revenue,Profit,Revenue_Rank,Revenue_Contribution_Percent,Cumulative_Revenue_Percent,Revenue_Concentration_Segment
0,CUST03370,Rohan Deshmukh,18,70,682579.18,215680.31,1,0.0501,0.0501,Top Revenue Contributors
1,CUST02369,Vivaan Sharma,26,65,656467.23,162061.30,2,0.0482,0.0983,Top Revenue Contributors
2,CUST02987,Amit Sharma,25,70,630590.67,114788.84,3,0.0463,0.1447,Top Revenue Contributors
3,CUST02176,Aarav Joshi,20,68,629769.19,147672.45,4,0.0463,0.1909,Top Revenue Contributors
4,CUST01171,Aarav Gupta,22,65,612137.04,151644.59,5,0.0450,0.2359,Top Revenue Contributors
...,...,...,...,...,...,...,...,...,...,...
5995,CUST04054,Vivaan Gupta,3,4,29726.08,9306.96,5996,0.0022,99.9933,Long Tail Customers
5996,CUST03449,Isha Deshmukh,3,3,25823.60,5632.51,5997,0.0019,99.9952,Long Tail Customers
5997,CUST05075,Sneha Joshi,4,11,25491.51,4954.61,5998,0.0019,99.9971,Long Tail Customers
5998,CUST05613,Rohan Shah,4,6,21742.57,3605.18,5999,0.0016,99.9986,Long Tail Customers
5999,CUST01391,Aarav Gupta,3,3,18419.30,4408.29,6000,0.0014,100.0000,Long Tail Customers

In [78]:
top_customers = (
    customer_concentration
    .head(20)
)

display(top_customers)

,Customer_ID,Customer_Name,Total_Orders,Units_Sold,Revenue,Profit,Revenue_Rank,Revenue_Contribution_Percent,Cumulative_Revenue_Percent,Revenue_Concentration_Segment
0,CUST03370,Rohan Deshmukh,18,70,682579.18,215680.31,1,0.0501,0.0501,Top Revenue Contributors
1,CUST02369,Vivaan Sharma,26,65,656467.23,162061.30,2,0.0482,0.0983,Top Revenue Contributors
2,CUST02987,Amit Sharma,25,70,630590.67,114788.84,3,0.0463,0.1447,Top Revenue Contributors
3,CUST02176,Aarav Joshi,20,68,629769.19,147672.45,4,0.0463,0.1909,Top Revenue Contributors
4,CUST01171,Aarav Gupta,22,65,612137.04,151644.59,5,0.0450,0.2359,Top Revenue Contributors
5,CUST03244,Neha Mhaske,19,61,600454.29,155811.64,6,0.0441,0.2800,Top Revenue Contributors
6,CUST00947,Meera Deshmukh,21,53,592453.93,141721.69,7,0.0435,0.3235,Top Revenue Contributors
7,CUST05687,Amit Kumar,17,50,576083.55,134145.68,8,0.0423,0.3658,Top Revenue Contributors
8,CUST00992,Sneha Sharma,23,57,572539.20,141653.78,9,0.0420,0.4078,Top Revenue Contributors
9,CUST03036,Pooja Singh,21,58,569817.88,139394.75,10,0.0418,0.4497,Top Revenue Contributors
10,CUST03758,Sneha Mehta,21,53,555275.89,146087.08,11,0.0408,0.4905,Top Revenue Contributors
11,CUST05424,Aarav Joshi,16,58,544745.38,111299.86,12,0.0400,0.5305,Top Revenue Contributors
12,CUST00349,Amit Singh,20,65,543035.24,123959.62,13,0.0399,0.5703,Top Revenue Contributors
13,CUST02022,Neha Patil,23,61,541358.75,101352.10,14,0.0398,0.6101,Top Revenue Contributors
14,CUST05362,Rahul Singh,19,52,539423.17,140032.67,15,0.0396,0.6497,Top Revenue Contributors
15,CUST04253,Meera Joshi,20,60,538140.37,136884.12,16,0.0395,0.6892,Top Revenue Contributors
16,CUST01139,Karan Joshi,22,62,534445.22,116100.30,17,0.0393,0.7285,Top Revenue Contributors
17,CUST01817,Amit Patil,21,52,529895.41,118662.35,18,0.0389,0.7674,Top Revenue Contributors
18,CUST00778,Karan Shah,21,52,527205.51,146329.42,19,0.0387,0.8061,Top Revenue Contributors
19,CUST03037,Isha Sharma,17,58,521696.75,159437.07,20,0.0383,0.8444,Top Revenue Contributors

In [79]:
concentration_summary = (
    customer_concentration
    .groupby("Revenue_Concentration_Segment")
    .agg(
        Customers=("Customer_ID", "count"),
        Revenue=("Revenue", "sum"),
        Profit=("Profit", "sum")
    )
    .reset_index()
    .sort_values("Revenue", ascending=False)
)

display(concentration_summary)

  Revenue_Concentration_Segment  Customers       Revenue        Profit
0     Core Revenue Contributors       1415  4.086806e+08  1.012342e+08
2         Moderate Contributors       1876  4.085061e+08  9.947887e+07
1           Long Tail Customers       2014  2.724148e+08  6.464698e+07
3      Top Revenue Contributors        695  2.720235e+08  6.822471e+07

In [80]:
top_10_revenue_contribution = (
    customer_concentration
    .head(10)["Revenue"]
    .sum()
    /
    customer_concentration["Revenue"].sum()
    * 100
)

print(
    f"Top 10 customers contribute "
    f"{top_10_revenue_contribution:.2f}% of total revenue."
)

Top 10 customers contribute 0.45% of total revenue.

In [81]:
customer_concentration.to_csv(
    advanced_sql_path / "customer_revenue_concentration.csv",
    index=False
)

concentration_summary.to_csv(
    advanced_sql_path / "customer_concentration_summary.csv",
    index=False
)

print("Saved: customer_revenue_concentration.csv")
print("Saved: customer_concentration_summary.csv")

Saved: customer_revenue_concentration.csv
Saved: customer_concentration_summary.csv

In [82]:
# ============================================
# ADVANCED SQL 8: DISCOUNT EFFECTIVENESS
# ============================================

discount_effectiveness_query = """
WITH discount_analysis AS (
    SELECT
        CASE
            WHEN Discount_Percent = 0 THEN '0% Discount'
            WHEN Discount_Percent > 0
                 AND Discount_Percent <= 5 THEN '1-5% Discount'
            WHEN Discount_Percent > 5
                 AND Discount_Percent <= 10 THEN '6-10% Discount'
            WHEN Discount_Percent > 10
                 AND Discount_Percent <= 15 THEN '11-15% Discount'
            WHEN Discount_Percent > 15
                 AND Discount_Percent <= 20 THEN '16-20% Discount'
            ELSE '20%+ Discount'
        END AS Discount_Band,

        COUNT(DISTINCT Order_ID) AS Orders,

        SUM(Quantity) AS Units_Sold,

        ROUND(SUM(Sales_Amount), 2) AS Revenue,

        ROUND(SUM(Profit), 2) AS Profit,

        ROUND(AVG(Discount_Percent), 2) AS Average_Discount

    FROM sales

    GROUP BY
        CASE
            WHEN Discount_Percent = 0 THEN '0% Discount'
            WHEN Discount_Percent > 0
                 AND Discount_Percent <= 5 THEN '1-5% Discount'
            WHEN Discount_Percent > 5
                 AND Discount_Percent <= 10 THEN '6-10% Discount'
            WHEN Discount_Percent > 10
                 AND Discount_Percent <= 15 THEN '11-15% Discount'
            WHEN Discount_Percent > 15
                 AND Discount_Percent <= 20 THEN '16-20% Discount'
            ELSE '20%+ Discount'
        END
),

discount_metrics AS (
    SELECT
        *,

        ROUND(
            Profit * 100.0 /
            NULLIF(Revenue, 0),
            2
        ) AS Profit_Margin_Percent,

        ROUND(
            Revenue / NULLIF(Orders, 0),
            2
        ) AS Average_Order_Value

    FROM discount_analysis
)

SELECT
    Discount_Band,
    Orders,
    Units_Sold,
    Revenue,
    Profit,
    Profit_Margin_Percent,
    Average_Discount,
    Average_Order_Value

FROM discount_metrics

ORDER BY
    CASE Discount_Band
        WHEN '0% Discount' THEN 1
        WHEN '1-5% Discount' THEN 2
        WHEN '6-10% Discount' THEN 3
        WHEN '11-15% Discount' THEN 4
        WHEN '16-20% Discount' THEN 5
        WHEN '20%+ Discount' THEN 6
    END;
"""

discount_effectiveness = pd.read_sql_query(
    discount_effectiveness_query,
    conn
)

display(discount_effectiveness)

,Discount_Band,Orders,Units_Sold,Revenue,Profit,Profit_Margin_Percent,Average_Discount,Average_Order_Value
0,0% Discount,4950,11740,1.008796e+08,3.173451e+07,31.46,0.00,20379.71
1,1-5% Discount,14017,33208,2.720361e+08,7.981408e+07,29.34,2.87,19407.59
2,6-10% Discount,23464,55530,4.339846e+08,1.119029e+08,25.79,7.57,18495.76
3,11-15% Discount,20660,48888,3.636283e+08,7.934578e+07,21.82,12.31,17600.60
4,16-20% Discount,9372,22080,1.539243e+08,2.657168e+07,17.26,17.04,16423.85
5,20%+ Discount,2457,5731,3.717219e+07,4.215770e+06,11.34,22.34,15129.10

In [83]:
discount_effectiveness["Revenue_Contribution_Percent"] = (
    discount_effectiveness["Revenue"]
    / discount_effectiveness["Revenue"].sum()
    * 100
)

discount_effectiveness["Profit_Contribution_Percent"] = (
    discount_effectiveness["Profit"]
    / discount_effectiveness["Profit"].sum()
    * 100
)

discount_effectiveness = discount_effectiveness.round(2)

display(discount_effectiveness)

,Discount_Band,Orders,Units_Sold,Revenue,Profit,Profit_Margin_Percent,Average_Discount,Average_Order_Value,Revenue_Contribution_Percent,Profit_Contribution_Percent
0,0% Discount,4950,11740,1.008796e+08,3.173451e+07,31.46,0.00,20379.71,7.41,9.51
1,1-5% Discount,14017,33208,2.720361e+08,7.981408e+07,29.34,2.87,19407.59,19.98,23.93
2,6-10% Discount,23464,55530,4.339846e+08,1.119029e+08,25.79,7.57,18495.76,31.87,33.55
3,11-15% Discount,20660,48888,3.636283e+08,7.934578e+07,21.82,12.31,17600.60,26.71,23.79
4,16-20% Discount,9372,22080,1.539243e+08,2.657168e+07,17.26,17.04,16423.85,11.30,7.97
5,20%+ Discount,2457,5731,3.717219e+07,4.215770e+06,11.34,22.34,15129.10,2.73,1.26

In [84]:
best_discount_band = discount_effectiveness.loc[
    discount_effectiveness["Profit_Margin_Percent"].idxmax()
]

print("Highest-margin discount band:")
display(best_discount_band.to_frame().T)

Highest-margin discount band:

,Discount_Band,Orders,Units_Sold,Revenue,Profit,Profit_Margin_Percent,Average_Discount,Average_Order_Value,Revenue_Contribution_Percent,Profit_Contribution_Percent
0,0% Discount,4950,11740,100879550.82,31734512.87,31.46,0.0,20379.71,7.41,9.51

In [85]:
weakest_discount_band = discount_effectiveness.loc[
    discount_effectiveness["Profit_Margin_Percent"].idxmin()
]

print("Lowest-margin discount band:")
display(weakest_discount_band.to_frame().T)

Lowest-margin discount band:

,Discount_Band,Orders,Units_Sold,Revenue,Profit,Profit_Margin_Percent,Average_Discount,Average_Order_Value,Revenue_Contribution_Percent,Profit_Contribution_Percent
5,20%+ Discount,2457,5731,37172193.36,4215769.96,11.34,22.34,15129.1,2.73,1.26

In [86]:
discount_effectiveness.to_csv(
    advanced_sql_path / "discount_effectiveness.csv",
    index=False
)

print("Saved: discount_effectiveness.csv")
print(f"Output folder: {advanced_sql_path}")

Saved: discount_effectiveness.csv
Output folder: C:\Users\shubh\Desktop\AI_Sales_Intelligence\data\cleaned\sql_outputs\advanced

In [87]:
# ============================================
# ADVANCED SQL 9: RETURN & PRODUCT IMPACT
# ============================================

return_product_query = """
WITH product_sales AS (
    SELECT
        p.Product_ID,
        p.Product_Name,
        p.Category,

        SUM(s.Quantity) AS Units_Sold,

        ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

        ROUND(SUM(s.Profit), 2) AS Profit

    FROM sales s

    LEFT JOIN product p
        ON s.Product_ID = p.Product_ID

    GROUP BY
        p.Product_ID,
        p.Product_Name,
        p.Category
),

product_returns AS (
    SELECT
        Product_ID,

        SUM(
            CASE
                WHEN Is_Valid_Return = 1
                THEN Analytical_Return_Quantity
                ELSE 0
            END
        ) AS Returned_Units,

        ROUND(
            SUM(
                CASE
                    WHEN Is_Valid_Return = 1
                    THEN Analytical_Refund_Amount
                    ELSE 0
                END
            ),
            2
        ) AS Refund_Amount,

        COUNT(
            CASE
                WHEN Is_Valid_Return = 1
                THEN Return_ID
            END
        ) AS Valid_Return_Records

    FROM return

    GROUP BY
        Product_ID
)

SELECT
    ps.Product_ID,
    ps.Product_Name,
    ps.Category,

    ps.Units_Sold,
    ps.Revenue,
    ps.Profit,

    COALESCE(pr.Returned_Units, 0) AS Returned_Units,

    COALESCE(pr.Refund_Amount, 0) AS Refund_Amount,

    COALESCE(pr.Valid_Return_Records, 0)
        AS Valid_Return_Records,

    ROUND(
        COALESCE(pr.Returned_Units, 0) * 100.0 /
        NULLIF(ps.Units_Sold, 0),
        2
    ) AS Return_Rate_Percent,

    ROUND(
        COALESCE(pr.Refund_Amount, 0) * 100.0 /
        NULLIF(ps.Revenue, 0),
        2
    ) AS Refund_to_Revenue_Percent,

    ROUND(
        ps.Profit * 100.0 /
        NULLIF(ps.Revenue, 0),
        2
    ) AS Profit_Margin_Percent

FROM product_sales ps

LEFT JOIN product_returns pr
    ON ps.Product_ID = pr.Product_ID

ORDER BY
    Return_Rate_Percent DESC;
"""

return_product_analysis = pd.read_sql_query(
    return_product_query,
    conn
)

display(return_product_analysis)

,Product_ID,Product_Name,Category,Units_Sold,Revenue,Profit,Returned_Units,Refund_Amount,Valid_Return_Records,Return_Rate_Percent,Refund_to_Revenue_Percent,Profit_Margin_Percent
0,PROD0179,Sports Fitness 179,Sports,923,12656109.98,2153265.29,43,646353.21,41,4.66,5.11,17.01
1,PROD0040,Home Appliances 040,Home,900,5826478.67,1837921.67,38,270776.22,30,4.22,4.65,31.54
2,PROD0103,Fashion Accessories 103,Fashion,974,6503367.61,1235576.27,41,300963.37,36,4.21,4.63,19.00
3,PROD0001,Electronics Audio 001,Electronics,845,9204443.68,2280555.93,35,420045.50,31,4.14,4.56,24.78
4,PROD0154,Sports Outdoor 154,Sports,914,1965687.51,438640.29,36,85266.36,31,3.94,4.34,22.31
...,...,...,...,...,...,...,...,...,...,...,...,...
175,PROD0113,Beauty Haircare 113,Beauty,964,12612426.83,1429091.75,13,187527.34,13,1.35,1.49,11.33
176,PROD0145,Sports Sportswear 145,Sports,902,844978.11,188267.99,12,12354.36,12,1.33,1.46,22.28
177,PROD0174,Sports Outdoor 174,Sports,899,1912457.00,220494.05,12,27994.44,11,1.33,1.46,11.53
178,PROD0107,Fashion Women 107,Fashion,984,7326943.97,554878.85,11,89647.36,9,1.12,1.22,7.57
179,PROD0169,Sports Equipment 169,Sports,980,5674078.61,1872492.01,11,69903.68,10,1.12,1.23,33.00

In [88]:
highest_refund_products = (
    return_product_analysis
    .sort_values(
        "Refund_Amount",
        ascending=False
    )
    .head(10)
)

display(highest_refund_products)

,Product_ID,Product_Name,Category,Units_Sold,Revenue,Profit,Returned_Units,Refund_Amount,Valid_Return_Records,Return_Rate_Percent,Refund_to_Revenue_Percent,Profit_Margin_Percent
0,PROD0179,Sports Fitness 179,Sports,923,12656109.98,2153265.29,43,646353.21,41,4.66,5.11,17.01
5,PROD0032,Electronics Accessories 032,Electronics,947,14251350.97,4299792.00,37,613354.55,33,3.91,4.30,30.17
36,PROD0054,Home Appliances 054,Home,1007,16407111.84,4701925.10,32,574071.04,27,3.18,3.50,28.66
20,PROD0036,Electronics Laptops 036,Electronics,1018,14510322.18,3814990.22,35,545774.60,31,3.44,3.76,26.29
22,PROD0064,Home Appliances 064,Home,1055,13433507.92,2272061.57,36,504843.12,31,3.41,3.76,16.91
70,PROD0021,Electronics Laptops 021,Electronics,963,16141749.44,5571611.06,27,499496.22,24,2.80,3.09,34.52
28,PROD0098,Fashion Footwear 098,Fashion,986,13897143.59,4793208.39,32,496395.20,27,3.25,3.57,34.49
14,PROD0088,Fashion Accessories 088,Fashion,890,12659830.57,4676922.17,32,495023.04,28,3.60,3.91,36.94
12,PROD0172,Sports Sportswear 172,Sports,991,12276115.74,3847799.48,36,490033.80,31,3.63,3.99,31.34
10,PROD0070,Home Kitchen 070,Home,942,11807173.49,3822574.25,35,481962.60,29,3.72,4.08,32.38

In [89]:
overall_return_rate = (
    return_product_analysis["Returned_Units"].sum()
    /
    return_product_analysis["Units_Sold"].sum()
    * 100
)

return_product_analysis["Return_Risk"] = (
    return_product_analysis["Return_Rate_Percent"]
    .apply(
        lambda x:
        "High Return Risk"
        if x > overall_return_rate * 1.5
        else
        "Moderate Return Risk"
        if x > overall_return_rate
        else
        "Low Return Risk"
    )
)

display(
    return_product_analysis[
        [
            "Product_ID",
            "Product_Name",
            "Category",
            "Units_Sold",
            "Returned_Units",
            "Return_Rate_Percent",
            "Refund_Amount",
            "Return_Risk"
        ]
    ].sort_values(
        "Return_Rate_Percent",
        ascending=False
    )
)

,Product_ID,Product_Name,Category,Units_Sold,Returned_Units,Return_Rate_Percent,Refund_Amount,Return_Risk
0,PROD0179,Sports Fitness 179,Sports,923,43,4.66,646353.21,High Return Risk
1,PROD0040,Home Appliances 040,Home,900,38,4.22,270776.22,High Return Risk
2,PROD0103,Fashion Accessories 103,Fashion,974,41,4.21,300963.37,High Return Risk
3,PROD0001,Electronics Audio 001,Electronics,845,35,4.14,420045.50,High Return Risk
4,PROD0154,Sports Outdoor 154,Sports,914,36,3.94,85266.36,Moderate Return Risk
...,...,...,...,...,...,...,...,...
175,PROD0113,Beauty Haircare 113,Beauty,964,13,1.35,187527.34,Low Return Risk
176,PROD0145,Sports Sportswear 145,Sports,902,12,1.33,12354.36,Low Return Risk
177,PROD0174,Sports Outdoor 174,Sports,899,12,1.33,27994.44,Low Return Risk
178,PROD0107,Fashion Women 107,Fashion,984,11,1.12,89647.36,Low Return Risk
179,PROD0169,Sports Equipment 169,Sports,980,11,1.12,69903.68,Low Return Risk

In [90]:
return_risk_summary = (
    return_product_analysis
    .groupby("Return_Risk")
    .agg(
        Products=("Product_ID", "count"),
        Units_Sold=("Units_Sold", "sum"),
        Returned_Units=("Returned_Units", "sum"),
        Refund_Amount=("Refund_Amount", "sum"),
        Revenue=("Revenue", "sum"),
        Profit=("Profit", "sum")
    )
    .reset_index()
)

return_risk_summary["Return_Rate_Percent"] = (
    return_risk_summary["Returned_Units"]
    * 100
    /
    return_risk_summary["Units_Sold"]
)

return_risk_summary = return_risk_summary.round(2)

display(return_risk_summary)

,Return_Risk,Products,Units_Sold,Returned_Units,Refund_Amount,Revenue,Profit,Return_Rate_Percent
0,High Return Risk,4,3642,157,1638138.30,3.419040e+07,7.507319e+06,4.31
1,Low Return Risk,93,92330,1999,17583011.22,7.312002e+08,1.719493e+08,2.17
2,Moderate Return Risk,83,81205,2530,20328992.10,5.962344e+08,1.541281e+08,3.12

In [91]:
return_product_analysis.to_csv(
    advanced_sql_path / "return_product_analysis.csv",
    index=False
)

return_risk_summary.to_csv(
    advanced_sql_path / "return_risk_summary.csv",
    index=False
)

print("Saved: return_product_analysis.csv")
print("Saved: return_risk_summary.csv")
print(f"Output folder: {advanced_sql_path}")

Saved: return_product_analysis.csv
Saved: return_risk_summary.csv
Output folder: C:\Users\shubh\Desktop\AI_Sales_Intelligence\data\cleaned\sql_outputs\advanced

In [92]:
# ============================================
# ADVANCED SQL 10: MONTHLY BUSINESS PERFORMANCE
# ============================================

monthly_business_query = """
WITH monthly_performance AS (
    SELECT
        d.Year,
        d.Month_Number,
        d.Month_Name,

        SUM(s.Quantity) AS Units_Sold,

        COUNT(DISTINCT s.Order_ID) AS Orders,

        ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

        ROUND(SUM(s.Cost_Amount), 2) AS Cost,

        ROUND(SUM(s.Profit), 2) AS Profit

    FROM sales s

    LEFT JOIN date d
        ON DATE(s.Order_Date) = DATE(d.Date)

    GROUP BY
        d.Year,
        d.Month_Number,
        d.Month_Name
),

monthly_growth AS (
    SELECT
        *,

        LAG(Revenue) OVER (
            ORDER BY Year, Month_Number
        ) AS Previous_Month_Revenue,

        LAG(Profit) OVER (
            ORDER BY Year, Month_Number
        ) AS Previous_Month_Profit

    FROM monthly_performance
)

SELECT
    Year,
    Month_Number,
    Month_Name,

    Units_Sold,
    Orders,

    Revenue,
    Cost,
    Profit,

    ROUND(
        Profit * 100.0 /
        NULLIF(Revenue, 0),
        2
    ) AS Profit_Margin_Percent,

    ROUND(
        Revenue / NULLIF(Orders, 0),
        2
    ) AS Average_Order_Value,

    ROUND(Previous_Month_Revenue, 2)
        AS Previous_Month_Revenue,

    ROUND(
        (Revenue - Previous_Month_Revenue) * 100.0 /
        NULLIF(Previous_Month_Revenue, 0),
        2
    ) AS MoM_Revenue_Growth_Percent,

    ROUND(Previous_Month_Profit, 2)
        AS Previous_Month_Profit,

    ROUND(
        (Profit - Previous_Month_Profit) * 100.0 /
        NULLIF(Previous_Month_Profit, 0),
        2
    ) AS MoM_Profit_Growth_Percent

FROM monthly_growth

ORDER BY
    Year,
    Month_Number;
"""

monthly_business = pd.read_sql_query(
    monthly_business_query,
    conn
)

display(monthly_business)

,Year,Month_Number,Month_Name,Units_Sold,Orders,Revenue,Cost,Profit,Profit_Margin_Percent,Average_Order_Value,Previous_Month_Revenue,MoM_Revenue_Growth_Percent,Previous_Month_Profit,MoM_Profit_Growth_Percent
0,2024,1.0,January,5980,2577,45928721.52,34838455.29,11090266.23,24.15,17822.55,NaN,NaN,NaN,NaN
1,2024,2.0,February,5459,2333,42757973.40,32221260.66,10536712.74,24.64,18327.46,45928721.52,-6.90,11090266.23,-4.99
2,2024,3.0,March,6185,2564,47293209.21,35837882.15,11455327.06,24.22,18445.09,42757973.40,10.61,10536712.74,8.72
3,2024,4.0,April,5808,2460,44229524.02,33815616.23,10413907.79,23.55,17979.48,47293209.21,-6.48,11455327.06,-9.09
4,2024,5.0,May,6038,2533,47834619.98,36080220.35,11754399.63,24.57,18884.57,44229524.02,8.15,10413907.79,12.87
5,2024,6.0,June,5845,2535,45395067.75,34272187.61,11122880.14,24.50,17907.32,47834619.98,-5.10,11754399.63,-5.37
6,2024,7.0,July,5915,2533,44538880.51,33871110.71,10667769.80,23.95,17583.45,45395067.75,-1.89,11122880.14,-4.09
7,2024,8.0,August,6196,2657,48460455.71,36476797.39,11983658.32,24.73,18238.79,44538880.51,8.80,10667769.80,12.34
8,2024,9.0,September,5530,2399,42664906.93,32111640.03,10553266.90,24.74,17784.45,48460455.71,-11.96,11983658.32,-11.94
9,2024,10.0,October,6176,2594,47151653.05,35680294.80,11471358.25,24.33,18177.20,42664906.93,10.52,10553266.90,8.70
10,2024,11.0,November,5923,2481,45848582.06,34482987.54,11365594.52,24.79,18479.88,47151653.05,-2.76,11471358.25,-0.92
11,2024,12.0,December,6195,2557,47163245.19,35632565.51,11530679.68,24.45,18444.76,45848582.06,2.87,11365594.52,1.45
12,2025,1.0,January,6086,2575,47196919.38,35418600.46,11778318.92,24.96,18328.90,47163245.19,0.07,11530679.68,2.15
13,2025,2.0,February,5593,2337,42175078.09,31908052.57,10267025.52,24.34,18046.67,47196919.38,-10.64,11778318.92,-12.83
14,2025,3.0,March,5998,2491,44920726.16,33913689.70,11007036.46,24.50,18033.21,42175078.09,6.51,10267025.52,7.21
15,2025,4.0,April,5593,2398,42678296.19,32245185.52,10433110.67,24.45,17797.45,44920726.16,-4.99,11007036.46,-5.21
16,2025,5.0,May,6101,2587,46038208.94,34664565.28,11373643.66,24.70,17795.98,42678296.19,7.87,10433110.67,9.01
17,2025,6.0,June,5666,2423,45201618.70,33928798.87,11272819.83,24.94,18655.23,46038208.94,-1.82,11373643.66,-0.89
18,2025,7.0,July,5861,2531,45913674.74,34670568.69,11243106.05,24.49,18140.53,45201618.70,1.58,11272819.83,-0.26
19,2025,8.0,August,6156,2606,46927485.11,35412659.05,11514826.06,24.54,18007.48,45913674.74,2.21,11243106.05,2.42
20,2025,9.0,September,5787,2457,43899251.14,33051821.04,10847430.10,24.71,17867.01,46927485.11,-6.45,11514826.06,-5.80
21,2025,10.0,October,5979,2526,45585179.36,34657497.32,10927682.04,23.97,18046.39,43899251.14,3.84,10847430.10,0.74
22,2025,11.0,November,5746,2419,43337990.48,32797667.86,10540322.62,24.32,17915.66,45585179.36,-4.93,10927682.04,-3.54
23,2025,12.0,December,6069,2566,47139270.74,35332224.89,11807045.85,25.05,18370.72,43337990.48,8.77,10540322.62,12.02
24,2026,1.0,January,6228,2610,46503689.37,34982981.45,11520707.92,24.77,17817.51,47139270.74,-1.35,11807045.85,-2.43
25,2026,2.0,February,5497,2313,43268831.63,32508976.20,10759855.43,24.87,18706.80,46503689.37,-6.96,11520707.92,-6.60
26,2026,3.0,March,5999,2484,45608262.08,34484231.80,11124030.28,24.39,18360.81,43268831.63,5.41,10759855.43,3.38
27,2026,4.0,April,5484,2323,41994344.40,31731929.03,10262415.37,24.44,18077.63,45608262.08,-7.92,11124030.28,-7.75
28,2026,5.0,May,6193,2575,48674859.39,36883438.19,11791421.20,24.22,18902.86,41994344.40,15.91,10262415.37,14.90
29,2026,6.0,June,5891,2476,45294511.51,34126376.03,11168135.48,24.66,18293.42,48674859.39,-6.94,11791421.20,-5.29

In [93]:
best_revenue_months = (
    monthly_business
    .sort_values(
        "Revenue",
        ascending=False
    )
    .head(10)
)

display(best_revenue_months)

,Year,Month_Number,Month_Name,Units_Sold,Orders,Revenue,Cost,Profit,Profit_Margin_Percent,Average_Order_Value,Previous_Month_Revenue,MoM_Revenue_Growth_Percent,Previous_Month_Profit,MoM_Profit_Growth_Percent
28,2026,5.0,May,6193,2575,48674859.39,36883438.19,11791421.20,24.22,18902.86,41994344.40,15.91,10262415.37,14.90
7,2024,8.0,August,6196,2657,48460455.71,36476797.39,11983658.32,24.73,18238.79,44538880.51,8.80,10667769.80,12.34
4,2024,5.0,May,6038,2533,47834619.98,36080220.35,11754399.63,24.57,18884.57,44229524.02,8.15,10413907.79,12.87
2,2024,3.0,March,6185,2564,47293209.21,35837882.15,11455327.06,24.22,18445.09,42757973.40,10.61,10536712.74,8.72
12,2025,1.0,January,6086,2575,47196919.38,35418600.46,11778318.92,24.96,18328.90,47163245.19,0.07,11530679.68,2.15
11,2024,12.0,December,6195,2557,47163245.19,35632565.51,11530679.68,24.45,18444.76,45848582.06,2.87,11365594.52,1.45
9,2024,10.0,October,6176,2594,47151653.05,35680294.80,11471358.25,24.33,18177.20,42664906.93,10.52,10553266.90,8.70
23,2025,12.0,December,6069,2566,47139270.74,35332224.89,11807045.85,25.05,18370.72,43337990.48,8.77,10540322.62,12.02
19,2025,8.0,August,6156,2606,46927485.11,35412659.05,11514826.06,24.54,18007.48,45913674.74,2.21,11243106.05,2.42
24,2026,1.0,January,6228,2610,46503689.37,34982981.45,11520707.92,24.77,17817.51,47139270.74,-1.35,11807045.85,-2.43

In [94]:
best_profit_months = (
    monthly_business
    .sort_values(
        "Profit",
        ascending=False
    )
    .head(10)
)

display(best_profit_months)

,Year,Month_Number,Month_Name,Units_Sold,Orders,Revenue,Cost,Profit,Profit_Margin_Percent,Average_Order_Value,Previous_Month_Revenue,MoM_Revenue_Growth_Percent,Previous_Month_Profit,MoM_Profit_Growth_Percent
7,2024,8.0,August,6196,2657,48460455.71,36476797.39,11983658.32,24.73,18238.79,44538880.51,8.80,10667769.80,12.34
23,2025,12.0,December,6069,2566,47139270.74,35332224.89,11807045.85,25.05,18370.72,43337990.48,8.77,10540322.62,12.02
28,2026,5.0,May,6193,2575,48674859.39,36883438.19,11791421.20,24.22,18902.86,41994344.40,15.91,10262415.37,14.90
12,2025,1.0,January,6086,2575,47196919.38,35418600.46,11778318.92,24.96,18328.90,47163245.19,0.07,11530679.68,2.15
4,2024,5.0,May,6038,2533,47834619.98,36080220.35,11754399.63,24.57,18884.57,44229524.02,8.15,10413907.79,12.87
11,2024,12.0,December,6195,2557,47163245.19,35632565.51,11530679.68,24.45,18444.76,45848582.06,2.87,11365594.52,1.45
24,2026,1.0,January,6228,2610,46503689.37,34982981.45,11520707.92,24.77,17817.51,47139270.74,-1.35,11807045.85,-2.43
19,2025,8.0,August,6156,2606,46927485.11,35412659.05,11514826.06,24.54,18007.48,45913674.74,2.21,11243106.05,2.42
9,2024,10.0,October,6176,2594,47151653.05,35680294.80,11471358.25,24.33,18177.20,42664906.93,10.52,10553266.90,8.70
2,2024,3.0,March,6185,2564,47293209.21,35837882.15,11455327.06,24.22,18445.09,42757973.40,10.61,10536712.74,8.72

In [95]:
weakest_revenue_months = (
    monthly_business
    .sort_values(
        "Revenue",
        ascending=True
    )
    .head(10)
)

display(weakest_revenue_months)

,Year,Month_Number,Month_Name,Units_Sold,Orders,Revenue,Cost,Profit,Profit_Margin_Percent,Average_Order_Value,Previous_Month_Revenue,MoM_Revenue_Growth_Percent,Previous_Month_Profit,MoM_Profit_Growth_Percent
27,2026,4.0,April,5484,2323,41994344.40,31731929.03,10262415.37,24.44,18077.63,45608262.08,-7.92,11124030.28,-7.75
13,2025,2.0,February,5593,2337,42175078.09,31908052.57,10267025.52,24.34,18046.67,47196919.38,-10.64,11778318.92,-12.83
8,2024,9.0,September,5530,2399,42664906.93,32111640.03,10553266.90,24.74,17784.45,48460455.71,-11.96,11983658.32,-11.94
15,2025,4.0,April,5593,2398,42678296.19,32245185.52,10433110.67,24.45,17797.45,44920726.16,-4.99,11007036.46,-5.21
1,2024,2.0,February,5459,2333,42757973.40,32221260.66,10536712.74,24.64,18327.46,45928721.52,-6.90,11090266.23,-4.99
25,2026,2.0,February,5497,2313,43268831.63,32508976.20,10759855.43,24.87,18706.80,46503689.37,-6.96,11520707.92,-6.60
22,2025,11.0,November,5746,2419,43337990.48,32797667.86,10540322.62,24.32,17915.66,45585179.36,-4.93,10927682.04,-3.54
20,2025,9.0,September,5787,2457,43899251.14,33051821.04,10847430.10,24.71,17867.01,46927485.11,-6.45,11514826.06,-5.80
3,2024,4.0,April,5808,2460,44229524.02,33815616.23,10413907.79,23.55,17979.48,47293209.21,-6.48,11455327.06,-9.09
6,2024,7.0,July,5915,2533,44538880.51,33871110.71,10667769.80,23.95,17583.45,45395067.75,-1.89,11122880.14,-4.09

In [96]:
seasonality_query = """
SELECT
    d.Month_Number,
    d.Month_Name,

    COUNT(DISTINCT s.Order_ID) AS Orders,

    SUM(s.Quantity) AS Units_Sold,

    ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

    ROUND(SUM(s.Profit), 2) AS Profit,

    ROUND(
        SUM(s.Profit) * 100.0 /
        NULLIF(SUM(s.Sales_Amount), 0),
        2
    ) AS Profit_Margin_Percent

FROM sales s

LEFT JOIN date d
    ON DATE(s.Order_Date) = DATE(d.Date)

GROUP BY
    d.Month_Number,
    d.Month_Name

ORDER BY
    d.Month_Number;
"""

seasonality = pd.read_sql_query(
    seasonality_query,
    conn
)

display(seasonality)

,Month_Number,Month_Name,Orders,Units_Sold,Revenue,Profit,Profit_Margin_Percent
0,1.0,January,7762,18294,1.396293e+08,34389293.07,24.63
1,2.0,February,6983,16549,1.282019e+08,31563593.69,24.62
2,3.0,March,7539,18182,1.378222e+08,33586393.80,24.37
3,4.0,April,7181,16885,1.289022e+08,31109433.83,24.13
4,5.0,May,7695,18332,1.425477e+08,34919464.49,24.50
5,6.0,June,7434,17402,1.358912e+08,33563835.45,24.70
6,7.0,July,5064,11776,9.045256e+07,21910875.85,24.22
7,8.0,August,5263,12352,9.538794e+07,23498484.38,24.63
8,9.0,September,4856,11317,8.656416e+07,21400697.00,24.72
9,10.0,October,5120,12155,9.273683e+07,22399040.29,24.15
10,11.0,November,4900,11669,8.918657e+07,21905917.14,24.56
11,12.0,December,5123,12264,9.430252e+07,23337725.53,24.75

In [97]:
average_monthly_revenue = seasonality["Revenue"].mean()

seasonality["Revenue_Performance"] = (
    seasonality["Revenue"]
    .apply(
        lambda x:
        "Above Average"
        if x > average_monthly_revenue
        else "Below Average"
    )
)

display(seasonality)

,Month_Number,Month_Name,Orders,Units_Sold,Revenue,Profit,Profit_Margin_Percent,Revenue_Performance
0,1.0,January,7762,18294,1.396293e+08,34389293.07,24.63,Above Average
1,2.0,February,6983,16549,1.282019e+08,31563593.69,24.62,Above Average
2,3.0,March,7539,18182,1.378222e+08,33586393.80,24.37,Above Average
3,4.0,April,7181,16885,1.289022e+08,31109433.83,24.13,Above Average
4,5.0,May,7695,18332,1.425477e+08,34919464.49,24.50,Above Average
5,6.0,June,7434,17402,1.358912e+08,33563835.45,24.70,Above Average
6,7.0,July,5064,11776,9.045256e+07,21910875.85,24.22,Below Average
7,8.0,August,5263,12352,9.538794e+07,23498484.38,24.63,Below Average
8,9.0,September,4856,11317,8.656416e+07,21400697.00,24.72,Below Average
9,10.0,October,5120,12155,9.273683e+07,22399040.29,24.15,Below Average
10,11.0,November,4900,11669,8.918657e+07,21905917.14,24.56,Below Average
11,12.0,December,5123,12264,9.430252e+07,23337725.53,24.75,Below Average

In [98]:
monthly_business.to_csv(
    advanced_sql_path / "monthly_business_performance.csv",
    index=False
)

seasonality.to_csv(
    advanced_sql_path / "seasonality_analysis.csv",
    index=False
)

print("Saved: monthly_business_performance.csv")
print("Saved: seasonality_analysis.csv")
print(f"Output folder: {advanced_sql_path}")

Saved: monthly_business_performance.csv
Saved: seasonality_analysis.csv
Output folder: C:\Users\shubh\Desktop\AI_Sales_Intelligence\data\cleaned\sql_outputs\advanced

In [99]:
# ============================================
# ADVANCED SQL 11: CUSTOMER RFM SEGMENTATION
# ============================================

rfm_query = """
WITH customer_metrics AS (
    SELECT
        c.Customer_ID,
        c.Customer_Name,

        MAX(DATE(s.Order_Date)) AS Last_Purchase_Date,

        COUNT(DISTINCT s.Order_ID) AS Frequency,

        ROUND(
            SUM(s.Sales_Amount),
            2
        ) AS Monetary

    FROM sales s

    LEFT JOIN customer c
        ON s.Customer_ID = c.Customer_ID

    GROUP BY
        c.Customer_ID,
        c.Customer_Name
),

reference_date AS (
    SELECT
        MAX(DATE(Order_Date)) AS Analysis_Date
    FROM sales
),

rfm_base AS (
    SELECT
        cm.Customer_ID,
        cm.Customer_Name,

        julianday(rd.Analysis_Date)
        - julianday(cm.Last_Purchase_Date)
        AS Recency,

        cm.Frequency,
        cm.Monetary

    FROM customer_metrics cm

    CROSS JOIN reference_date rd
),

rfm_scores AS (
    SELECT
        *,

        NTILE(5) OVER (
            ORDER BY Recency DESC
        ) AS Recency_Score,

        NTILE(5) OVER (
            ORDER BY Frequency ASC
        ) AS Frequency_Score,

        NTILE(5) OVER (
            ORDER BY Monetary ASC
        ) AS Monetary_Score

    FROM rfm_base
)

SELECT
    Customer_ID,
    Customer_Name,

    ROUND(Recency, 0) AS Recency_Days,

    Frequency,
    Monetary,

    Recency_Score,
    Frequency_Score,
    Monetary_Score,

    (
        Recency_Score
        + Frequency_Score
        + Monetary_Score
    ) AS RFM_Total_Score,

    CASE

        WHEN Recency_Score >= 4
             AND Frequency_Score >= 4
             AND Monetary_Score >= 4
            THEN 'Champions'

        WHEN Recency_Score >= 3
             AND Frequency_Score >= 4
             AND Monetary_Score >= 3
            THEN 'Loyal Customers'

        WHEN Recency_Score >= 4
             AND Frequency_Score >= 2
             AND Monetary_Score >= 2
            THEN 'Potential Loyalists'

        WHEN Recency_Score <= 2
             AND Frequency_Score >= 3
             AND Monetary_Score >= 3
            THEN 'At Risk'

        WHEN Recency_Score <= 2
             AND Frequency_Score <= 2
             AND Monetary_Score <= 2
            THEN 'Lost / Low Value'

        ELSE 'Regular Customers'

    END AS Customer_Segment

FROM rfm_scores

ORDER BY
    RFM_Total_Score DESC,
    Monetary DESC;
"""

rfm_analysis = pd.read_sql_query(
    rfm_query,
    conn
)

display(rfm_analysis)

,Customer_ID,Customer_Name,Recency_Days,Frequency,Monetary,Recency_Score,Frequency_Score,Monetary_Score,RFM_Total_Score,Customer_Segment
0,CUST02369,Vivaan Sharma,6.0,26,656467.23,5,5,5,15,Champions
1,CUST03244,Neha Mhaske,12.0,19,600454.29,5,5,5,15,Champions
2,CUST00349,Amit Singh,6.0,20,543035.24,5,5,5,15,Champions
3,CUST02022,Neha Patil,15.0,23,541358.75,5,5,5,15,Champions
4,CUST01139,Karan Joshi,2.0,22,534445.22,5,5,5,15,Champions
...,...,...,...,...,...,...,...,...,...,...
5995,CUST04709,Pooja Kumar,179.0,4,40960.86,1,1,1,3,Lost / Low Value
5996,CUST01541,Amit Joshi,172.0,5,40004.95,1,1,1,3,Lost / Low Value
5997,CUST02713,Neha Patil,149.0,4,38365.61,1,1,1,3,Lost / Low Value
5998,CUST04054,Vivaan Gupta,471.0,3,29726.08,1,1,1,3,Lost / Low Value
5999,CUST03449,Isha Deshmukh,348.0,3,25823.60,1,1,1,3,Lost / Low Value

In [100]:
rfm_segment_summary = (
    rfm_analysis
    .groupby("Customer_Segment")
    .agg(
        Customers=("Customer_ID", "count"),
        Revenue=("Monetary", "sum"),
        Average_Recency_Days=("Recency_Days", "mean"),
        Average_Frequency=("Frequency", "mean"),
        Average_Monetary=("Monetary", "mean")
    )
    .reset_index()
)

rfm_segment_summary = rfm_segment_summary.round(2)

display(rfm_segment_summary)

,Customer_Segment,Customers,Revenue,Average_Recency_Days,Average_Frequency,Average_Monetary
0,At Risk,947,2.710324e+08,122.92,14.69,286201.07
1,Champions,851,2.823705e+08,16.31,16.39,331810.18
2,Lost / Low Value,913,1.220189e+08,159.81,8.60,133646.13
3,Loyal Customers,670,1.886997e+08,41.07,15.75,281641.29
4,Potential Loyalists,844,1.817172e+08,16.60,11.96,215304.78
5,Regular Customers,1775,3.157863e+08,68.64,10.46,177907.80

In [101]:
rfm_segment_summary["Revenue_Contribution_Percent"] = (
    rfm_segment_summary["Revenue"]
    / rfm_segment_summary["Revenue"].sum()
    * 100
)

rfm_segment_summary = rfm_segment_summary.round(2)

display(
    rfm_segment_summary
    .sort_values(
        "Revenue",
        ascending=False
    )
)

,Customer_Segment,Customers,Revenue,Average_Recency_Days,Average_Frequency,Average_Monetary,Revenue_Contribution_Percent
5,Regular Customers,1775,3.157863e+08,68.64,10.46,177907.80,23.19
1,Champions,851,2.823705e+08,16.31,16.39,331810.18,20.74
0,At Risk,947,2.710324e+08,122.92,14.69,286201.07,19.91
3,Loyal Customers,670,1.886997e+08,41.07,15.75,281641.29,13.86
4,Potential Loyalists,844,1.817172e+08,16.60,11.96,215304.78,13.35
2,Lost / Low Value,913,1.220189e+08,159.81,8.60,133646.13,8.96

In [102]:
top_rfm_customers = (
    rfm_analysis
    .sort_values(
        ["RFM_Total_Score", "Monetary"],
        ascending=[False, False]
    )
    .head(20)
)

display(top_rfm_customers)

,Customer_ID,Customer_Name,Recency_Days,Frequency,Monetary,Recency_Score,Frequency_Score,Monetary_Score,RFM_Total_Score,Customer_Segment
0,CUST02369,Vivaan Sharma,6.0,26,656467.23,5,5,5,15,Champions
1,CUST03244,Neha Mhaske,12.0,19,600454.29,5,5,5,15,Champions
2,CUST00349,Amit Singh,6.0,20,543035.24,5,5,5,15,Champions
3,CUST02022,Neha Patil,15.0,23,541358.75,5,5,5,15,Champions
4,CUST01139,Karan Joshi,2.0,22,534445.22,5,5,5,15,Champions
5,CUST02672,Ananya Joshi,9.0,20,518367.26,5,5,5,15,Champions
6,CUST04433,Ananya Kumar,5.0,20,512302.35,5,5,5,15,Champions
7,CUST03669,Aarav Deshmukh,12.0,17,497075.29,5,5,5,15,Champions
8,CUST00348,Amit Mehta,1.0,18,496225.41,5,5,5,15,Champions
9,CUST04416,Vivaan Verma,3.0,21,495128.65,5,5,5,15,Champions
10,CUST01244,Vivaan Shah,0.0,19,491153.79,5,5,5,15,Champions
11,CUST01564,Pooja Joshi,10.0,18,489934.67,5,5,5,15,Champions
12,CUST04378,Vivaan Mhaske,0.0,20,483643.45,5,5,5,15,Champions
13,CUST03149,Karan Nair,15.0,16,482374.99,5,5,5,15,Champions
14,CUST03969,Rohan Kumar,16.0,19,481934.91,5,5,5,15,Champions
15,CUST01307,Arjun Sharma,3.0,19,481414.00,5,5,5,15,Champions
16,CUST02439,Priya Deshmukh,8.0,15,477507.72,5,5,5,15,Champions
17,CUST04335,Amit Gupta,8.0,21,477477.47,5,5,5,15,Champions
18,CUST05036,Amit Patil,14.0,20,471552.49,5,5,5,15,Champions
19,CUST05431,Arjun Kumar,2.0,17,471221.61,5,5,5,15,Champions

In [103]:
rfm_analysis.to_csv(
    advanced_sql_path / "customer_rfm_analysis.csv",
    index=False
)

rfm_segment_summary.to_csv(
    advanced_sql_path / "rfm_segment_summary.csv",
    index=False
)

print("Saved: customer_rfm_analysis.csv")
print("Saved: rfm_segment_summary.csv")
print(f"Output folder: {advanced_sql_path}")

Saved: customer_rfm_analysis.csv
Saved: rfm_segment_summary.csv
Output folder: C:\Users\shubh\Desktop\AI_Sales_Intelligence\data\cleaned\sql_outputs\advanced

In [104]:
# ============================================
# ADVANCED SQL 12: SALES CHANNEL PERFORMANCE
# ============================================

channel_performance_query = """
SELECT
    Channel,

    COUNT(DISTINCT Order_ID) AS Orders,

    COUNT(DISTINCT Customer_ID) AS Customers,

    SUM(Quantity) AS Units_Sold,

    ROUND(SUM(Sales_Amount), 2) AS Revenue,

    ROUND(SUM(Cost_Amount), 2) AS Cost,

    ROUND(SUM(Profit), 2) AS Profit,

    ROUND(AVG(Discount_Percent), 2) AS Average_Discount,

    ROUND(
        SUM(Profit) * 100.0 /
        NULLIF(SUM(Sales_Amount), 0),
        2
    ) AS Profit_Margin_Percent,

    ROUND(
        SUM(Sales_Amount) /
        NULLIF(COUNT(DISTINCT Order_ID), 0),
        2
    ) AS Average_Order_Value,

    ROUND(
        SUM(Sales_Amount) /
        NULLIF(SUM(Quantity), 0),
        2
    ) AS Average_Selling_Price

FROM sales

GROUP BY
    Channel

ORDER BY
    Revenue DESC;
"""

channel_performance = pd.read_sql_query(
    channel_performance_query,
    conn
)

display(channel_performance)

,Channel,Orders,Customers,Units_Sold,Revenue,Cost,Profit,Average_Discount,Profit_Margin_Percent,Average_Order_Value,Average_Selling_Price
0,Online,41322,5999,97878,7.524344e+08,5.680959e+08,1.843385e+08,9.17,24.50,18209.05,7687.47
1,Store,18604,5749,44364,3.404260e+08,2.564709e+08,8.395513e+07,9.16,24.66,18298.54,7673.48
2,Marketplace,14994,5503,34935,2.687646e+08,2.034735e+08,6.529111e+07,9.14,24.29,17924.81,7693.28

In [105]:
channel_performance["Revenue_Contribution_Percent"] = (
    channel_performance["Revenue"]
    / channel_performance["Revenue"].sum()
    * 100
)

channel_performance["Profit_Contribution_Percent"] = (
    channel_performance["Profit"]
    / channel_performance["Profit"].sum()
    * 100
)

channel_performance = channel_performance.round(2)

display(channel_performance)

,Channel,Orders,Customers,Units_Sold,Revenue,Cost,Profit,Average_Discount,Profit_Margin_Percent,Average_Order_Value,Average_Selling_Price,Revenue_Contribution_Percent,Profit_Contribution_Percent
0,Online,41322,5999,97878,7.524344e+08,5.680959e+08,1.843385e+08,9.17,24.50,18209.05,7687.47,55.26,55.26
1,Store,18604,5749,44364,3.404260e+08,2.564709e+08,8.395513e+07,9.16,24.66,18298.54,7673.48,25.00,25.17
2,Marketplace,14994,5503,34935,2.687646e+08,2.034735e+08,6.529111e+07,9.14,24.29,17924.81,7693.28,19.74,19.57

In [106]:
channel_year_query = """
SELECT
    d.Year,
    s.Channel,

    COUNT(DISTINCT s.Order_ID) AS Orders,

    SUM(s.Quantity) AS Units_Sold,

    ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

    ROUND(SUM(s.Profit), 2) AS Profit,

    ROUND(
        SUM(s.Profit) * 100.0 /
        NULLIF(SUM(s.Sales_Amount), 0),
        2
    ) AS Profit_Margin_Percent

FROM sales s

LEFT JOIN date d
    ON DATE(s.Order_Date) = DATE(d.Date)

GROUP BY
    d.Year,
    s.Channel

ORDER BY
    d.Year,
    Revenue DESC;
"""

channel_year = pd.read_sql_query(
    channel_year_query,
    conn
)

display(channel_year)

,Year,Channel,Orders,Units_Sold,Revenue,Profit,Profit_Margin_Percent
0,2024,Online,16617,39337,3.040221e+08,73999737.75,24.34
1,2024,Store,7512,17810,1.366541e+08,33513350.00,24.52
2,2024,Marketplace,6094,14103,1.085906e+08,26432733.31,24.34
3,2025,Online,16571,39080,3.001158e+08,73924623.17,24.63
4,2025,Store,7466,17843,1.360712e+08,33707667.92,24.77
5,2025,Marketplace,5879,13712,1.048267e+08,25380076.69,24.21
6,2026,Online,8134,19461,1.482965e+08,36414153.54,24.55
7,2026,Store,3626,8711,6.770065e+07,16734115.51,24.72
8,2026,Marketplace,3021,7120,5.534732e+07,13478296.63,24.35

In [107]:
best_revenue_channel = channel_performance.loc[
    channel_performance["Revenue"].idxmax()
]

best_profit_channel = channel_performance.loc[
    channel_performance["Profit"].idxmax()
]

best_margin_channel = channel_performance.loc[
    channel_performance["Profit_Margin_Percent"].idxmax()
]

print(
    "Highest Revenue Channel:",
    best_revenue_channel["Channel"]
)

print(
    "Highest Profit Channel:",
    best_profit_channel["Channel"]
)

print(
    "Highest Margin Channel:",
    best_margin_channel["Channel"]
)

Highest Revenue Channel: Online
Highest Profit Channel: Online
Highest Margin Channel: Store

In [108]:
channel_performance.to_csv(
    advanced_sql_path / "channel_performance.csv",
    index=False
)

channel_year.to_csv(
    advanced_sql_path / "channel_year_performance.csv",
    index=False
)

print("Saved: channel_performance.csv")
print("Saved: channel_year_performance.csv")
print(f"Output folder: {advanced_sql_path}")

Saved: channel_performance.csv
Saved: channel_year_performance.csv
Output folder: C:\Users\shubh\Desktop\AI_Sales_Intelligence\data\cleaned\sql_outputs\advanced

In [109]:
# ============================================
# ADVANCED SQL 13: CATEGORY PORTFOLIO ANALYSIS
# ============================================

category_portfolio_query = """
WITH category_performance AS (
    SELECT
        p.Category,

        COUNT(DISTINCT p.Product_ID) AS Products,

        COUNT(DISTINCT s.Order_ID) AS Orders,

        COUNT(DISTINCT s.Customer_ID) AS Customers,

        SUM(s.Quantity) AS Units_Sold,

        ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

        ROUND(SUM(s.Cost_Amount), 2) AS Cost,

        ROUND(SUM(s.Profit), 2) AS Profit

    FROM sales s

    LEFT JOIN product p
        ON s.Product_ID = p.Product_ID

    GROUP BY
        p.Category
),

ranked_categories AS (
    SELECT
        *,

        RANK() OVER (
            ORDER BY Revenue DESC
        ) AS Revenue_Rank,

        RANK() OVER (
            ORDER BY Profit DESC
        ) AS Profit_Rank

    FROM category_performance
),

benchmarks AS (
    SELECT
        AVG(Revenue) AS Average_Category_Revenue,

        AVG(
            Profit * 100.0 /
            NULLIF(Revenue, 0)
        ) AS Average_Category_Margin

    FROM category_performance
)

SELECT
    rc.Category,
    rc.Products,
    rc.Orders,
    rc.Customers,
    rc.Units_Sold,
    rc.Revenue,
    rc.Cost,
    rc.Profit,

    ROUND(
        rc.Profit * 100.0 /
        NULLIF(rc.Revenue, 0),
        2
    ) AS Profit_Margin_Percent,

    ROUND(
        rc.Revenue /
        NULLIF(rc.Orders, 0),
        2
    ) AS Average_Order_Value,

    rc.Revenue_Rank,
    rc.Profit_Rank,

    CASE
        WHEN rc.Revenue > b.Average_Category_Revenue
             AND
             (
                 rc.Profit * 100.0 /
                 NULLIF(rc.Revenue, 0)
             ) > b.Average_Category_Margin
            THEN 'High Revenue - High Margin'

        WHEN rc.Revenue > b.Average_Category_Revenue
             AND
             (
                 rc.Profit * 100.0 /
                 NULLIF(rc.Revenue, 0)
             ) < b.Average_Category_Margin
            THEN 'High Revenue - Low Margin'

        WHEN rc.Revenue < b.Average_Category_Revenue
             AND
             (
                 rc.Profit * 100.0 /
                 NULLIF(rc.Revenue, 0)
             ) > b.Average_Category_Margin
            THEN 'Low Revenue - High Margin'

        ELSE 'Low Revenue - Low Margin'

    END AS Portfolio_Segment

FROM ranked_categories rc

CROSS JOIN benchmarks b

ORDER BY
    rc.Revenue_Rank;
"""

category_portfolio = pd.read_sql_query(
    category_portfolio_query,
    conn
)

display(category_portfolio)

,Category,Products,Orders,Customers,Units_Sold,Revenue,Cost,Profit,Profit_Margin_Percent,Average_Order_Value,Revenue_Rank,Profit_Rank,Portfolio_Segment
0,Electronics,36,14918,5483,35365,3.283501e+08,2.466674e+08,81682681.92,24.88,22010.33,1,1,High Revenue - High Margin
1,Beauty,36,15031,5517,35486,2.698045e+08,2.014051e+08,68399400.53,25.35,17949.87,2,2,Low Revenue - High Margin
2,Sports,36,15063,5488,35498,2.658742e+08,2.021629e+08,63711259.66,23.96,17650.81,3,4,Low Revenue - Low Margin
3,Home,36,15002,5516,35556,2.509789e+08,1.949403e+08,56038569.38,22.33,16729.70,4,5,Low Revenue - Low Margin
4,Fashion,36,14906,5486,35272,2.466173e+08,1.828645e+08,63752843.03,25.85,16544.84,5,3,Low Revenue - High Margin

In [110]:
category_portfolio["Revenue_Contribution_Percent"] = (
    category_portfolio["Revenue"]
    / category_portfolio["Revenue"].sum()
    * 100
)

category_portfolio["Profit_Contribution_Percent"] = (
    category_portfolio["Profit"]
    / category_portfolio["Profit"].sum()
    * 100
)

category_portfolio = category_portfolio.round(2)

display(category_portfolio)

,Category,Products,Orders,Customers,Units_Sold,Revenue,Cost,Profit,Profit_Margin_Percent,Average_Order_Value,Revenue_Rank,Profit_Rank,Portfolio_Segment,Revenue_Contribution_Percent,Profit_Contribution_Percent
0,Electronics,36,14918,5483,35365,3.283501e+08,2.466674e+08,81682681.92,24.88,22010.33,1,1,High Revenue - High Margin,24.11,24.49
1,Beauty,36,15031,5517,35486,2.698045e+08,2.014051e+08,68399400.53,25.35,17949.87,2,2,Low Revenue - High Margin,19.81,20.50
2,Sports,36,15063,5488,35498,2.658742e+08,2.021629e+08,63711259.66,23.96,17650.81,3,4,Low Revenue - Low Margin,19.53,19.10
3,Home,36,15002,5516,35556,2.509789e+08,1.949403e+08,56038569.38,22.33,16729.70,4,5,Low Revenue - Low Margin,18.43,16.80
4,Fashion,36,14906,5486,35272,2.466173e+08,1.828645e+08,63752843.03,25.85,16544.84,5,3,Low Revenue - High Margin,18.11,19.11

In [111]:
portfolio_summary = (
    category_portfolio
    .groupby("Portfolio_Segment")
    .agg(
        Categories=("Category", "count"),
        Revenue=("Revenue", "sum"),
        Profit=("Profit", "sum"),
        Units_Sold=("Units_Sold", "sum")
    )
    .reset_index()
    .sort_values(
        "Revenue",
        ascending=False
    )
)

display(portfolio_summary)

,Portfolio_Segment,Categories,Revenue,Profit,Units_Sold
2,Low Revenue - Low Margin,2,5.168531e+08,1.197498e+08,71054
1,Low Revenue - High Margin,2,5.164218e+08,1.321522e+08,70758
0,High Revenue - High Margin,1,3.283501e+08,8.168268e+07,35365

In [112]:
best_categories = (
    category_portfolio
    .sort_values(
        "Revenue",
        ascending=False
    )
    .head(5)
)

weakest_categories = (
    category_portfolio
    .sort_values(
        "Revenue",
        ascending=True
    )
    .head(5)
)

print("Top 5 Categories by Revenue")
display(best_categories)

print("Bottom 5 Categories by Revenue")
display(weakest_categories)

Top 5 Categories by Revenue

,Category,Products,Orders,Customers,Units_Sold,Revenue,Cost,Profit,Profit_Margin_Percent,Average_Order_Value,Revenue_Rank,Profit_Rank,Portfolio_Segment,Revenue_Contribution_Percent,Profit_Contribution_Percent
0,Electronics,36,14918,5483,35365,3.283501e+08,2.466674e+08,81682681.92,24.88,22010.33,1,1,High Revenue - High Margin,24.11,24.49
1,Beauty,36,15031,5517,35486,2.698045e+08,2.014051e+08,68399400.53,25.35,17949.87,2,2,Low Revenue - High Margin,19.81,20.50
2,Sports,36,15063,5488,35498,2.658742e+08,2.021629e+08,63711259.66,23.96,17650.81,3,4,Low Revenue - Low Margin,19.53,19.10
3,Home,36,15002,5516,35556,2.509789e+08,1.949403e+08,56038569.38,22.33,16729.70,4,5,Low Revenue - Low Margin,18.43,16.80
4,Fashion,36,14906,5486,35272,2.466173e+08,1.828645e+08,63752843.03,25.85,16544.84,5,3,Low Revenue - High Margin,18.11,19.11

Bottom 5 Categories by Revenue

,Category,Products,Orders,Customers,Units_Sold,Revenue,Cost,Profit,Profit_Margin_Percent,Average_Order_Value,Revenue_Rank,Profit_Rank,Portfolio_Segment,Revenue_Contribution_Percent,Profit_Contribution_Percent
4,Fashion,36,14906,5486,35272,2.466173e+08,1.828645e+08,63752843.03,25.85,16544.84,5,3,Low Revenue - High Margin,18.11,19.11
3,Home,36,15002,5516,35556,2.509789e+08,1.949403e+08,56038569.38,22.33,16729.70,4,5,Low Revenue - Low Margin,18.43,16.80
2,Sports,36,15063,5488,35498,2.658742e+08,2.021629e+08,63711259.66,23.96,17650.81,3,4,Low Revenue - Low Margin,19.53,19.10
1,Beauty,36,15031,5517,35486,2.698045e+08,2.014051e+08,68399400.53,25.35,17949.87,2,2,Low Revenue - High Margin,19.81,20.50
0,Electronics,36,14918,5483,35365,3.283501e+08,2.466674e+08,81682681.92,24.88,22010.33,1,1,High Revenue - High Margin,24.11,24.49

In [113]:
highest_margin_categories = (
    category_portfolio
    .sort_values(
        "Profit_Margin_Percent",
        ascending=False
    )
    .head(5)
)

print("Top 5 Categories by Profit Margin")

display(
    highest_margin_categories[
        [
            "Category",
            "Revenue",
            "Profit",
            "Profit_Margin_Percent"
        ]
    ]
)

Top 5 Categories by Profit Margin

      Category       Revenue       Profit  Profit_Margin_Percent
4      Fashion  2.466173e+08  63752843.03                  25.85
1       Beauty  2.698045e+08  68399400.53                  25.35
0  Electronics  3.283501e+08  81682681.92                  24.88
2       Sports  2.658742e+08  63711259.66                  23.96
3         Home  2.509789e+08  56038569.38                  22.33

In [114]:
category_portfolio.to_csv(
    advanced_sql_path / "category_portfolio_analysis.csv",
    index=False
)

portfolio_summary.to_csv(
    advanced_sql_path / "category_portfolio_summary.csv",
    index=False
)

print("Saved: category_portfolio_analysis.csv")
print("Saved: category_portfolio_summary.csv")
print(f"Output folder: {advanced_sql_path}")

Saved: category_portfolio_analysis.csv
Saved: category_portfolio_summary.csv
Output folder: C:\Users\shubh\Desktop\AI_Sales_Intelligence\data\cleaned\sql_outputs\advanced

In [115]:
# ============================================
# ADVANCED SQL 14: REGION × CATEGORY ANALYSIS
# ============================================

region_category_query = """
WITH region_category AS (
    SELECT
        s.Region_ID,
        r.Region,
        p.Category,

        COUNT(DISTINCT s.Order_ID) AS Orders,

        COUNT(DISTINCT s.Customer_ID) AS Customers,

        SUM(s.Quantity) AS Units_Sold,

        ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

        ROUND(SUM(s.Cost_Amount), 2) AS Cost,

        ROUND(SUM(s.Profit), 2) AS Profit

    FROM sales s

    LEFT JOIN region r
        ON s.Region_ID = r.Region_ID

    LEFT JOIN product p
        ON s.Product_ID = p.Product_ID

    GROUP BY
        s.Region_ID,
        r.Region,
        p.Category
),

ranked_matrix AS (
    SELECT
        *,

        RANK() OVER (
            PARTITION BY Region_ID
            ORDER BY Revenue DESC
        ) AS Category_Revenue_Rank_In_Region,

        RANK() OVER (
            PARTITION BY Category
            ORDER BY Revenue DESC
        ) AS Region_Revenue_Rank_In_Category

    FROM region_category
)

SELECT
    Region_ID,
    Region,
    Category,

    Orders,
    Customers,
    Units_Sold,

    Revenue,
    Cost,
    Profit,

    ROUND(
        Profit * 100.0 /
        NULLIF(Revenue, 0),
        2
    ) AS Profit_Margin_Percent,

    ROUND(
        Revenue /
        NULLIF(Orders, 0),
        2
    ) AS Average_Order_Value,

    Category_Revenue_Rank_In_Region,
    Region_Revenue_Rank_In_Category

FROM ranked_matrix

ORDER BY
    Region,
    Revenue DESC;
"""

region_category_analysis = pd.read_sql_query(
    region_category_query,
    conn
)

display(region_category_analysis)

,Region_ID,Region,Category,Orders,Customers,Units_Sold,Revenue,Cost,Profit,Profit_Margin_Percent,Average_Order_Value,Category_Revenue_Rank_In_Region,Region_Revenue_Rank_In_Category
0,R025,Central,Electronics,594,217,1354,12801955.11,9639019.76,3162935.35,24.71,21552.11,1,17
1,R025,Central,Beauty,624,229,1444,11453191.03,8458356.17,2994834.86,26.15,18354.47,2,5
2,R024,Central,Electronics,536,213,1263,11050042.75,8294220.38,2755822.37,24.94,20615.75,1,25
3,R025,Central,Sports,658,226,1488,10545638.23,8049524.41,2496113.82,23.67,16026.81,3,13
4,R024,Central,Home,633,223,1510,10502814.61,8137681.13,2365133.48,22.52,16592.12,2,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,R002,West,Home,592,212,1392,9503504.74,7359679.83,2143824.91,22.56,16053.22,4,17
121,R004,West,Fashion,588,215,1370,9482920.64,7010517.10,2472403.54,26.07,16127.42,4,18
122,R004,West,Home,554,218,1296,9383869.82,7169636.94,2214232.88,23.60,16938.39,5,20
123,R003,West,Home,586,218,1376,9191522.10,7114405.62,2077116.48,22.60,15685.19,5,21
124,R002,West,Fashion,565,213,1305,9111606.00,6696954.76,2414651.24,26.50,16126.74,5,23

In [116]:
best_category_by_region = (
    region_category_analysis
    .sort_values(
        [
            "Region",
            "Category_Revenue_Rank_In_Region"
        ]
    )
    .groupby("Region", as_index=False)
    .first()
)

display(
    best_category_by_region[
        [
            "Region",
            "Category",
            "Revenue",
            "Profit",
            "Profit_Margin_Percent"
        ]
    ]
)

    Region     Category      Revenue      Profit  Profit_Margin_Percent
0  Central  Electronics  12801955.11  3162935.35                  24.71
1     East  Electronics  14611951.78  3610551.97                  24.71
2    North  Electronics  14108227.87  3496793.74                  24.79
3    South  Electronics  14647436.08  3689523.91                  25.19
4     West  Electronics  14814420.81  3737942.28                  25.23

In [117]:
best_region_by_category = (
    region_category_analysis
    .sort_values(
        [
            "Category",
            "Region_Revenue_Rank_In_Category"
        ]
    )
    .groupby("Category", as_index=False)
    .first()
)

display(
    best_region_by_category[
        [
            "Category",
            "Region",
            "Revenue",
            "Profit",
            "Profit_Margin_Percent"
        ]
    ]
)

      Category Region      Revenue      Profit  Profit_Margin_Percent
0       Beauty  South  12653628.67  3239528.71                  25.60
1  Electronics   West  14814420.81  3737942.28                  25.23
2      Fashion  North  11669836.39  3025602.55                  25.93
3         Home  North  11156384.08  2462441.46                  22.07
4       Sports  North  12802892.47  3018669.19                  23.58

In [118]:
high_value_combinations = (
    region_category_analysis
    .sort_values(
        "Revenue",
        ascending=False
    )
    .head(20)
)

display(high_value_combinations)

,Region_ID,Region,Category,Orders,Customers,Units_Sold,Revenue,Cost,Profit,Profit_Margin_Percent,Average_Order_Value,Category_Revenue_Rank_In_Region,Region_Revenue_Rank_In_Category
105,R001,West,Electronics,636,223,1583,14814420.81,11076478.53,3737942.28,25.23,23293.11,1,1
60,R019,South,Electronics,629,229,1502,14647436.08,10957912.17,3689523.91,25.19,23286.86,1,2
10,R013,East,Electronics,656,229,1597,14611951.78,11001399.81,3610551.97,24.71,22274.32,1,3
11,R012,East,Electronics,660,233,1599,14519000.53,10995281.43,3523719.10,24.27,21998.49,1,4
61,R016,South,Electronics,661,240,1564,14513606.89,10871252.44,3642354.45,25.10,21957.05,1,5
25,R010,North,Electronics,669,246,1543,14108227.87,10611434.13,3496793.74,24.79,21088.53,1,6
62,R018,South,Electronics,630,225,1501,14074413.79,10563755.03,3510658.76,24.94,22340.34,1,7
26,R005,North,Electronics,585,218,1419,13719746.04,10252929.41,3466816.63,25.27,23452.56,1,8
106,R003,West,Electronics,585,207,1401,13555322.10,10045306.27,3510015.83,25.89,23171.49,1,9
27,R006,North,Electronics,584,211,1421,13447488.33,10132688.47,3314799.86,24.65,23026.52,1,10
63,R020,South,Electronics,596,214,1417,13190342.17,9887331.12,3303011.05,25.04,22131.45,1,11
28,R007,North,Electronics,631,232,1443,13176778.36,9998248.17,3178530.19,24.12,20882.37,1,12
64,R022,South,Electronics,613,224,1432,13140008.43,9842995.24,3297013.19,25.09,21435.58,1,13
107,R002,West,Electronics,585,216,1405,13036233.33,9794861.90,3241371.43,24.86,22284.16,1,14
65,R023,South,Electronics,604,224,1401,12956705.28,9765051.87,3191653.41,24.63,21451.50,1,15
66,R017,South,Electronics,609,227,1445,12896562.32,9737260.96,3159301.36,24.50,21176.62,1,16
29,R010,North,Sports,721,257,1657,12802892.47,9784223.28,3018669.19,23.58,17757.13,2,1
0,R025,Central,Electronics,594,217,1354,12801955.11,9639019.76,3162935.35,24.71,21552.11,1,17
108,R004,West,Electronics,570,219,1361,12744063.06,9591582.68,3152480.38,24.74,22358.01,1,18
67,R021,South,Electronics,566,208,1369,12742448.72,9603505.15,3138943.57,24.63,22513.16,1,19

In [119]:
high_margin_combinations = (
    region_category_analysis
    .sort_values(
        "Profit_Margin_Percent",
        ascending=False
    )
    .head(20)
)

display(
    high_margin_combinations[
        [
            "Region",
            "Category",
            "Revenue",
            "Profit",
            "Profit_Margin_Percent"
        ]
    ]
)

      Region     Category      Revenue      Profit  Profit_Margin_Percent
47     North      Fashion  10251929.83  2793351.69                  27.25
103    South      Fashion   9129294.02  2443832.93                  26.77
124     West      Fashion   9111606.00  2414651.24                  26.50
96     South      Fashion   9696413.68  2562007.18                  26.42
119     West       Beauty   9764688.79  2570098.01                  26.32
94     South      Fashion   9825372.42  2570603.48                  26.16
1    Central       Beauty  11453191.03  2994834.86                  26.15
59     North      Fashion   8815967.77  2303170.80                  26.12
70     South       Beauty  11993802.02  3131773.37                  26.11
7    Central      Fashion  10079826.76  2630964.34                  26.10
121     West      Fashion   9482920.64  2472403.54                  26.07
97     South      Fashion   9554060.47  2487704.33                  26.04
54     North      Fashion   9429241.94  2452859.35                  26.01
71     South      Fashion  11651833.42  3028774.10                  25.99
82     South      Fashion  10580165.07  2746436.13                  25.96
33     North      Fashion  11669836.39  3025602.55                  25.93
106     West  Electronics  13555322.10  3510015.83                  25.89
19      East      Fashion  10435850.52  2698047.01                  25.85
24      East      Fashion   7842862.59  2024572.36                  25.81
30     North  Electronics  12439557.23  3210395.28                  25.81

In [120]:
region_category_analysis.to_csv(
    advanced_sql_path / "region_category_analysis.csv",
    index=False
)

best_category_by_region.to_csv(
    advanced_sql_path / "best_category_by_region.csv",
    index=False
)

best_region_by_category.to_csv(
    advanced_sql_path / "best_region_by_category.csv",
    index=False
)

print("Saved: region_category_analysis.csv")
print("Saved: best_category_by_region.csv")
print("Saved: best_region_by_category.csv")
print(f"Output folder: {advanced_sql_path}")

Saved: region_category_analysis.csv
Saved: best_category_by_region.csv
Saved: best_region_by_category.csv
Output folder: C:\Users\shubh\Desktop\AI_Sales_Intelligence\data\cleaned\sql_outputs\advanced

In [121]:
# ============================================
# ADVANCED SQL 15: PROFITABILITY & LOSS ANALYSIS
# ============================================

loss_transaction_query = """
SELECT
    Order_ID,
    Order_Date,
    Customer_ID,
    Product_ID,
    Region_ID,
    Channel,

    Quantity,
    Unit_Price,
    Discount_Percent,

    ROUND(Sales_Amount, 2) AS Revenue,
    ROUND(Cost_Amount, 2) AS Cost,
    ROUND(Profit, 2) AS Profit,

    CASE
        WHEN Profit < 0 THEN 'Loss-Making'
        WHEN Profit = 0 THEN 'Break-Even'
        ELSE 'Profitable'
    END AS Profitability_Status

FROM sales

ORDER BY
    Profit ASC;
"""

loss_transaction_analysis = pd.read_sql_query(
    loss_transaction_query,
    conn
)

display(
    loss_transaction_analysis.head(20)
)

,Order_ID,Order_Date,Customer_ID,Product_ID,Region_ID,Channel,Quantity,Unit_Price,Discount_Percent,Revenue,Cost,Profit,Profitability_Status
0,ORD009457,2025-11-25 00:00:00,CUST04944,PROD0017,R011,Online,5,9986.93,24.54,37680.69,41203.35,-3522.66,Loss-Making
1,ORD001931,2024-11-21 00:00:00,CUST04623,PROD0018,R004,Marketplace,4,12486.26,24.21,37853.35,41374.76,-3521.41,Loss-Making
2,ORD007261,2025-11-10 00:00:00,CUST03511,PROD0018,R001,Store,5,12486.26,22.73,48240.67,51718.45,-3477.78,Loss-Making
3,ORD048800,2025-07-13 00:00:00,CUST05992,PROD0018,R022,Online,4,12486.26,23.89,38013.17,41374.76,-3361.59,Loss-Making
4,ORD064446,2024-03-13 00:00:00,CUST03229,PROD0018,R014,Marketplace,4,12486.26,23.21,38352.80,41374.76,-3021.96,Loss-Making
5,ORD030857,2024-07-29 00:00:00,CUST03863,PROD0125,R017,Online,4,12200.98,23.30,37432.61,40405.80,-2973.19,Loss-Making
6,ORD073471,2024-04-09 00:00:00,CUST05891,PROD0068,R018,Online,4,14057.37,23.87,42807.50,45764.56,-2957.06,Loss-Making
7,ORD072378,2025-05-17 00:00:00,CUST02588,PROD0068,R001,Online,5,14057.37,22.76,54289.56,57205.70,-2916.14,Loss-Making
8,ORD050222,2025-09-23 00:00:00,CUST01674,PROD0018,R025,Store,3,12486.26,24.72,28198.97,31031.07,-2832.10,Loss-Making
9,ORD055140,2024-07-14 00:00:00,CUST03722,PROD0017,R005,Store,5,9986.93,22.83,38534.57,41203.35,-2668.78,Loss-Making
10,ORD026305,2025-07-08 00:00:00,CUST00856,PROD0018,R016,Online,6,12486.26,20.56,59514.51,62062.14,-2547.63,Loss-Making
11,ORD045051,2025-02-09 00:00:00,CUST02874,PROD0018,R018,Online,5,12486.26,21.22,49183.38,51718.45,-2535.07,Loss-Making
12,ORD002638,2025-10-12 00:00:00,CUST02343,PROD0076,R007,Marketplace,6,7447.92,21.04,35285.27,37786.56,-2501.29,Loss-Making
13,ORD009535,2025-07-17 00:00:00,CUST05316,PROD0068,R001,Store,3,14057.37,24.36,31898.98,34323.42,-2424.44,Loss-Making
14,ORD047283,2025-07-21 00:00:00,CUST01873,PROD0047,R018,Online,6,7182.73,27.59,31206.09,33625.68,-2419.59,Loss-Making
15,ORD010179,2026-05-19 00:00:00,CUST03859,PROD0017,R011,Marketplace,3,9986.93,25.56,22302.81,24722.01,-2419.20,Loss-Making
16,ORD006848,2024-04-11 00:00:00,CUST05355,PROD0018,R013,Online,4,12486.26,21.97,38972.11,41374.76,-2402.65,Loss-Making
17,ORD022254,2024-03-15 00:00:00,CUST03187,PROD0148,R002,Online,5,8761.87,23.70,33426.53,35663.30,-2236.77,Loss-Making
18,ORD074981,2025-05-15 00:00:00,CUST04277,PROD0170,R011,Store,3,15086.92,25.51,33714.74,35918.52,-2203.78,Loss-Making
19,ORD032758,2025-09-17 00:00:00,CUST03756,PROD0085,R002,Marketplace,3,7374.91,28.09,15909.89,18109.59,-2199.70,Loss-Making

In [122]:
profitability_summary = (
    loss_transaction_analysis
    .groupby("Profitability_Status")
    .agg(
        Transactions=("Order_ID", "count"),
        Revenue=("Revenue", "sum"),
        Cost=("Cost", "sum"),
        Profit=("Profit", "sum")
    )
    .reset_index()
)

profitability_summary["Transaction_Percent"] = (
    profitability_summary["Transactions"]
    / profitability_summary["Transactions"].sum()
    * 100
)

profitability_summary = profitability_summary.round(2)

display(profitability_summary)

,Profitability_Status,Transactions,Revenue,Cost,Profit,Transaction_Percent
0,Loss-Making,906,1.136332e+07,1.172192e+07,-3.586003e+05,1.21
1,Profitable,74014,1.350262e+09,1.016318e+09,3.339434e+08,98.79

In [123]:
loss_product_query = """
SELECT
    p.Product_ID,
    p.Product_Name,
    p.Category,

    COUNT(DISTINCT s.Order_ID) AS Loss_Making_Orders,

    ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

    ROUND(SUM(s.Profit), 2) AS Total_Profit,

    ROUND(
        AVG(s.Profit),
        2
    ) AS Average_Profit_Per_Order

FROM sales s

LEFT JOIN product p
    ON s.Product_ID = p.Product_ID

WHERE s.Profit < 0

GROUP BY
    p.Product_ID,
    p.Product_Name,
    p.Category

ORDER BY
    Total_Profit ASC;
"""

loss_product_analysis = pd.read_sql_query(
    loss_product_query,
    conn
)

display(loss_product_analysis.head(20))

,Product_ID,Product_Name,Category,Loss_Making_Orders,Revenue,Total_Profit,Average_Profit_Per_Order
0,PROD0018,Electronics Smartphones 018,Electronics,34,864377.62,-35523.41,-1044.81
1,PROD0017,Electronics Laptops 017,Electronics,34,664124.84,-28091.44,-826.22
2,PROD0076,Fashion Footwear 076,Fashion,55,766005.91,-27511.85,-500.22
3,PROD0107,Fashion Women 107,Fashion,50,698273.08,-24355.82,-487.12
4,PROD0125,Beauty Fragrance 125,Beauty,34,687255.56,-19845.94,-583.70
5,PROD0068,Home Appliances 068,Home,29,736822.65,-18292.59,-630.78
6,PROD0085,Fashion Men 085,Fashion,29,435801.86,-16937.89,-584.07
7,PROD0038,Home Furniture 038,Home,42,487533.50,-16903.42,-402.46
8,PROD0005,Electronics Accessories 005,Electronics,42,474983.00,-16716.00,-398.00
9,PROD0148,Sports Equipment 148,Sports,21,450050.79,-13572.11,-646.29
10,PROD0170,Sports Fitness 170,Sports,15,418040.45,-12981.79,-865.45
11,PROD0050,Home Kitchen 050,Home,21,355432.06,-12149.15,-578.53
12,PROD0113,Beauty Haircare 113,Beauty,16,430614.70,-10222.16,-638.88
13,PROD0136,Beauty Fragrance 136,Beauty,18,369916.24,-9412.08,-522.89
14,PROD0072,Home Kitchen 072,Home,23,224210.54,-8665.60,-376.77
15,PROD0082,Fashion Accessories 082,Fashion,58,235369.48,-8121.53,-140.03
16,PROD0059,Home Furniture 059,Home,28,202008.66,-6291.39,-224.69
17,PROD0071,Home Decor 071,Home,12,267876.48,-5709.69,-475.81
18,PROD0047,Home Appliances 047,Home,9,117712.74,-5581.42,-620.16
19,PROD0165,Sports Outdoor 165,Sports,11,240088.13,-5511.43,-501.04

In [124]:
loss_region_query = """
SELECT
    s.Region_ID,
    r.Region,

    COUNT(DISTINCT s.Order_ID) AS Loss_Making_Orders,

    ROUND(SUM(s.Sales_Amount), 2) AS Revenue,

    ROUND(SUM(s.Profit), 2) AS Total_Loss

FROM sales s

LEFT JOIN region r
    ON s.Region_ID = r.Region_ID

WHERE s.Profit < 0

GROUP BY
    s.Region_ID,
    r.Region

ORDER BY
    Total_Loss ASC;
"""

loss_region_analysis = pd.read_sql_query(
    loss_region_query,
    conn
)

display(loss_region_analysis)

   Region_ID   Region  Loss_Making_Orders    Revenue  Total_Loss
0       R001     West                  44  714550.17   -25787.61
1       R013     East                  47  531046.16   -20603.99
2       R025  Central                  44  491024.81   -19543.41
3       R011    North                  31  446234.79   -18023.92
4       R024  Central                  47  465873.60   -17569.10
5       R016    South                  44  548851.20   -17143.12
6       R005    North                  33  430164.51   -17046.40
7       R022    South                  41  424106.80   -16332.83
8       R018    South                  35  426517.44   -16134.48
9       R007    North                  32  482748.78   -15603.62
10      R010    North                  49  640725.87   -15314.22
11      R002     West                  35  526290.64   -14843.81
12      R014     East                  28  435858.01   -14096.35
13      R006    North                  35  436077.36   -13457.68
14      R012     East                  31  407128.66   -11820.82
15      R009    North                  41  565203.36   -11687.15
16      R017    South                  36  461813.29   -11588.24
17      R003     West                  34  374340.68   -11510.98
18      R015    South                  30  371996.64   -11382.07
19      R023    South                  39  443867.25   -10874.45
20      R004     West                  28  314939.64   -10783.11
21      R008    North                  25  345077.89   -10603.58
22      R020    South                  34  435806.51    -9564.74
23      R021    South                  34  367849.54    -9166.48
24      R019    South                  29  275227.10    -8118.17

In [125]:
loss_channel_query = """
SELECT
    Channel,

    COUNT(DISTINCT Order_ID) AS Loss_Making_Orders,

    ROUND(SUM(Sales_Amount), 2) AS Revenue,

    ROUND(SUM(Profit), 2) AS Total_Loss,

    ROUND(AVG(Profit), 2) AS Average_Loss_Per_Order

FROM sales

WHERE Profit < 0

GROUP BY
    Channel

ORDER BY
    Total_Loss ASC;
"""

loss_channel_analysis = pd.read_sql_query(
    loss_channel_query,
    conn
)

display(loss_channel_analysis)

,Channel,Loss_Making_Orders,Revenue,Total_Loss,Average_Loss_Per_Order
0,Online,485,5935336.33,-194961.80,-401.98
1,Store,225,2831933.29,-85989.71,-382.18
2,Marketplace,196,2596051.08,-77648.82,-396.17

In [126]:
largest_losses = (
    loss_transaction_analysis[
        loss_transaction_analysis["Profit"] < 0
    ]
    .sort_values(
        "Profit",
        ascending=True
    )
    .head(20)
)

display(largest_losses)

,Order_ID,Order_Date,Customer_ID,Product_ID,Region_ID,Channel,Quantity,Unit_Price,Discount_Percent,Revenue,Cost,Profit,Profitability_Status
0,ORD009457,2025-11-25 00:00:00,CUST04944,PROD0017,R011,Online,5,9986.93,24.54,37680.69,41203.35,-3522.66,Loss-Making
1,ORD001931,2024-11-21 00:00:00,CUST04623,PROD0018,R004,Marketplace,4,12486.26,24.21,37853.35,41374.76,-3521.41,Loss-Making
2,ORD007261,2025-11-10 00:00:00,CUST03511,PROD0018,R001,Store,5,12486.26,22.73,48240.67,51718.45,-3477.78,Loss-Making
3,ORD048800,2025-07-13 00:00:00,CUST05992,PROD0018,R022,Online,4,12486.26,23.89,38013.17,41374.76,-3361.59,Loss-Making
4,ORD064446,2024-03-13 00:00:00,CUST03229,PROD0018,R014,Marketplace,4,12486.26,23.21,38352.80,41374.76,-3021.96,Loss-Making
5,ORD030857,2024-07-29 00:00:00,CUST03863,PROD0125,R017,Online,4,12200.98,23.30,37432.61,40405.80,-2973.19,Loss-Making
6,ORD073471,2024-04-09 00:00:00,CUST05891,PROD0068,R018,Online,4,14057.37,23.87,42807.50,45764.56,-2957.06,Loss-Making
7,ORD072378,2025-05-17 00:00:00,CUST02588,PROD0068,R001,Online,5,14057.37,22.76,54289.56,57205.70,-2916.14,Loss-Making
8,ORD050222,2025-09-23 00:00:00,CUST01674,PROD0018,R025,Store,3,12486.26,24.72,28198.97,31031.07,-2832.10,Loss-Making
9,ORD055140,2024-07-14 00:00:00,CUST03722,PROD0017,R005,Store,5,9986.93,22.83,38534.57,41203.35,-2668.78,Loss-Making
10,ORD026305,2025-07-08 00:00:00,CUST00856,PROD0018,R016,Online,6,12486.26,20.56,59514.51,62062.14,-2547.63,Loss-Making
11,ORD045051,2025-02-09 00:00:00,CUST02874,PROD0018,R018,Online,5,12486.26,21.22,49183.38,51718.45,-2535.07,Loss-Making
12,ORD002638,2025-10-12 00:00:00,CUST02343,PROD0076,R007,Marketplace,6,7447.92,21.04,35285.27,37786.56,-2501.29,Loss-Making
13,ORD009535,2025-07-17 00:00:00,CUST05316,PROD0068,R001,Store,3,14057.37,24.36,31898.98,34323.42,-2424.44,Loss-Making
14,ORD047283,2025-07-21 00:00:00,CUST01873,PROD0047,R018,Online,6,7182.73,27.59,31206.09,33625.68,-2419.59,Loss-Making
15,ORD010179,2026-05-19 00:00:00,CUST03859,PROD0017,R011,Marketplace,3,9986.93,25.56,22302.81,24722.01,-2419.20,Loss-Making
16,ORD006848,2024-04-11 00:00:00,CUST05355,PROD0018,R013,Online,4,12486.26,21.97,38972.11,41374.76,-2402.65,Loss-Making
17,ORD022254,2024-03-15 00:00:00,CUST03187,PROD0148,R002,Online,5,8761.87,23.70,33426.53,35663.30,-2236.77,Loss-Making
18,ORD074981,2025-05-15 00:00:00,CUST04277,PROD0170,R011,Store,3,15086.92,25.51,33714.74,35918.52,-2203.78,Loss-Making
19,ORD032758,2025-09-17 00:00:00,CUST03756,PROD0085,R002,Marketplace,3,7374.91,28.09,15909.89,18109.59,-2199.70,Loss-Making

In [127]:
total_loss = abs(
    loss_transaction_analysis.loc[
        loss_transaction_analysis["Profit"] < 0,
        "Profit"
    ].sum()
)

loss_transactions = (
    loss_transaction_analysis["Profit"] < 0
).sum()

total_transactions = len(
    loss_transaction_analysis
)

loss_transaction_percentage = (
    loss_transactions
    / total_transactions
    * 100
)

print(f"Loss-making transactions: {loss_transactions:,}")
print(
    f"Loss-making transaction percentage: "
    f"{loss_transaction_percentage:.2f}%"
)
print(f"Absolute loss from loss-making transactions: {total_loss:,.2f}")

Loss-making transactions: 906
Loss-making transaction percentage: 1.21%
Absolute loss from loss-making transactions: 358,600.33

In [128]:
loss_transaction_analysis.to_csv(
    advanced_sql_path / "loss_transaction_analysis.csv",
    index=False
)

profitability_summary.to_csv(
    advanced_sql_path / "profitability_summary.csv",
    index=False
)

loss_product_analysis.to_csv(
    advanced_sql_path / "loss_product_analysis.csv",
    index=False
)

loss_region_analysis.to_csv(
    advanced_sql_path / "loss_region_analysis.csv",
    index=False
)

loss_channel_analysis.to_csv(
    advanced_sql_path / "loss_channel_analysis.csv",
    index=False
)

print("Saved: loss_transaction_analysis.csv")
print("Saved: profitability_summary.csv")
print("Saved: loss_product_analysis.csv")
print("Saved: loss_region_analysis.csv")
print("Saved: loss_channel_analysis.csv")
print(f"Output folder: {advanced_sql_path}")

Saved: loss_transaction_analysis.csv
Saved: profitability_summary.csv
Saved: loss_product_analysis.csv
Saved: loss_region_analysis.csv
Saved: loss_channel_analysis.csv
Output folder: C:\Users\shubh\Desktop\AI_Sales_Intelligence\data\cleaned\sql_outputs\advanced

In [129]:
# ============================================
# ADVANCED SQL 16: SQL ANALYSIS INVENTORY
# ============================================

sql_analysis_inventory = pd.DataFrame({
    "Analysis": [
        "Sales KPI",
        "Monthly Sales",
        "Customer Performance",
        "Product Performance",
        "Regional Performance",
        "Discount Analysis",
        "Return Analysis",
        "Return Rate",
        "Monthly MoM & YoY Growth",
        "Product Ranking",
        "Customer Ranking & Segmentation",
        "Target vs Actual",
        "Regional Ranking",
        "Top & Bottom Products",
        "Customer Revenue Concentration",
        "Discount Effectiveness",
        "Return & Product Impact",
        "Monthly Business Performance",
        "Seasonality Analysis",
        "Customer RFM Segmentation",
        "Sales Channel Performance",
        "Category Portfolio Analysis",
        "Region × Category Analysis",
        "Profitability & Loss Analysis"
    ],

    "Business_Purpose": [
        "Measure overall business performance",
        "Track monthly revenue and profitability",
        "Measure customer-level performance",
        "Measure product-level performance",
        "Compare regional performance",
        "Understand discount behavior",
        "Analyze return behavior",
        "Calculate valid return rate",
        "Measure revenue growth",
        "Rank products by business performance",
        "Segment customers by value",
        "Compare actual performance with targets",
        "Rank regions across key metrics",
        "Identify strongest and weakest products",
        "Measure customer revenue concentration",
        "Evaluate discount effectiveness",
        "Identify high-return products",
        "Track monthly business performance",
        "Identify recurring seasonal patterns",
        "Segment customers using RFM",
        "Compare sales channels",
        "Evaluate category portfolio",
        "Compare categories across regions",
        "Identify loss-making business areas"
    ],

    "SQL_Concepts": [
        "SUM, COUNT, DISTINCT, aggregation",
        "GROUP BY, date dimension",
        "JOIN, GROUP BY, aggregation",
        "JOIN, GROUP BY, aggregation",
        "JOIN, GROUP BY, aggregation",
        "CASE, GROUP BY",
        "CTE, conditional aggregation",
        "CTE, CROSS JOIN",
        "LAG, window functions",
        "RANK, ROW_NUMBER",
        "RANK, NTILE",
        "CTE, JOIN, aggregation",
        "RANK, window functions",
        "CTE, RANK, CASE",
        "RANK, SUM OVER",
        "CASE, aggregation",
        "CTE, JOIN, conditional aggregation",
        "LAG, window functions",
        "GROUP BY, aggregation",
        "NTILE, window functions",
        "GROUP BY, aggregation",
        "CTE, RANK, CASE",
        "PARTITION BY, RANK",
        "CASE, aggregation, filtering"
    ]
})

display(sql_analysis_inventory)

,Analysis,Business_Purpose,SQL_Concepts
0,Sales KPI,Measure overall business performance,"SUM, COUNT, DISTINCT, aggregation"
1,Monthly Sales,Track monthly revenue and profitability,"GROUP BY, date dimension"
2,Customer Performance,Measure customer-level performance,"JOIN, GROUP BY, aggregation"
3,Product Performance,Measure product-level performance,"JOIN, GROUP BY, aggregation"
4,Regional Performance,Compare regional performance,"JOIN, GROUP BY, aggregation"
5,Discount Analysis,Understand discount behavior,"CASE, GROUP BY"
6,Return Analysis,Analyze return behavior,"CTE, conditional aggregation"
7,Return Rate,Calculate valid return rate,"CTE, CROSS JOIN"
8,Monthly MoM & YoY Growth,Measure revenue growth,"LAG, window functions"
9,Product Ranking,Rank products by business performance,"RANK, ROW_NUMBER"
10,Customer Ranking & Segmentation,Segment customers by value,"RANK, NTILE"
11,Target vs Actual,Compare actual performance with targets,"CTE, JOIN, aggregation"
12,Regional Ranking,Rank regions across key metrics,"RANK, window functions"
13,Top & Bottom Products,Identify strongest and weakest products,"CTE, RANK, CASE"
14,Customer Revenue Concentration,Measure customer revenue concentration,"RANK, SUM OVER"
15,Discount Effectiveness,Evaluate discount effectiveness,"CASE, aggregation"
16,Return & Product Impact,Identify high-return products,"CTE, JOIN, conditional aggregation"
17,Monthly Business Performance,Track monthly business performance,"LAG, window functions"
18,Seasonality Analysis,Identify recurring seasonal patterns,"GROUP BY, aggregation"
19,Customer RFM Segmentation,Segment customers using RFM,"NTILE, window functions"
20,Sales Channel Performance,Compare sales channels,"GROUP BY, aggregation"
21,Category Portfolio Analysis,Evaluate category portfolio,"CTE, RANK, CASE"
22,Region × Category Analysis,Compare categories across regions,"PARTITION BY, RANK"
23,Profitability & Loss Analysis,Identify loss-making business areas,"CASE, aggregation, filtering"

In [130]:
sql_analysis_inventory.to_csv(
    advanced_sql_path / "sql_analysis_inventory.csv",
    index=False
)

print("Saved: sql_analysis_inventory.csv")
print(f"Output folder: {advanced_sql_path}")

Saved: sql_analysis_inventory.csv
Output folder: C:\Users\shubh\Desktop\AI_Sales_Intelligence\data\cleaned\sql_outputs\advanced

In [131]:
sql_files = sorted(
    advanced_sql_path.glob("*.csv")
)

print(f"Advanced SQL output files: {len(sql_files)}")
print()

for file in sql_files:
    print(file.name)

Advanced SQL output files: 29

best_category_by_region.csv
best_region_by_category.csv
category_portfolio_analysis.csv
category_portfolio_summary.csv
channel_performance.csv
channel_year_performance.csv
customer_concentration_summary.csv
customer_ranking.csv
customer_revenue_concentration.csv
customer_rfm_analysis.csv
customer_segments.csv
discount_effectiveness.csv
loss_channel_analysis.csv
loss_product_analysis.csv
loss_region_analysis.csv
loss_transaction_analysis.csv
monthly_business_performance.csv
monthly_growth.csv
product_ranking.csv
profitability_summary.csv
region_category_analysis.csv
regional_ranking.csv
regional_target_summary.csv
return_product_analysis.csv
return_risk_summary.csv
rfm_segment_summary.csv
seasonality_analysis.csv
sql_analysis_inventory.csv
target_vs_actual.csv